# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: AchievementTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'AchievementTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import table_basic_pb2 as table__basic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x41\x63hievementTable.proto\x12\x06\x62okura\x1a\x11table_basic.proto\"\xb7\x01\n\x14\x41\x63hievementTableBase\x12\x0b\n\x02id\x18\xb7\x0b \x01(\x05\x12\r\n\x04name\x18\xb0\x01 \x01(\t\x12\x12\n\tmain_type\x18\xba\x0e \x01(\x05\x12\x11\n\x08sub_type\x18\xb5\x0f \x01(\x05\x12\r\n\x04\x64\x65sc\x18\xe3\x03 \x01(\t\x12\r\n\x04show\x18\xd9\x04 \x01(\x05\x12\x13\n\ntime_limit\x18\xcd\x0e \x01(\x05\x12\x1a\n\x05\x61ward\x18\x95\x01 \x01(\x0b\x32\n.int_table\x12\r\n\x04icon\x18\xba\t \x01(\t\"\x98\x01\n\x13\x41\x63hievementTableMgr\x12\x35\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32&.bokura.AchievementTableMgr.DatasEntry\x1aJ\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12+\n\x05value\x18\x02 \x01(\x0b\x32\x1c.bokura.AchievementTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AchievementTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACHIEVEMENTTABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_ACHIEVEMENTTABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_ACHIEVEMENTTABLEBASE']._serialized_start=54
  _globals['_ACHIEVEMENTTABLEBASE']._serialized_end=237
  _globals['_ACHIEVEMENTTABLEMGR']._serialized_start=240
  _globals['_ACHIEVEMENTTABLEMGR']._serialized_end=392
  _globals['_ACHIEVEMENTTABLEMGR_DATASENTRY']._serialized_start=318
  _globals['_ACHIEVEMENTTABLEMGR_DATASENTRY']._serialized_end=392
# @@protoc_insertion_point(module_scope)
