# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ActionShowDataTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ActionShowDataTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x41\x63tionShowDataTable.proto\x12\x06\x62okura\"\x90\x02\n\x17\x41\x63tionShowDataTableBase\x12\x0b\n\x02id\x18\xb7\x0b \x01(\x03\x12\x0e\n\x05start\x18\xa6\x05 \x01(\x02\x12\x11\n\x08\x64uration\x18\xa0\x04 \x01(\x02\x12\x0c\n\x03\x65nd\x18\x87\x0b \x01(\x02\x12\x14\n\x0bis_attacker\x18\x98\x07 \x01(\x08\x12\x11\n\x08state_id\x18\xb4\x02 \x01(\x05\x12\x11\n\x08group_id\x18\xc4\x01 \x01(\x05\x12\x14\n\x0b\x61\x63tion_name\x18\xbc\n \x01(\t\x12\x11\n\x08res_path\x18\xa4\x04 \x01(\t\x12\x14\n\x0b\x61\x63tion_type\x18\xbe\x06 \x01(\x05\x12\x0f\n\x07is_loop\x18m \x01(\x08\x12\x11\n\x08is_upend\x18\xee\x03 \x01(\x08\x12\x18\n\x0f\x65nhance_damping\x18\xda\r \x01(\x08\"\xa1\x01\n\x16\x41\x63tionShowDataTableMgr\x12\x38\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32).bokura.ActionShowDataTableMgr.DatasEntry\x1aM\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x03\x12.\n\x05value\x18\x02 \x01(\x0b\x32\x1f.bokura.ActionShowDataTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ActionShowDataTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACTIONSHOWDATATABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_ACTIONSHOWDATATABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_ACTIONSHOWDATATABLEBASE']._serialized_start=38
  _globals['_ACTIONSHOWDATATABLEBASE']._serialized_end=310
  _globals['_ACTIONSHOWDATATABLEMGR']._serialized_start=313
  _globals['_ACTIONSHOWDATATABLEMGR']._serialized_end=474
  _globals['_ACTIONSHOWDATATABLEMGR_DATASENTRY']._serialized_start=397
  _globals['_ACTIONSHOWDATATABLEMGR_DATASENTRY']._serialized_end=474
# @@protoc_insertion_point(module_scope)
