# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: AudioShowDataTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'AudioShowDataTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x41udioShowDataTable.proto\x12\x06\x62okura\"\xb6\x01\n\x16\x41udioShowDataTableBase\x12\x0b\n\x02id\x18\xb7\x0b \x01(\x03\x12\x0e\n\x05start\x18\xa6\x05 \x01(\x02\x12\x11\n\x08\x64uration\x18\xa0\x04 \x01(\x02\x12\x0c\n\x03\x65nd\x18\x87\x0b \x01(\x02\x12\x14\n\x0bis_attacker\x18\x98\x07 \x01(\x08\x12\x11\n\x08state_id\x18\xb4\x02 \x01(\x05\x12\x11\n\x08group_id\x18\xc4\x01 \x01(\x05\x12\r\n\x04loop\x18\x89\x0f \x01(\x08\x12\x13\n\nevent_name\x18\xef\t \x01(\t\"\x9e\x01\n\x15\x41udioShowDataTableMgr\x12\x37\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32(.bokura.AudioShowDataTableMgr.DatasEntry\x1aL\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x03\x12-\n\x05value\x18\x02 \x01(\x0b\x32\x1e.bokura.AudioShowDataTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AudioShowDataTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIOSHOWDATATABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_AUDIOSHOWDATATABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_AUDIOSHOWDATATABLEBASE']._serialized_start=37
  _globals['_AUDIOSHOWDATATABLEBASE']._serialized_end=219
  _globals['_AUDIOSHOWDATATABLEMGR']._serialized_start=222
  _globals['_AUDIOSHOWDATATABLEMGR']._serialized_end=380
  _globals['_AUDIOSHOWDATATABLEMGR_DATASENTRY']._serialized_start=304
  _globals['_AUDIOSHOWDATATABLEMGR_DATASENTRY']._serialized_end=380
# @@protoc_insertion_point(module_scope)
