# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: AwardAttrFixRatioTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'AwardAttrFixRatioTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import table_basic_pb2 as table__basic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x41wardAttrFixRatioTable.proto\x12\x06\x62okura\x1a\x11table_basic.proto\"\x80\x01\n\x1a\x41wardAttrFixRatioTableBase\x12\x0b\n\x02id\x18\xb7\x0b \x01(\x05\x12\x10\n\x07\x61ttr_id\x18\x9b\n \x01(\x05\x12\r\n\x04type\x18\xa1\x05 \x01(\x05\x12\x12\n\titem_type\x18\xa9\x06 \x01(\x05\x12 \n\x0bitem_params\x18\xa1\x0f \x01(\x0b\x32\n.int_table\"\xaa\x01\n\x19\x41wardAttrFixRatioTableMgr\x12;\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32,.bokura.AwardAttrFixRatioTableMgr.DatasEntry\x1aP\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x31\n\x05value\x18\x02 \x01(\x0b\x32\".bokura.AwardAttrFixRatioTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AwardAttrFixRatioTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AWARDATTRFIXRATIOTABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_AWARDATTRFIXRATIOTABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_AWARDATTRFIXRATIOTABLEBASE']._serialized_start=60
  _globals['_AWARDATTRFIXRATIOTABLEBASE']._serialized_end=188
  _globals['_AWARDATTRFIXRATIOTABLEMGR']._serialized_start=191
  _globals['_AWARDATTRFIXRATIOTABLEMGR']._serialized_end=361
  _globals['_AWARDATTRFIXRATIOTABLEMGR_DATASENTRY']._serialized_start=281
  _globals['_AWARDATTRFIXRATIOTABLEMGR_DATASENTRY']._serialized_end=361
# @@protoc_insertion_point(module_scope)
