# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: BasicAttrEffectTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'BasicAttrEffectTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import table_basic_pb2 as table__basic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x42\x61sicAttrEffectTable.proto\x12\x06\x62okura\x1a\x11table_basic.proto\"\x84\x04\n\x18\x42\x61sicAttrEffectTableBase\x12\x0b\n\x02id\x18\xb7\x0b \x01(\x05\x12+\n\x13\x61ttr_strength_table\x18\x90\x08 \x01(\x0b\x32\r.number_table\x12\x1a\n\x11\x61ttr_strength_max\x18\xde\x0b \x01(\x05\x12+\n\x13\x61ttr_vitality_table\x18\xcf\x06 \x01(\x0b\x32\r.number_table\x12\x1a\n\x11\x61ttr_vitality_max\x18\x96\x03 \x01(\x05\x12,\n\x14\x61ttr_dexterity_table\x18\xcc\x08 \x01(\x0b\x32\r.number_table\x12\x1b\n\x12\x61ttr_dexterity_max\x18\xc5\x0f \x01(\x05\x12/\n\x17\x61ttr_intelligence_table\x18\xb0\x07 \x01(\x0b\x32\r.number_table\x12\x1e\n\x15\x61ttr_intelligence_max\x18\xe5\x0f \x01(\x05\x12\'\n\x0f\x61ttr_mind_table\x18\xfd\x04 \x01(\x0b\x32\r.number_table\x12\x16\n\rattr_mind_max\x18\xb3\x0f \x01(\x05\x12*\n\x12\x61ttr_observe_table\x18\x81\x03 \x01(\x0b\x32\r.number_table\x12\x19\n\x10\x61ttr_observe_max\x18\x9a\r \x01(\x05\x12%\n\x11\x61ttr_introduction\x18\x89\x0b \x01(\x0b\x32\t.mlstring\"\xa4\x01\n\x17\x42\x61sicAttrEffectTableMgr\x12\x39\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32*.bokura.BasicAttrEffectTableMgr.DatasEntry\x1aN\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12/\n\x05value\x18\x02 \x01(\x0b\x32 .bokura.BasicAttrEffectTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BasicAttrEffectTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BASICATTREFFECTTABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_BASICATTREFFECTTABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_BASICATTREFFECTTABLEBASE']._serialized_start=58
  _globals['_BASICATTREFFECTTABLEBASE']._serialized_end=574
  _globals['_BASICATTREFFECTTABLEMGR']._serialized_start=577
  _globals['_BASICATTREFFECTTABLEMGR']._serialized_end=741
  _globals['_BASICATTREFFECTTABLEMGR_DATASENTRY']._serialized_start=663
  _globals['_BASICATTREFFECTTABLEMGR_DATASENTRY']._serialized_end=741
# @@protoc_insertion_point(module_scope)
