# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: BattlePassGlobalTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'BattlePassGlobalTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import table_basic_pb2 as table__basic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x42\x61ttlePassGlobalTable.proto\x12\x06\x62okura\x1a\x11table_basic.proto\"\xb5\x03\n\x19\x42\x61ttlePassGlobalTableBase\x12\x0b\n\x02id\x18\xb7\x0b \x01(\x05\x12\x19\n\x10weekly_exp_limit\x18\x9c\n \x01(\x05\x12$\n\x10normal_pass_name\x18\xfa\x0f \x01(\x0b\x32\t.mlstring\x12#\n\x0fprime_pass_name\x18\xa3\x04 \x01(\x0b\x32\t.mlstring\x12\x1c\n\x07\x66\x61shion\x18\xed\x0e \x01(\x0b\x32\n.int_table\x12\x16\n\rfashion_level\x18\x8f\x0b \x01(\x05\x12\"\n\raward_preview\x18\x89\t \x01(\x0b\x32\n.int_array\x12\x1d\n\x14prime_pass_add_level\x18\x92\x05 \x01(\x05\x12&\n\x11prime_extra_award\x18\xb8\x07 \x01(\x0b\x32\n.int_array\x12\x1f\n\nlevel_cost\x18\xf3\x06 \x01(\x0b\x32\n.int_array\x12\x1e\n\x16normal_pass_payment_id\x18{ \x01(\x05\x12\x1e\n\x15prime_pass_payment_id\x18\xb4\x01 \x01(\x05\x12#\n\x1apass_price_diff_payment_id\x18\x8a\x04 \x01(\x05\"\xa7\x01\n\x18\x42\x61ttlePassGlobalTableMgr\x12:\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32+.bokura.BattlePassGlobalTableMgr.DatasEntry\x1aO\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x30\n\x05value\x18\x02 \x01(\x0b\x32!.bokura.BattlePassGlobalTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BattlePassGlobalTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BATTLEPASSGLOBALTABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_BATTLEPASSGLOBALTABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_BATTLEPASSGLOBALTABLEBASE']._serialized_start=59
  _globals['_BATTLEPASSGLOBALTABLEBASE']._serialized_end=496
  _globals['_BATTLEPASSGLOBALTABLEMGR']._serialized_start=499
  _globals['_BATTLEPASSGLOBALTABLEMGR']._serialized_end=666
  _globals['_BATTLEPASSGLOBALTABLEMGR_DATASENTRY']._serialized_start=587
  _globals['_BATTLEPASSGLOBALTABLEMGR_DATASENTRY']._serialized_end=666
# @@protoc_insertion_point(module_scope)
