# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: BDTAGLinkTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'BDTAGLinkTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import table_basic_pb2 as table__basic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x42\x44TAGLinkTable.proto\x12\x06\x62okura\x1a\x11table_basic.proto\"\xe1\x01\n\x12\x42\x44TAGLinkTableBase\x12\x0b\n\x02id\x18\xb7\x0b \x01(\x05\x12\r\n\x04note\x18\xc5\x03 \x01(\t\x12\x12\n\tnote_type\x18\x80\x02 \x01(\x05\x12\x12\n\tfind_type\x18\xbe\x06 \x01(\x05\x12\x12\n\tfind_body\x18\x92\x0c \x01(\t\x12\'\n\x0f\x66ind_conditions\x18\xe4\x0e \x01(\x0b\x32\r.string_table\x12\x14\n\x0btarget_para\x18\xf7\x0c \x01(\t\x12\x19\n\x10skill_level_type\x18\xfc\x0c \x01(\x05\x12\x19\n\x10target_node_type\x18\xa5\x0f \x01(\x05\"\x92\x01\n\x11\x42\x44TAGLinkTableMgr\x12\x33\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32$.bokura.BDTAGLinkTableMgr.DatasEntry\x1aH\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12)\n\x05value\x18\x02 \x01(\x0b\x32\x1a.bokura.BDTAGLinkTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BDTAGLinkTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BDTAGLINKTABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_BDTAGLINKTABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_BDTAGLINKTABLEBASE']._serialized_start=52
  _globals['_BDTAGLINKTABLEBASE']._serialized_end=277
  _globals['_BDTAGLINKTABLEMGR']._serialized_start=280
  _globals['_BDTAGLINKTABLEMGR']._serialized_end=426
  _globals['_BDTAGLINKTABLEMGR_DATASENTRY']._serialized_start=354
  _globals['_BDTAGLINKTABLEMGR_DATASENTRY']._serialized_end=426
# @@protoc_insertion_point(module_scope)
