# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: BulletRunTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'BulletRunTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import table_basic_pb2 as table__basic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x42ulletRunTable.proto\x12\x06\x62okura\x1a\x11table_basic.proto\"\xdc\x05\n\x12\x42ulletRunTableBase\x12\x0b\n\x02id\x18\xb7\x0b \x01(\x03\x12\x14\n\x0bmotion_type\x18\xc4\x0f \x01(\x05\x12\x14\n\x0bstart_speed\x18\xdb\x03 \x01(\x02\x12\x1a\n\x11\x61\x63\x63\x65lerated_speed\x18\xcf\x0e \x01(\x02\x12\x12\n\tmax_speed\x18\xb2\x06 \x01(\x02\x12\x17\n\x0e\x64irection_type\x18\xbc\x07 \x01(\x05\x12\x19\n\x10is_follow_target\x18\x99\r \x01(\x08\x12\x19\n\x10max_follow_angle\x18\xdd\x01 \x01(\x02\x12\x17\n\x0e\x65x_start_speed\x18\xde\n \x01(\x02\x12\x1d\n\x14\x65x_accelerated_speed\x18\xae\x05 \x01(\x02\x12\x15\n\x0c\x65x_max_speed\x18\xf1\x04 \x01(\x02\x12\x12\n\ncurve_path\x18# \x01(\t\x12\x11\n\x08\x63urve_id\x18\xaf\x03 \x01(\x03\x12\x19\n\x10is_random_radian\x18\xba\x02 \x01(\x08\x12\x17\n\x0erandom_pos_top\x18\xb9\x03 \x01(\x02\x12\x1a\n\x11random_pos_bottom\x18\xa1\x03 \x01(\x02\x12\x18\n\x0frandom_pos_left\x18\x83\x0f \x01(\x02\x12\x19\n\x10random_pos_right\x18\xcf\x03 \x01(\x02\x12\x14\n\x0b\x66ollow_type\x18\xa0\t \x01(\x05\x12\x1d\n\noffset_pos\x18\xa1\x0c \x01(\x0b\x32\x08.vector3\x12\x15\n\x0coriginal_dir\x18\xc4\x07 \x01(\x02\x12\x11\n\x08min_zoom\x18\xb9\t \x01(\x02\x12\x11\n\x08max_zoom\x18\x83\x0b \x01(\x02\x12\x13\n\nzoom_speed\x18\xc7\x04 \x01(\x02\x12\x15\n\x0czoom_is_loop\x18\xc0\x06 \x01(\x08\x12\x19\n\x10\x66ollow_config_id\x18\xac\x05 \x01(\x05\x12\x17\n\x0e\x63heck_obstacle\x18\xa6\x07 \x01(\x08\x12\x11\n\x08is_stand\x18\xef\n \x01(\x08\x12\x17\n\x0eis_lock_target\x18\xa4\x06 \x01(\x08\x12\x15\n\x0cis_can_dodge\x18\x8a\x03 \x01(\x08\"\x92\x01\n\x11\x42ulletRunTableMgr\x12\x33\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32$.bokura.BulletRunTableMgr.DatasEntry\x1aH\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x03\x12)\n\x05value\x18\x02 \x01(\x0b\x32\x1a.bokura.BulletRunTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BulletRunTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BULLETRUNTABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_BULLETRUNTABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_BULLETRUNTABLEBASE']._serialized_start=52
  _globals['_BULLETRUNTABLEBASE']._serialized_end=784
  _globals['_BULLETRUNTABLEMGR']._serialized_start=787
  _globals['_BULLETRUNTABLEMGR']._serialized_end=933
  _globals['_BULLETRUNTABLEMGR_DATASENTRY']._serialized_start=861
  _globals['_BULLETRUNTABLEMGR_DATASENTRY']._serialized_end=933
# @@protoc_insertion_point(module_scope)
