# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: BulletShapeTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'BulletShapeTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import table_basic_pb2 as table__basic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x42ulletShapeTable.proto\x12\x06\x62okura\x1a\x11table_basic.proto\"\xad\x01\n\x14\x42ulletShapeTableBase\x12\x0b\n\x02id\x18\xb7\x0b \x01(\x03\x12\x13\n\nshape_type\x18\xf1\x06 \x01(\x05\x12\"\n\nshape_data\x18\xed\x0e \x01(\x0b\x32\r.number_array\x12#\n\x0bscale_curve\x18\xf3\x04 \x01(\x0b\x32\r.number_table\x12*\n\x12scale_curve_sample\x18\xfe\x04 \x01(\x0b\x32\r.number_table\"\x98\x01\n\x13\x42ulletShapeTableMgr\x12\x35\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32&.bokura.BulletShapeTableMgr.DatasEntry\x1aJ\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x03\x12+\n\x05value\x18\x02 \x01(\x0b\x32\x1c.bokura.BulletShapeTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BulletShapeTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BULLETSHAPETABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_BULLETSHAPETABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_BULLETSHAPETABLEBASE']._serialized_start=54
  _globals['_BULLETSHAPETABLEBASE']._serialized_end=227
  _globals['_BULLETSHAPETABLEMGR']._serialized_start=230
  _globals['_BULLETSHAPETABLEMGR']._serialized_end=382
  _globals['_BULLETSHAPETABLEMGR_DATASENTRY']._serialized_start=308
  _globals['_BULLETSHAPETABLEMGR_DATASENTRY']._serialized_end=382
# @@protoc_insertion_point(module_scope)
