# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ChatBubble.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ChatBubble.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import table_basic_pb2 as table__basic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x43hatBubble.proto\x12\x06\x62okura\x1a\x11table_basic.proto\"W\n\x0e\x43hatBubbleBase\x12\x0b\n\x02id\x18\xb7\x0b \x01(\x05\x12\x1b\n\x07\x63ontent\x18\x8f\x06 \x01(\x0b\x32\t.mlstring\x12\x1b\n\x12plot_characters_id\x18\x82\n \x01(\x05\"\x86\x01\n\rChatBubbleMgr\x12/\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32 .bokura.ChatBubbleMgr.DatasEntry\x1a\x44\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.bokura.ChatBubbleBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ChatBubble_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHATBUBBLEMGR_DATASENTRY']._loaded_options = None
  _globals['_CHATBUBBLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_CHATBUBBLEBASE']._serialized_start=47
  _globals['_CHATBUBBLEBASE']._serialized_end=134
  _globals['_CHATBUBBLEMGR']._serialized_start=137
  _globals['_CHATBUBBLEMGR']._serialized_end=271
  _globals['_CHATBUBBLEMGR_DATASENTRY']._serialized_start=203
  _globals['_CHATBUBBLEMGR_DATASENTRY']._serialized_end=271
# @@protoc_insertion_point(module_scope)
