# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ChatStickersTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ChatStickersTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x43hatStickersTable.proto\x12\x06\x62okura\"j\n\x15\x43hatStickersTableBase\x12\x0b\n\x02id\x18\xb7\x0b \x01(\x05\x12\r\n\x04type\x18\xa1\x05 \x01(\x05\x12\x11\n\x08group_id\x18\xc4\x01 \x01(\x05\x12\x0c\n\x03res\x18\xfb\t \x01(\t\x12\x14\n\x0bunlock_item\x18\xbe\x05 \x01(\x05\"\x9b\x01\n\x14\x43hatStickersTableMgr\x12\x36\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32\'.bokura.ChatStickersTableMgr.DatasEntry\x1aK\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12,\n\x05value\x18\x02 \x01(\x0b\x32\x1d.bokura.ChatStickersTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ChatStickersTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHATSTICKERSTABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_CHATSTICKERSTABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_CHATSTICKERSTABLEBASE']._serialized_start=35
  _globals['_CHATSTICKERSTABLEBASE']._serialized_end=141
  _globals['_CHATSTICKERSTABLEMGR']._serialized_start=144
  _globals['_CHATSTICKERSTABLEMGR']._serialized_end=299
  _globals['_CHATSTICKERSTABLEMGR_DATASENTRY']._serialized_start=224
  _globals['_CHATSTICKERSTABLEMGR_DATASENTRY']._serialized_end=299
# @@protoc_insertion_point(module_scope)
