# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ColorGroupTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ColorGroupTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import table_basic_pb2 as table__basic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x43olorGroupTable.proto\x12\x06\x62okura\x1a\x11table_basic.proto\"\xfc\x02\n\x13\x43olorGroupTableBase\x12\x0b\n\x02id\x18\xb7\x0b \x01(\x05\x12\r\n\x04type\x18\xa1\x05 \x01(\x05\x12\x0e\n\x05\x63olor\x18\xcb\x0f \x01(\t\x12\x18\n\x03hue\x18\xfb\x0b \x01(\x0b\x32\n.int_table\x12\x16\n\rif_saturation\x18\xcb\x0b \x01(\x05\x12\x1f\n\nsaturation\x18\xd2\t \x01(\x0b\x32\n.int_table\x12\x11\n\x08if_value\x18\xb9\n \x01(\x05\x12\x1a\n\x05value\x18\xe8\x04 \x01(\x0b\x32\n.int_table\x12\x1c\n\x08ui_color\x18\x1a \x01(\x0b\x32\n.int_table\x12\x1d\n\x08\x63onsumeh\x18\xe9\x01 \x01(\x0b\x32\n.int_table\x12\x19\n\x04zone\x18\xb3\x0f \x01(\x0b\x32\n.int_table\x12\x1f\n\x0b\x63onsume_low\x18I \x01(\x0b\x32\n.int_table\x12!\n\x0c\x63onsume_high\x18\xe1\r \x01(\x0b\x32\n.int_table\x12\x1b\n\x06unlock\x18\x82\r \x01(\x0b\x32\n.int_table\"\x95\x01\n\x12\x43olorGroupTableMgr\x12\x34\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32%.bokura.ColorGroupTableMgr.DatasEntry\x1aI\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12*\n\x05value\x18\x02 \x01(\x0b\x32\x1b.bokura.ColorGroupTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ColorGroupTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COLORGROUPTABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_COLORGROUPTABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_COLORGROUPTABLEBASE']._serialized_start=53
  _globals['_COLORGROUPTABLEBASE']._serialized_end=433
  _globals['_COLORGROUPTABLEMGR']._serialized_start=436
  _globals['_COLORGROUPTABLEMGR']._serialized_end=585
  _globals['_COLORGROUPTABLEMGR_DATASENTRY']._serialized_start=512
  _globals['_COLORGROUPTABLEMGR_DATASENTRY']._serialized_end=585
# @@protoc_insertion_point(module_scope)
