# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: CounterTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'CounterTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x43ounterTable.proto\x12\x06\x62okura\"k\n\x10\x43ounterTableBase\x12\x0b\n\x02id\x18\xb7\x0b \x01(\x03\x12\r\n\x04name\x18\xb7\x03 \x01(\t\x12\x15\n\rtime_table_id\x18\x38 \x01(\x03\x12\x14\n\x0brefresh_num\x18\xe0\n \x01(\x05\x12\x0e\n\x05limit\x18\x80\x05 \x01(\x05\"\x8c\x01\n\x0f\x43ounterTableMgr\x12\x31\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32\".bokura.CounterTableMgr.DatasEntry\x1a\x46\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x03\x12\'\n\x05value\x18\x02 \x01(\x0b\x32\x18.bokura.CounterTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CounterTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COUNTERTABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_COUNTERTABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_COUNTERTABLEBASE']._serialized_start=30
  _globals['_COUNTERTABLEBASE']._serialized_end=137
  _globals['_COUNTERTABLEMGR']._serialized_start=140
  _globals['_COUNTERTABLEMGR']._serialized_end=280
  _globals['_COUNTERTABLEMGR_DATASENTRY']._serialized_start=210
  _globals['_COUNTERTABLEMGR_DATASENTRY']._serialized_end=280
# @@protoc_insertion_point(module_scope)
