# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: DayAndNightTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'DayAndNightTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import table_basic_pb2 as table__basic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x44\x61yAndNightTable.proto\x12\x06\x62okura\x1a\x11table_basic.proto\"X\n\x14\x44\x61yAndNightTableBase\x12\x0b\n\x02id\x18\xb7\x0b \x01(\x05\x12\x13\n\ncycle_time\x18\xfe\x0b \x01(\x05\x12\x1e\n\x05stage\x18\xe4\x0c \x01(\x0b\x32\x0e.vector2_array\"\x98\x01\n\x13\x44\x61yAndNightTableMgr\x12\x35\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32&.bokura.DayAndNightTableMgr.DatasEntry\x1aJ\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12+\n\x05value\x18\x02 \x01(\x0b\x32\x1c.bokura.DayAndNightTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DayAndNightTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DAYANDNIGHTTABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_DAYANDNIGHTTABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_DAYANDNIGHTTABLEBASE']._serialized_start=53
  _globals['_DAYANDNIGHTTABLEBASE']._serialized_end=141
  _globals['_DAYANDNIGHTTABLEMGR']._serialized_start=144
  _globals['_DAYANDNIGHTTABLEMGR']._serialized_end=296
  _globals['_DAYANDNIGHTTABLEMGR_DATASENTRY']._serialized_start=222
  _globals['_DAYANDNIGHTTABLEMGR_DATASENTRY']._serialized_end=296
# @@protoc_insertion_point(module_scope)
