# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: DungeonTitleTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'DungeonTitleTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import table_basic_pb2 as table__basic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x44ungeonTitleTable.proto\x12\x06\x62okura\x1a\x11table_basic.proto\"l\n\x15\x44ungeonTitleTableBase\x12\x0b\n\x02id\x18\xb7\x0b \x01(\x05\x12\x18\n\x04name\x18\xb7\x03 \x01(\x0b\x32\t.mlstring\x12\x1b\n\x07\x63ontent\x18\x8f\x06 \x01(\x0b\x32\t.mlstring\x12\x0f\n\x06weight\x18\x8c\x01 \x01(\x05\"\x9b\x01\n\x14\x44ungeonTitleTableMgr\x12\x36\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32\'.bokura.DungeonTitleTableMgr.DatasEntry\x1aK\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12,\n\x05value\x18\x02 \x01(\x0b\x32\x1d.bokura.DungeonTitleTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DungeonTitleTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DUNGEONTITLETABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_DUNGEONTITLETABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_DUNGEONTITLETABLEBASE']._serialized_start=54
  _globals['_DUNGEONTITLETABLEBASE']._serialized_end=162
  _globals['_DUNGEONTITLETABLEMGR']._serialized_start=165
  _globals['_DUNGEONTITLETABLEMGR']._serialized_end=320
  _globals['_DUNGEONTITLETABLEMGR_DATASENTRY']._serialized_start=245
  _globals['_DUNGEONTITLETABLEMGR_DATASENTRY']._serialized_end=320
# @@protoc_insertion_point(module_scope)
