from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class ECommunityAuthorityOperateOptionType(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    CommunityAuthorityOperateOptionType: _ClassVar[ECommunityAuthorityOperateOptionType]
    CommunityAuthorityOperateOptionTypeFriend: _ClassVar[ECommunityAuthorityOperateOptionType]
    CommunityAuthorityOperateOptionTypeAll: _ClassVar[ECommunityAuthorityOperateOptionType]
    CommunityAuthorityOperateOptionTypeCohabitant: _ClassVar[ECommunityAuthorityOperateOptionType]
    CommunityAuthorityOperateOptionTypeSeedOwner: _ClassVar[ECommunityAuthorityOperateOptionType]
    CommunityAuthorityOperateOptionTypeNonSeedOwner: _ClassVar[ECommunityAuthorityOperateOptionType]
    CommunityAuthorityOperateOptionTypeFurnitureMaker: _ClassVar[ECommunityAuthorityOperateOptionType]
    CommunityAuthorityOperateOptionTypeHomeOwner: _ClassVar[ECommunityAuthorityOperateOptionType]
    CommunityAuthorityOperateOptionTypeFurnitureOwner: _ClassVar[ECommunityAuthorityOperateOptionType]
    CommunityAuthorityOperateOptionTypeNoOne: _ClassVar[ECommunityAuthorityOperateOptionType]
CommunityAuthorityOperateOptionType: ECommunityAuthorityOperateOptionType
CommunityAuthorityOperateOptionTypeFriend: ECommunityAuthorityOperateOptionType
CommunityAuthorityOperateOptionTypeAll: ECommunityAuthorityOperateOptionType
CommunityAuthorityOperateOptionTypeCohabitant: ECommunityAuthorityOperateOptionType
CommunityAuthorityOperateOptionTypeSeedOwner: ECommunityAuthorityOperateOptionType
CommunityAuthorityOperateOptionTypeNonSeedOwner: ECommunityAuthorityOperateOptionType
CommunityAuthorityOperateOptionTypeFurnitureMaker: ECommunityAuthorityOperateOptionType
CommunityAuthorityOperateOptionTypeHomeOwner: ECommunityAuthorityOperateOptionType
CommunityAuthorityOperateOptionTypeFurnitureOwner: ECommunityAuthorityOperateOptionType
CommunityAuthorityOperateOptionTypeNoOne: ECommunityAuthorityOperateOptionType
