# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: enum_e_temp_attr_type.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'enum_e_temp_attr_type.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x65num_e_temp_attr_type.proto\x12\x06zproto*\xde\x01\n\rETempAttrType\x12\x12\n\x0eTempAttrGlobal\x10\x00\x12\x11\n\rTempAttrSkill\x10\x01\x12\x14\n\x10TempAttrFightRes\x10\x02\x12\x0f\n\x0bTempAttrTag\x10\x03\x12\x10\n\x0cTempAttrBuff\x10\x04\x12\x15\n\x11TempAttrFightAttr\x10\x05\x12\x0f\n\x0bTempAttrJob\x10\x06\x12\x11\n\rTempAttrDummy\x10\x07\x12\x1a\n\x16TempAttrLifeProfession\x10\x08\x12\x16\n\x12TempAttrRogueEntry\x10\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'enum_e_temp_attr_type_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ETEMPATTRTYPE']._serialized_start=40
  _globals['_ETEMPATTRTYPE']._serialized_end=262
# @@protoc_insertion_point(module_scope)
