# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: enum_e_climb_type.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'enum_e_climb_type.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x65num_e_climb_type.proto\x12\x06zproto*\xac\x01\n\nEClimbType\x12\r\n\tClimbIdle\x10\x00\x12\x0c\n\x08\x43limbing\x10\x01\x12\r\n\tClimbRush\x10\x02\x12\x0c\n\x08ShinIdle\x10\n\x12\x0b\n\x07Shining\x10\x0b\x12\r\n\tShinCross\x10\x0c\x12\x0e\n\nTopBraceUp\x10\x14\x12\x10\n\x0cTopBraceDown\x10\x15\x12\x11\n\rBottomBraceUp\x10\x16\x12\x13\n\x0f\x42ottomBraceDown\x10\x17\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'enum_e_climb_type_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ECLIMBTYPE']._serialized_start=36
  _globals['_ECLIMBTYPE']._serialized_end=208
# @@protoc_insertion_point(module_scope)
