# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: enum_e_show_piece_type.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'enum_e_show_piece_type.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x65num_e_show_piece_type.proto\x12\x06zproto*\x83\x01\n\x0e\x45ShowPieceType\x12\x11\n\rShowPieceNull\x10\x00\x12\x19\n\x15ShowPieceNormalAction\x10\x01\x12\x12\n\x0eShowPieceEmote\x10\x02\x12\x19\n\x15ShowPieceDoubleAction\x10\x03\x12\x14\n\x10ShowPieceSticker\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'enum_e_show_piece_type_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ESHOWPIECETYPE']._serialized_start=41
  _globals['_ESHOWPIECETYPE']._serialized_end=172
# @@protoc_insertion_point(module_scope)
