# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: enum_login_plat_form_type.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'enum_login_plat_form_type.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x65num_login_plat_form_type.proto\x12\x06zproto*\xc9\x01\n\x11LoginPlatFormType\x12\x11\n\rInnerPlatForm\x10\x00\x12\x13\n\x0fTencentPlatForm\x10\x01\x12\x10\n\x0cIntlPlatForm\x10\x02\x12\x13\n\x0fHaoPlayPlatForm\x10\x03\x12\x0f\n\x0b\x41pjPlatForm\x10\x04\x12\x0e\n\nXdPlatForm\x10\x05\x12\x19\n\x15SoutheastAsiaPlatForm\x10\x06\x12\x15\n\x10LoginPlatFormMax\x10\xe7\x07\x12\x12\n\rAiBotPlatForm\x10\x8fNb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'enum_login_plat_form_type_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGINPLATFORMTYPE']._serialized_start=44
  _globals['_LOGINPLATFORMTYPE']._serialized_end=245
# @@protoc_insertion_point(module_scope)
