# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: enum_e_entity_status_transition_type.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'enum_e_entity_status_transition_type.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*enum_e_entity_status_transition_type.proto\x12\x06zproto*\xde\x01\n\x1b\x45\x45ntityStatusTransitionType\x12\'\n#EEntityStatusTransitionType_Default\x10\x00\x12/\n+EEntityStatusTransitionType_GlobalCondition\x10\x01\x12\x30\n,EEntityStatusTransitionType_InteractionTimes\x10\x02\x12\x33\n/EEntityStatusTransitionType_InteractionTemplate\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'enum_e_entity_status_transition_type_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EENTITYSTATUSTRANSITIONTYPE']._serialized_start=55
  _globals['_EENTITYSTATUSTRANSITIONTYPE']._serialized_end=277
# @@protoc_insertion_point(module_scope)
