# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: enum_e_team_error_type.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'enum_e_team_error_type.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x65num_e_team_error_type.proto\x12\x06zproto*\xc4\x04\n\x0e\x45TeamErrorType\x12\x11\n\rReqCreateTeam\x10\x00\x12\x18\n\x14ReqSetTeamTargetInfo\x10\x01\x12\x13\n\x0fReqInviteToTeam\x10\x02\x12\x18\n\x14ReqReplyBeInvitation\x10\x03\x12\x0f\n\x0bReqQuitTeam\x10\x04\x12\x14\n\x10ReqApplyBeLeader\x10\x05\x12\x15\n\x11ReqTransferLeader\x10\x06\x12\x1d\n\x19ReqAcceptTransferBeLeader\x10\x07\x12\x18\n\x14ReqRefuseLeaderApply\x10\x08\x12\x0e\n\nReqTickOut\x10\t\x12\x12\n\x0eReqGetTeamList\x10\n\x12\x16\n\x12ReqGetNearTeamList\x10\x0b\x12\x14\n\x10ReqApplyJoinTeam\x10\x0c\x12\x14\n\x10ReqDealApplyJoin\x10\r\x12\x17\n\x13ReqDenyAllApplyJoin\x10\x0e\x12\x15\n\x11ReqCharBeginMatch\x10\x0f\x12\x16\n\x12ReqCharCancelMatch\x10\x10\x12\x17\n\x13ReqLeaderBeginMatch\x10\x11\x12\x18\n\x14ReqLeaderCancelMatch\x10\x12\x12\x19\n\x15ReqLeaderGetApplyList\x10\x13\x12\x18\n\x14ReqTeamStartActivity\x10\x14\x12\x19\n\x15ReqTeamCancelActivity\x10\x15\x12\x18\n\x14ReqReplyJoinActivity\x10\x16\x12\x12\n\x0eReqSetShowHall\x10\x17\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'enum_e_team_error_type_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ETEAMERRORTYPE']._serialized_start=41
  _globals['_ETEAMERRORTYPE']._serialized_end=621
# @@protoc_insertion_point(module_scope)
