# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: EquipTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'EquipTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import table_basic_pb2 as table__basic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x45quipTable.proto\x12\x06\x62okura\x1a\x11table_basic.proto\"\xe3\x02\n\x0e\x45quipTableBase\x12\x0b\n\x02id\x18\xb7\x0b \x01(\x05\x12\x0e\n\x05model\x18\xa5\x03 \x01(\t\x12\x10\n\x07suit_id\x18\x81\x05 \x01(\x05\x12\x15\n\x0csuit_part_id\x18\x9b\x06 \x01(\x05\x12\x13\n\nequip_part\x18\xcc\r \x01(\x05\x12\x13\n\nequip_type\x18\xb2\x0f \x01(\x05\x12\x19\n\x10type_attr_lib_id\x18\xb7\x01 \x01(\x05\x12\x1c\n\x13style_effect_lib_id\x18\xbf\x02 \x01(\x05\x12\x16\n\x0emax_durability\x18) \x01(\x05\x12 \n\x17\x64urability_invalid_type\x18\xb2\t \x01(\x05\x12\x15\n\x0c\x66\x61shion_m_id\x18\x9b\x03 \x01(\x05\x12\x15\n\x0c\x66\x61shion_f_id\x18\xaf\x0c \x01(\x05\x12%\n\x10\x62onus_grow_times\x18\xf3\x0b \x01(\x0b\x32\n.int_table\x12\x19\n\x10\x62\x61sic_grow_range\x18\x9a\n \x01(\x05\"\x86\x01\n\rEquipTableMgr\x12/\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32 .bokura.EquipTableMgr.DatasEntry\x1a\x44\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.bokura.EquipTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'EquipTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EQUIPTABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_EQUIPTABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_EQUIPTABLEBASE']._serialized_start=48
  _globals['_EQUIPTABLEBASE']._serialized_end=403
  _globals['_EQUIPTABLEMGR']._serialized_start=406
  _globals['_EQUIPTABLEMGR']._serialized_end=540
  _globals['_EQUIPTABLEMGR_DATASENTRY']._serialized_start=472
  _globals['_EQUIPTABLEMGR_DATASENTRY']._serialized_end=540
# @@protoc_insertion_point(module_scope)
