# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: FacialExpressionTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'FacialExpressionTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x46\x61\x63ialExpressionTable.proto\x12\x06\x62okura\"^\n\x19\x46\x61\x63ialExpressionTableBase\x12\x0b\n\x02id\x18\xb7\x0b \x01(\x05\x12\x14\n\x0b\x66\x61\x63ial_name\x18\xa1\x0c \x01(\t\x12\x0f\n\x06remark\x18\xef\n \x01(\t\x12\r\n\x04path\x18\xac\x01 \x01(\t\"\xa7\x01\n\x18\x46\x61\x63ialExpressionTableMgr\x12:\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32+.bokura.FacialExpressionTableMgr.DatasEntry\x1aO\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x30\n\x05value\x18\x02 \x01(\x0b\x32!.bokura.FacialExpressionTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FacialExpressionTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FACIALEXPRESSIONTABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_FACIALEXPRESSIONTABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_FACIALEXPRESSIONTABLEBASE']._serialized_start=39
  _globals['_FACIALEXPRESSIONTABLEBASE']._serialized_end=133
  _globals['_FACIALEXPRESSIONTABLEMGR']._serialized_start=136
  _globals['_FACIALEXPRESSIONTABLEMGR']._serialized_end=303
  _globals['_FACIALEXPRESSIONTABLEMGR_DATASENTRY']._serialized_start=224
  _globals['_FACIALEXPRESSIONTABLEMGR_DATASENTRY']._serialized_end=303
# @@protoc_insertion_point(module_scope)
