# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: FieldTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'FieldTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import table_basic_pb2 as table__basic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x46ieldTable.proto\x12\x06\x62okura\x1a\x11table_basic.proto\"\xf5\x01\n\x0e\x46ieldTableBase\x12\x0b\n\x02id\x18\xb7\x0b \x01(\x05\x12\r\n\x04name\x18\xb7\x03 \x01(\t\x12\x11\n\x08skill_id\x18\xbf\x08 \x01(\x03\x12\x17\n\x04size\x18\xef\x08 \x01(\x0b\x32\x08.vector2\x12\x11\n\x08model_id\x18\xab\x04 \x01(\x05\x12\x11\n\x08min_body\x18\x9d\x02 \x01(\x05\x12\x15\n\x0c\x61ttribute_id\x18\xa1\x0e \x01(\x05\x12\x15\n\rbe_hit_effect\x18\x08 \x01(\t\x12\x15\n\x0c\x62irth_effect\x18\xf0\t \x01(\t\x12\x15\n\x0c\x64\x65\x61th_effect\x18\xdf\x0e \x01(\t\x12\x19\n\x04tags\x18\xe8\x01 \x01(\x0b\x32\n.int_array\"\x86\x01\n\rFieldTableMgr\x12/\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32 .bokura.FieldTableMgr.DatasEntry\x1a\x44\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.bokura.FieldTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FieldTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FIELDTABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_FIELDTABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_FIELDTABLEBASE']._serialized_start=48
  _globals['_FIELDTABLEBASE']._serialized_end=293
  _globals['_FIELDTABLEMGR']._serialized_start=296
  _globals['_FIELDTABLEMGR']._serialized_end=430
  _globals['_FIELDTABLEMGR_DATASENTRY']._serialized_start=362
  _globals['_FIELDTABLEMGR_DATASENTRY']._serialized_end=430
# @@protoc_insertion_point(module_scope)
