# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: GlobalTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'GlobalTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import table_basic_pb2 as table__basic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11GlobalTable.proto\x12\x06\x62okura\x1a\x11table_basic.proto\"I\n\x0fGlobalTableBase\x12\x0e\n\x05index\x18\xf8\n \x01(\x05\x12\x0b\n\x02id\x18\xb7\x0b \x01(\t\x12\x19\n\x05value\x18\xe8\x04 \x01(\x0b\x32\t.mlstring\"\x89\x01\n\x0eGlobalTableMgr\x12\x30\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32!.bokura.GlobalTableMgr.DatasEntry\x1a\x45\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.bokura.GlobalTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GlobalTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GLOBALTABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_GLOBALTABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_GLOBALTABLEBASE']._serialized_start=48
  _globals['_GLOBALTABLEBASE']._serialized_end=121
  _globals['_GLOBALTABLEMGR']._serialized_start=124
  _globals['_GLOBALTABLEMGR']._serialized_end=261
  _globals['_GLOBALTABLEMGR_DATASENTRY']._serialized_start=192
  _globals['_GLOBALTABLEMGR_DATASENTRY']._serialized_end=261
# @@protoc_insertion_point(module_scope)
