# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: InferenceStepTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'InferenceStepTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import table_basic_pb2 as table__basic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18InferenceStepTable.proto\x12\x06\x62okura\x1a\x11table_basic.proto\"\xf8\x01\n\x16InferenceStepTableBase\x12\x0b\n\x02id\x18\xb7\x0b \x01(\x05\x12\x1c\n\x08question\x18\xa9\r \x01(\x0b\x32\t.mlstring\x12\x1b\n\x06\x61nswer\x18\xb7\x02 \x01(\x0b\x32\n.int_array\x12#\n\x0fquestion_bubble\x18\xb1\x02 \x01(\x0b\x32\t.mlstring\x12\x1f\n\x16question_bubble_action\x18\xd7\x0b \x01(\x05\x12&\n\x0cwrong_bubble\x18\x80\x04 \x01(\x0b\x32\x0f.mlstring_array\x12(\n\x13wrong_bubble_action\x18\xea\r \x01(\x0b\x32\n.int_array\"\x9e\x01\n\x15InferenceStepTableMgr\x12\x37\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32(.bokura.InferenceStepTableMgr.DatasEntry\x1aL\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12-\n\x05value\x18\x02 \x01(\x0b\x32\x1e.bokura.InferenceStepTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'InferenceStepTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INFERENCESTEPTABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_INFERENCESTEPTABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_INFERENCESTEPTABLEBASE']._serialized_start=56
  _globals['_INFERENCESTEPTABLEBASE']._serialized_end=304
  _globals['_INFERENCESTEPTABLEMGR']._serialized_start=307
  _globals['_INFERENCESTEPTABLEMGR']._serialized_end=465
  _globals['_INFERENCESTEPTABLEMGR_DATASENTRY']._serialized_start=389
  _globals['_INFERENCESTEPTABLEMGR_DATASENTRY']._serialized_end=465
# @@protoc_insertion_point(module_scope)
