# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: InvestigationStepTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'InvestigationStepTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import table_basic_pb2 as table__basic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cInvestigationStepTable.proto\x12\x06\x62okura\x1a\x11table_basic.proto\"\xb3\x03\n\x1aInvestigationStepTableBase\x12\x0b\n\x02id\x18\xb7\x0b \x01(\x05\x12\x19\n\x04\x63lue\x18\xfb\x01 \x01(\x0b\x32\n.int_array\x12#\n\x0einference_step\x18\xcd\x0f \x01(\x0b\x32\n.int_array\x12\x1e\n\nconclusion\x18\xef\x06 \x01(\x0b\x32\t.mlstring\x12#\n\x0f\x63onclusion_tips\x18\x9f\x02 \x01(\x0b\x32\t.mlstring\x12%\n\x11\x63onclusion_bubble\x18\xb9\x0f \x01(\x0b\x32\t.mlstring\x12\x1a\n\x11\x63onclusion_action\x18\xf4\x03 \x01(\x05\x12\'\n\riocked_bubble\x18\xfc\x01 \x01(\x0b\x32\x0f.mlstring_array\x12)\n\x14iocked_bubble_action\x18\xfa\x03 \x01(\x0b\x32\n.int_array\x12\'\n\rreview_bubble\x18\xec\x02 \x01(\x0b\x32\x0f.mlstring_array\x12)\n\x14review_bubble_action\x18\x9b\x08 \x01(\x0b\x32\n.int_array\x12\x18\n\x0fquick_reasoning\x18\xfa\x07 \x01(\x08\"\xaa\x01\n\x19InvestigationStepTableMgr\x12;\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32,.bokura.InvestigationStepTableMgr.DatasEntry\x1aP\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x31\n\x05value\x18\x02 \x01(\x0b\x32\".bokura.InvestigationStepTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'InvestigationStepTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INVESTIGATIONSTEPTABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_INVESTIGATIONSTEPTABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_INVESTIGATIONSTEPTABLEBASE']._serialized_start=60
  _globals['_INVESTIGATIONSTEPTABLEBASE']._serialized_end=495
  _globals['_INVESTIGATIONSTEPTABLEMGR']._serialized_start=498
  _globals['_INVESTIGATIONSTEPTABLEMGR']._serialized_end=668
  _globals['_INVESTIGATIONSTEPTABLEMGR_DATASENTRY']._serialized_start=588
  _globals['_INVESTIGATIONSTEPTABLEMGR_DATASENTRY']._serialized_end=668
# @@protoc_insertion_point(module_scope)
