# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: InvestigationsTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'InvestigationsTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import table_basic_pb2 as table__basic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19InvestigationsTable.proto\x12\x06\x62okura\x1a\x11table_basic.proto\"\xbc\x02\n\x17InvestigationsTableBase\x12\x0b\n\x02id\x18\xb7\x0b \x01(\x05\x12\'\n\x13investigation_theme\x18\x8a\x07 \x01(\x0b\x32\t.mlstring\x12%\n\x10unlock_condition\x18\xf6\x07 \x01(\x0b\x32\n.int_table\x12\'\n\x12investigation_step\x18\xe7\n \x01(\x0b\x32\n.int_array\x12*\n\x15\x63ompletion_conditions\x18\xb2\x01 \x01(\x0b\x32\n.int_table\x12&\n\x12theme_introduction\x18\x8d\r \x01(\x0b\x32\t.mlstring\x12\x1f\n\x0biocked_tips\x18\xc0\r \x01(\x0b\x32\t.mlstring\x12\x12\n\ttheme_pic\x18\x97\n \x01(\t\x12\x12\n\tguarantee\x18\x83\t \x01(\x05\"\xa1\x01\n\x16InvestigationsTableMgr\x12\x38\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32).bokura.InvestigationsTableMgr.DatasEntry\x1aM\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12.\n\x05value\x18\x02 \x01(\x0b\x32\x1f.bokura.InvestigationsTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'InvestigationsTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INVESTIGATIONSTABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_INVESTIGATIONSTABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_INVESTIGATIONSTABLEBASE']._serialized_start=57
  _globals['_INVESTIGATIONSTABLEBASE']._serialized_end=373
  _globals['_INVESTIGATIONSTABLEMGR']._serialized_start=376
  _globals['_INVESTIGATIONSTABLEMGR']._serialized_end=537
  _globals['_INVESTIGATIONSTABLEMGR_DATASENTRY']._serialized_start=460
  _globals['_INVESTIGATIONSTABLEMGR_DATASENTRY']._serialized_end=537
# @@protoc_insertion_point(module_scope)
