# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: InvestigationClueTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'InvestigationClueTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import table_basic_pb2 as table__basic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cInvestigationClueTable.proto\x12\x06\x62okura\x1a\x11table_basic.proto\"\xc9\x02\n\x1aInvestigationClueTableBase\x12\x0b\n\x02id\x18\xb7\x0b \x01(\x05\x12\r\n\x04sort\x18\xb6\x06 \x01(\x05\x12%\n\x10unlock_condition\x18\xf6\x07 \x01(\x0b\x32\n.int_table\x12\x18\n\x04\x63lue\x18\xfb\x01 \x01(\x0b\x32\t.mlstring\x12 \n\x06\x61nswer\x18\xb7\x02 \x01(\x0b\x32\x0f.mlstring_array\x12\x18\n\x04tips\x18\xa0\t \x01(\x0b\x32\t.mlstring\x12$\n\ntap_bubble\x18\x91\r \x01(\x0b\x32\x0f.mlstring_array\x12&\n\x11tap_bubble_action\x18\xb9\x0e \x01(\x0b\x32\n.int_array\x12#\n\x0funlocked_bubble\x18\x83\x0c \x01(\x0b\x32\t.mlstring\x12\x1f\n\x16unlocked_bubble_action\x18\x82\x01 \x01(\x05\"\xaa\x01\n\x19InvestigationClueTableMgr\x12;\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32,.bokura.InvestigationClueTableMgr.DatasEntry\x1aP\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x31\n\x05value\x18\x02 \x01(\x0b\x32\".bokura.InvestigationClueTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'InvestigationClueTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INVESTIGATIONCLUETABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_INVESTIGATIONCLUETABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_INVESTIGATIONCLUETABLEBASE']._serialized_start=60
  _globals['_INVESTIGATIONCLUETABLEBASE']._serialized_end=389
  _globals['_INVESTIGATIONCLUETABLEMGR']._serialized_start=392
  _globals['_INVESTIGATIONCLUETABLEMGR']._serialized_end=562
  _globals['_INVESTIGATIONCLUETABLEMGR_DATASENTRY']._serialized_start=482
  _globals['_INVESTIGATIONCLUETABLEMGR_DATASENTRY']._serialized_end=562
# @@protoc_insertion_point(module_scope)
