# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ItemTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ItemTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import table_basic_pb2 as table__basic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fItemTable.proto\x12\x06\x62okura\x1a\x11table_basic.proto\"\xf8\x02\n\rItemTableBase\x12\x0b\n\x02id\x18\xb7\x0b \x01(\x05\x12\x18\n\x04name\x18\xb7\x03 \x01(\x0b\x32\t.mlstring\x12\r\n\x04icon\x18\x81\t \x01(\t\x12\r\n\x04type\x18\xa1\x05 \x01(\x05\x12\x11\n\x08group_id\x18\xc4\x01 \x01(\x05\x12\x10\n\x07quality\x18\xa9\x0f \x01(\x05\x12\x10\n\x07sort_id\x18\xf8\x03 \x01(\x05\x12\x1e\n\x0b\x64\x65scription\x18K \x01(\x0b\x32\t.mlstring\x12\x12\n\tsex_limit\x18\x9a\x06 \x01(\x05\x12\x10\n\x07overlap\x18\xa3\x02 \x01(\x05\x12\x12\n\ttime_type\x18\xa5\n \x01(\x05\x12\x13\n\ntime_limit\x18\xba\r \x01(\t\x12\x13\n\ndrop_model\x18\xdc\x04 \x01(\x05\x12\x17\n\x0e\x63orrelation_id\x18\x8d\x07 \x01(\x05\x12\x1b\n\x12is_special_display\x18\xa4\x08 \x01(\x08\x12\x1d\n\x14special_display_type\x18\xb7\t \x01(\x05\x12\x12\n\tquick_use\x18\xd5\x08 \x01(\x05\"\x83\x01\n\x0cItemTableMgr\x12.\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32\x1f.bokura.ItemTableMgr.DatasEntry\x1a\x43\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12$\n\x05value\x18\x02 \x01(\x0b\x32\x15.bokura.ItemTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ItemTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ITEMTABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_ITEMTABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_ITEMTABLEBASE']._serialized_start=47
  _globals['_ITEMTABLEBASE']._serialized_end=423
  _globals['_ITEMTABLEMGR']._serialized_start=426
  _globals['_ITEMTABLEMGR']._serialized_end=557
  _globals['_ITEMTABLEMGR_DATASENTRY']._serialized_start=490
  _globals['_ITEMTABLEMGR_DATASENTRY']._serialized_end=557
# @@protoc_insertion_point(module_scope)
