# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ItemFunctionTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ItemFunctionTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import table_basic_pb2 as table__basic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17ItemFunctionTable.proto\x12\x06\x62okura\x1a\x11table_basic.proto\"\xe0\x02\n\x15ItemFunctionTableBase\x12\x0b\n\x02id\x18\xb7\x0b \x01(\x05\x12\r\n\x04name\x18\xb7\x03 \x01(\t\x12\r\n\x04type\x18\xa1\x05 \x01(\x05\x12!\n\tparameter\x18\xfd\x06 \x01(\x0b\x32\r.string_array\x12\x1a\n\x06\x62utton\x18\x87\x0f \x01(\x0b\x32\t.mlstring\x12!\n\tuse_limit\x18\x89\x02 \x01(\x0b\x32\r.string_array\x12\x12\n\treconfirm\x18\xd3\x08 \x01(\x05\x12\x0f\n\x06target\x18\xbc\n \x01(\x05\x12\x13\n\nauto_apply\x18\xff\r \x01(\x05\x12\x0f\n\x06use_cd\x18\x82\n \x01(\x05\x12\x1e\n\tpublic_cd\x18\xd1\t \x01(\x0b\x32\n.int_array\x12\x0f\n\x06\x65\x66\x66\x65\x63t\x18\xda\x04 \x01(\t\x12\x15\n\x0csound_effect\x18\xf9\x01 \x01(\t\x12\x12\n\tcan_quick\x18\xe9\x0f \x01(\x05\x12\x13\n\nitem_batch\x18\xfa\x0b \x01(\x05\"\x9b\x01\n\x14ItemFunctionTableMgr\x12\x36\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32\'.bokura.ItemFunctionTableMgr.DatasEntry\x1aK\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12,\n\x05value\x18\x02 \x01(\x0b\x32\x1d.bokura.ItemFunctionTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ItemFunctionTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ITEMFUNCTIONTABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_ITEMFUNCTIONTABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_ITEMFUNCTIONTABLEBASE']._serialized_start=55
  _globals['_ITEMFUNCTIONTABLEBASE']._serialized_end=407
  _globals['_ITEMFUNCTIONTABLEMGR']._serialized_start=410
  _globals['_ITEMFUNCTIONTABLEMGR']._serialized_end=565
  _globals['_ITEMFUNCTIONTABLEMGR_DATASENTRY']._serialized_start=490
  _globals['_ITEMFUNCTIONTABLEMGR_DATASENTRY']._serialized_end=565
# @@protoc_insertion_point(module_scope)
