# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: LocalShowRule.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'LocalShowRule.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13LocalShowRule.proto\x12\x06\x62okura\"\x92\x01\n\x11LocalShowRuleBase\x12\x0b\n\x02id\x18\xb7\x0b \x01(\x05\x12\x12\n\tlang_area\x18\xff\x02 \x01(\t\x12\x0c\n\x03ymd\x18\xa5\n \x01(\t\x12\x13\n\nymd_to_ymd\x18\xa9\x06 \x01(\t\x12\x0b\n\x02md\x18\xfd\x02 \x01(\t\x12\x11\n\x08md_to_md\x18\x82\x0b \x01(\t\x12\x0c\n\x03hms\x18\xda\x04 \x01(\t\x12\x0b\n\x02hm\x18\xb6\x02 \x01(\t\"\x8f\x01\n\x10LocalShowRuleMgr\x12\x32\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32#.bokura.LocalShowRuleMgr.DatasEntry\x1aG\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12(\n\x05value\x18\x02 \x01(\x0b\x32\x19.bokura.LocalShowRuleBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'LocalShowRule_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOCALSHOWRULEMGR_DATASENTRY']._loaded_options = None
  _globals['_LOCALSHOWRULEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_LOCALSHOWRULEBASE']._serialized_start=32
  _globals['_LOCALSHOWRULEBASE']._serialized_end=178
  _globals['_LOCALSHOWRULEMGR']._serialized_start=181
  _globals['_LOCALSHOWRULEMGR']._serialized_end=324
  _globals['_LOCALSHOWRULEMGR_DATASENTRY']._serialized_start=253
  _globals['_LOCALSHOWRULEMGR_DATASENTRY']._serialized_end=324
# @@protoc_insertion_point(module_scope)
