# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: MallTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'MallTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import table_basic_pb2 as table__basic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fMallTable.proto\x12\x06\x62okura\x1a\x11table_basic.proto\"\x94\x03\n\rMallTableBase\x12\x0b\n\x02id\x18\xb7\x0b \x01(\x05\x12\x14\n\x0b\x66unction_id\x18\x95\x01 \x01(\x05\x12\x18\n\x04name\x18\xb7\x03 \x01(\x0b\x32\t.mlstring\x12\x14\n\x0bname_remark\x18\xff\x0b \x01(\t\x12\x18\n\x0fhas_father_type\x18\xd0\n \x01(\x05\x12\x12\n\tmall_type\x18\x98\r \x01(\x05\x12*\n\x15refresh_interval_type\x18\xc4\x0c \x01(\x0b\x32\n.int_table\x12\x1e\n\tweight_id\x18\xd7\x0f \x01(\x0b\x32\n.int_table\x12\x11\n\x08timer_id\x18\xbe\x01 \x01(\x05\x12\r\n\x04sort\x18\xeb\x0c \x01(\x05\x12\x18\n\x0fshow_count_down\x18\xa8\t \x01(\x05\x12\x1c\n\x13mall_manual_refresh\x18\xbc\n \x01(\x05\x12&\n\x11refresh_cost_item\x18\xe5\x0c \x01(\x0b\x32\n.int_table\x12\r\n\x04icon\x18\x81\t \x01(\t\x12%\n\x10\x63urrency_display\x18\xfe\x07 \x01(\x0b\x32\n.int_array\"\x83\x01\n\x0cMallTableMgr\x12.\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32\x1f.bokura.MallTableMgr.DatasEntry\x1a\x43\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12$\n\x05value\x18\x02 \x01(\x0b\x32\x15.bokura.MallTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MallTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MALLTABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_MALLTABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_MALLTABLEBASE']._serialized_start=47
  _globals['_MALLTABLEBASE']._serialized_end=451
  _globals['_MALLTABLEMGR']._serialized_start=454
  _globals['_MALLTABLEMGR']._serialized_end=585
  _globals['_MALLTABLEMGR_DATASENTRY']._serialized_start=518
  _globals['_MALLTABLEMGR_DATASENTRY']._serialized_end=585
# @@protoc_insertion_point(module_scope)
