# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: MapBookTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'MapBookTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import table_basic_pb2 as table__basic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12MapBookTable.proto\x12\x06\x62okura\x1a\x11table_basic.proto\"\x88\x01\n\x10MapBookTableBase\x12\x0b\n\x02id\x18\xb7\x0b \x01(\x05\x12\x11\n\x08scene_id\x18\xe2\x0b \x01(\x05\x12\x10\n\x07sort_id\x18\xb2\x0c \x01(\x05\x12\x0e\n\x05model\x18\xa5\x03 \x01(\t\x12\x11\n\x08\x61ward_id\x18\xad\t \x01(\x05\x12\x1f\n\nsticker_id\x18\xfb\t \x01(\x0b\x32\n.int_array\"\x8c\x01\n\x0fMapBookTableMgr\x12\x31\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32\".bokura.MapBookTableMgr.DatasEntry\x1a\x46\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\'\n\x05value\x18\x02 \x01(\x0b\x32\x18.bokura.MapBookTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MapBookTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MAPBOOKTABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_MAPBOOKTABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_MAPBOOKTABLEBASE']._serialized_start=50
  _globals['_MAPBOOKTABLEBASE']._serialized_end=186
  _globals['_MAPBOOKTABLEMGR']._serialized_start=189
  _globals['_MAPBOOKTABLEMGR']._serialized_end=329
  _globals['_MAPBOOKTABLEMGR_DATASENTRY']._serialized_start=259
  _globals['_MAPBOOKTABLEMGR_DATASENTRY']._serialized_end=329
# @@protoc_insertion_point(module_scope)
