# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: MessageTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'MessageTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import table_basic_pb2 as table__basic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12MessageTable.proto\x12\x06\x62okura\x1a\x11table_basic.proto\"\xc7\x02\n\x10MessageTableBase\x12\x0b\n\x02id\x18\xb7\x0b \x01(\x05\x12\x1b\n\x07\x63ontent\x18\x8f\x06 \x01(\x0b\x32\t.mlstring\x12\r\n\x04type\x18\xa1\x05 \x01(\x05\x12\x16\n\rduration_time\x18\xc8\x04 \x01(\x02\x12\x1d\n\tchat_name\x18\xbd\n \x01(\x0b\x32\t.mlstring\x12\x0e\n\x05\x64\x65lay\x18\x8f\x03 \x01(\x02\x12 \n\x0brepeat_play\x18\x8d\x08 \x01(\x0b\x32\n.int_array\x12!\n\x0cshow_channel\x18\xeb\x04 \x01(\x0b\x32\n.int_array\x12\x14\n\x0b\x66ilter_rule\x18\x9f\x0c \x01(\x08\x12\x18\n\x0fis_show_in_chat\x18\xef\x08 \x01(\x08\x12\x1a\n\x11typewriter_effect\x18\x9b\x0b \x01(\x08\x12\x12\n\tinterrupt\x18\xe4\r \x01(\x05\x12\x0e\n\x05\x61udio\x18\xb2\x0f \x01(\t\"\x8c\x01\n\x0fMessageTableMgr\x12\x31\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32\".bokura.MessageTableMgr.DatasEntry\x1a\x46\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\'\n\x05value\x18\x02 \x01(\x0b\x32\x18.bokura.MessageTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MessageTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGETABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_MESSAGETABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_MESSAGETABLEBASE']._serialized_start=50
  _globals['_MESSAGETABLEBASE']._serialized_end=377
  _globals['_MESSAGETABLEMGR']._serialized_start=380
  _globals['_MESSAGETABLEMGR']._serialized_end=520
  _globals['_MESSAGETABLEMGR_DATASENTRY']._serialized_start=450
  _globals['_MESSAGETABLEMGR_DATASENTRY']._serialized_end=520
# @@protoc_insertion_point(module_scope)
