# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ModelWpNpcTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ModelWpNpcTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15ModelWpNpcTable.proto\x12\x06\x62okura\"\xf6\x02\n\x13ModelWpNpcTableBase\x12\x17\n\x0fmodel_prefab_id\x18\x05 \x01(\x05\x12\x1a\n\x11model_prefab_desc\x18\x80\t \x01(\t\x12\x0c\n\x03sex\x18\xa6\x08 \x01(\x05\x12\x11\n\x08skeleton\x18\xea\x08 \x01(\t\x12\x16\n\ranim_template\x18\xdc\t \x01(\t\x12\x13\n\nemo_prefix\x18\xd9\x06 \x01(\t\x12\r\n\x04head\x18\x98\x05 \x01(\t\x12\x1b\n\x12\x61nim_head_template\x18\x8b\x01 \x01(\t\x12\r\n\x04hair\x18\xbe\x04 \x01(\t\x12\x1b\n\x12\x61nim_hair_template\x18\x80\x01 \x01(\t\x12\x11\n\x08headwear\x18\xc5\x05 \x01(\t\x12\r\n\x04\x62\x61\x63k\x18\xfb\x01 \x01(\t\x12\x10\n\x07weaponl\x18\x9e\n \x01(\t\x12\x10\n\x07weaponr\x18\x9a\r \x01(\t\x12\r\n\x04tail\x18\x8c\n \x01(\t\x12\x18\n\x10weapon_idle_anim\x18\x66 \x01(\t\x12\x15\n\x0cpinch_config\x18\xc0\x06 \x01(\t\"\x95\x01\n\x12ModelWpNpcTableMgr\x12\x34\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32%.bokura.ModelWpNpcTableMgr.DatasEntry\x1aI\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12*\n\x05value\x18\x02 \x01(\x0b\x32\x1b.bokura.ModelWpNpcTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ModelWpNpcTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MODELWPNPCTABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_MODELWPNPCTABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_MODELWPNPCTABLEBASE']._serialized_start=34
  _globals['_MODELWPNPCTABLEBASE']._serialized_end=408
  _globals['_MODELWPNPCTABLEMGR']._serialized_start=411
  _globals['_MODELWPNPCTABLEMGR']._serialized_end=560
  _globals['_MODELWPNPCTABLEMGR_DATASENTRY']._serialized_start=487
  _globals['_MODELWPNPCTABLEMGR_DATASENTRY']._serialized_end=560
# @@protoc_insertion_point(module_scope)
