# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: MonsterExploreTargetTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'MonsterExploreTargetTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import table_basic_pb2 as table__basic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fMonsterExploreTargetTable.proto\x12\x06\x62okura\x1a\x11table_basic.proto\"\x99\x03\n\x1dMonsterExploreTargetTableBase\x12\x0b\n\x02id\x18\xb7\x0b \x01(\x05\x12\x14\n\x0btarget_type\x18\xe0\x05 \x01(\x05\x12\x0c\n\x03num\x18\xb3\x07 \x01(\x05\x12\x11\n\x08scene_id\x18\xe2\x0b \x01(\x05\x12\x1a\n\x05param\x18\xb7\t \x01(\x0b\x32\n.int_array\x12\x13\n\ntarget_pos\x18\xde\x08 \x01(\t\x12\x16\n\ris_team_share\x18\x85\x0f \x01(\x08\x12\x1e\n\ntarget_des\x18\xff\t \x01(\x0b\x32\t.mlstring\x12\x18\n\x10is_show_progress\x18\x38 \x01(\x08\x12%\n\x0bsp_variable\x18\x98\x02 \x01(\x0b\x32\x0f.mlstring_array\x12+\n\x11sp_variable_limit\x18\xbb\x02 \x01(\x0b\x32\x0f.mlstring_array\x12*\n\x10sp_variable_name\x18\xd6\x0f \x01(\x0b\x32\x0f.mlstring_array\x12\x31\n\x1cis_show_sp_variable_progress\x18\xa0\x06 \x01(\x0b\x32\n.int_array\"\xb3\x01\n\x1cMonsterExploreTargetTableMgr\x12>\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32/.bokura.MonsterExploreTargetTableMgr.DatasEntry\x1aS\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x34\n\x05value\x18\x02 \x01(\x0b\x32%.bokura.MonsterExploreTargetTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MonsterExploreTargetTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MONSTEREXPLORETARGETTABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_MONSTEREXPLORETARGETTABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_MONSTEREXPLORETARGETTABLEBASE']._serialized_start=63
  _globals['_MONSTEREXPLORETARGETTABLEBASE']._serialized_end=472
  _globals['_MONSTEREXPLORETARGETTABLEMGR']._serialized_start=475
  _globals['_MONSTEREXPLORETARGETTABLEMGR']._serialized_end=654
  _globals['_MONSTEREXPLORETARGETTABLEMGR_DATASENTRY']._serialized_start=571
  _globals['_MONSTEREXPLORETARGETTABLEMGR_DATASENTRY']._serialized_end=654
# @@protoc_insertion_point(module_scope)
