# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: NameCardTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'NameCardTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import table_basic_pb2 as table__basic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13NameCardTable.proto\x12\x06\x62okura\x1a\x11table_basic.proto\"\x8d\x01\n\x11NameCardTableBase\x12\x0b\n\x02id\x18\xb7\x0b \x01(\x05\x12\x18\n\x04name\x18\xb7\x03 \x01(\x0b\x32\t.mlstring\x12\x1e\n\nunlock_des\x18\xc7\x0f \x01(\x0b\x32\t.mlstring\x12\x0f\n\x06image1\x18\xaf\x0c \x01(\t\x12\x0f\n\x06image2\x18\xe0\x0f \x01(\t\x12\x0f\n\x06unlock\x18\x82\r \x01(\x05\"\x8f\x01\n\x10NameCardTableMgr\x12\x32\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32#.bokura.NameCardTableMgr.DatasEntry\x1aG\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12(\n\x05value\x18\x02 \x01(\x0b\x32\x19.bokura.NameCardTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'NameCardTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NAMECARDTABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_NAMECARDTABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_NAMECARDTABLEBASE']._serialized_start=51
  _globals['_NAMECARDTABLEBASE']._serialized_end=192
  _globals['_NAMECARDTABLEMGR']._serialized_start=195
  _globals['_NAMECARDTABLEMGR']._serialized_end=338
  _globals['_NAMECARDTABLEMGR_DATASENTRY']._serialized_start=267
  _globals['_NAMECARDTABLEMGR_DATASENTRY']._serialized_end=338
# @@protoc_insertion_point(module_scope)
