# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: NeighbouringSceneTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'NeighbouringSceneTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import table_basic_pb2 as table__basic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cNeighbouringSceneTable.proto\x12\x06\x62okura\x1a\x11table_basic.proto\"o\n\x1aNeighbouringSceneTableBase\x12\x0b\n\x02id\x18\xb7\x0b \x01(\x05\x12\'\n\x12neighbouring_scene\x18\xd6\x06 \x01(\x0b\x32\n.int_array\x12\x1b\n\x06portal\x18\xc2\t \x01(\x0b\x32\n.int_array\"\xaa\x01\n\x19NeighbouringSceneTableMgr\x12;\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32,.bokura.NeighbouringSceneTableMgr.DatasEntry\x1aP\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x31\n\x05value\x18\x02 \x01(\x0b\x32\".bokura.NeighbouringSceneTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'NeighbouringSceneTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NEIGHBOURINGSCENETABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_NEIGHBOURINGSCENETABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_NEIGHBOURINGSCENETABLEBASE']._serialized_start=59
  _globals['_NEIGHBOURINGSCENETABLEBASE']._serialized_end=170
  _globals['_NEIGHBOURINGSCENETABLEMGR']._serialized_start=173
  _globals['_NEIGHBOURINGSCENETABLEMGR']._serialized_end=343
  _globals['_NEIGHBOURINGSCENETABLEMGR_DATASENTRY']._serialized_start=263
  _globals['_NEIGHBOURINGSCENETABLEMGR_DATASENTRY']._serialized_end=343
# @@protoc_insertion_point(module_scope)
