# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: NormalHeroDungeonTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'NormalHeroDungeonTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import table_basic_pb2 as table__basic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cNormalHeroDungeonTable.proto\x12\x06\x62okura\x1a\x11table_basic.proto\"\x89\x02\n\x1aNormalHeroDungeonTableBase\x12\x13\n\ndungeon_id\x18\xaf\x0c \x01(\x05\x12\x19\n\x10season_open_time\x18\xc2\x07 \x01(\x05\x12\x13\n\naffix_pool\x18\xe6\x06 \x01(\x05\x12\x13\n\nbackground\x18\xd7\x02 \x01(\t\x12\x11\n\x08model_id\x18\xab\x04 \x01(\x05\x12\x12\n\teffect_id\x18\x93\x0c \x01(\x05\x12\x13\n\nbase_ratio\x18\xfc\x08 \x01(\x05\x12\x13\n\nlimit_time\x18\xdc\x02 \x01(\x05\x12\x1f\n\nscore_rank\x18\xe5\x05 \x01(\x0b\x32\n.int_table\x12\x1f\n\nkey_reward\x18\xff\r \x01(\x0b\x32\n.int_array\"\xaa\x01\n\x19NormalHeroDungeonTableMgr\x12;\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32,.bokura.NormalHeroDungeonTableMgr.DatasEntry\x1aP\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x31\n\x05value\x18\x02 \x01(\x0b\x32\".bokura.NormalHeroDungeonTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'NormalHeroDungeonTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NORMALHERODUNGEONTABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_NORMALHERODUNGEONTABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_NORMALHERODUNGEONTABLEBASE']._serialized_start=60
  _globals['_NORMALHERODUNGEONTABLEBASE']._serialized_end=325
  _globals['_NORMALHERODUNGEONTABLEMGR']._serialized_start=328
  _globals['_NORMALHERODUNGEONTABLEMGR']._serialized_end=498
  _globals['_NORMALHERODUNGEONTABLEMGR_DATASENTRY']._serialized_start=418
  _globals['_NORMALHERODUNGEONTABLEMGR_DATASENTRY']._serialized_end=498
# @@protoc_insertion_point(module_scope)
