# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: PresentationEPFlowTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'PresentationEPFlowTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import table_basic_pb2 as table__basic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dPresentationEPFlowTable.proto\x12\x06\x62okura\x1a\x11table_basic.proto\"\xf1\x02\n\x1bPresentationEPFlowTableBase\x12\x0b\n\x02id\x18\xb7\x0b \x01(\x05\x12\x11\n\x08res_path\x18\xa4\x04 \x01(\t\x12\x12\n\tflow_name\x18\xf3\x0b \x01(\t\x12\x11\n\tflow_type\x18\x10 \x01(\t\x12\x12\n\nget_option\x18? \x01(\x08\x12\x1b\n\x12is_save_play_state\x18\x85\x0c \x01(\x08\x12\x1d\n\x14\x63heck_play_key_index\x18\xb5\x04 \x01(\x05\x12\x18\n\x0f\x63heck_play_type\x18\xfe\x0e \x01(\x05\x12#\n\x1ais_default_camera_disabled\x18\xc8\x01 \x01(\x08\x12\x17\n\x0e\x63ontent_hiding\x18\x82\t \x01(\x05\x12&\n\x11ignore_hiding_npc\x18\xbb\x07 \x01(\x0b\x32\n.int_array\x12\x1a\n\x11is_model_dialogue\x18\xaa\r \x01(\x08\x12\x1f\n\nblack_mask\x18\x8f\x07 \x01(\x0b\x32\n.int_array\"\xad\x01\n\x1aPresentationEPFlowTableMgr\x12<\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32-.bokura.PresentationEPFlowTableMgr.DatasEntry\x1aQ\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x32\n\x05value\x18\x02 \x01(\x0b\x32#.bokura.PresentationEPFlowTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PresentationEPFlowTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRESENTATIONEPFLOWTABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_PRESENTATIONEPFLOWTABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_PRESENTATIONEPFLOWTABLEBASE']._serialized_start=61
  _globals['_PRESENTATIONEPFLOWTABLEBASE']._serialized_end=430
  _globals['_PRESENTATIONEPFLOWTABLEMGR']._serialized_start=433
  _globals['_PRESENTATIONEPFLOWTABLEMGR']._serialized_end=606
  _globals['_PRESENTATIONEPFLOWTABLEMGR_DATASENTRY']._serialized_start=525
  _globals['_PRESENTATIONEPFLOWTABLEMGR_DATASENTRY']._serialized_end=606
# @@protoc_insertion_point(module_scope)
