# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ProfessionEffectLibTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ProfessionEffectLibTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import table_basic_pb2 as table__basic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eProfessionEffectLibTable.proto\x12\x06\x62okura\x1a\x11table_basic.proto\"\xb5\x01\n\x1cProfessionEffectLibTableBase\x12\x0b\n\x02id\x18\xb7\x0b \x01(\x05\x12\x16\n\reffect_lib_id\x18\xa0\x05 \x01(\x05\x12\x14\n\x0b\x65\x66\x66\x65\x63t_type\x18\x8f\x04 \x01(\x05\x12\x15\n\reffect_config\x18n \x01(\x05\x12 \n\x0bvalue_range\x18\xd9\x0e \x01(\x0b\x32\n.int_table\x12!\n\x0crandom_range\x18\xd4\t \x01(\x0b\x32\n.int_table\"\xb0\x01\n\x1bProfessionEffectLibTableMgr\x12=\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32..bokura.ProfessionEffectLibTableMgr.DatasEntry\x1aR\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x33\n\x05value\x18\x02 \x01(\x0b\x32$.bokura.ProfessionEffectLibTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ProfessionEffectLibTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROFESSIONEFFECTLIBTABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_PROFESSIONEFFECTLIBTABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_PROFESSIONEFFECTLIBTABLEBASE']._serialized_start=62
  _globals['_PROFESSIONEFFECTLIBTABLEBASE']._serialized_end=243
  _globals['_PROFESSIONEFFECTLIBTABLEMGR']._serialized_start=246
  _globals['_PROFESSIONEFFECTLIBTABLEMGR']._serialized_end=422
  _globals['_PROFESSIONEFFECTLIBTABLEMGR_DATASENTRY']._serialized_start=340
  _globals['_PROFESSIONEFFECTLIBTABLEMGR_DATASENTRY']._serialized_end=422
# @@protoc_insertion_point(module_scope)
