# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ProfessionSignTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ProfessionSignTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import table_basic_pb2 as table__basic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19ProfessionSignTable.proto\x12\x06\x62okura\x1a\x11table_basic.proto\"\xe8\x01\n\x17ProfessionSignTableBase\x12\x0b\n\x02id\x18\xb7\x0b \x01(\x05\x12\x18\n\x04name\x18\xb7\x03 \x01(\x0b\x32\t.mlstring\x12\x1e\n\tsign_type\x18\xf5\x0c \x01(\x0b\x32\n.int_array\x12\r\n\x04\x63\x61rd\x18\xe3\x03 \x01(\t\x12\x12\n\titem_tips\x18\xeb\x03 \x01(\t\x12 \n\x0b\x65\x66\x66\x65\x63t_type\x18\x8f\x04 \x01(\x0b\x32\n.int_array\x12\x1e\n\teffect_id\x18\x93\x0c \x01(\x0b\x32\n.int_array\x12!\n\teffectkey\x18\xe1\r \x01(\x0b\x32\r.string_table\"\xa1\x01\n\x16ProfessionSignTableMgr\x12\x38\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32).bokura.ProfessionSignTableMgr.DatasEntry\x1aM\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12.\n\x05value\x18\x02 \x01(\x0b\x32\x1f.bokura.ProfessionSignTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ProfessionSignTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROFESSIONSIGNTABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_PROFESSIONSIGNTABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_PROFESSIONSIGNTABLEBASE']._serialized_start=57
  _globals['_PROFESSIONSIGNTABLEBASE']._serialized_end=289
  _globals['_PROFESSIONSIGNTABLEMGR']._serialized_start=292
  _globals['_PROFESSIONSIGNTABLEMGR']._serialized_end=453
  _globals['_PROFESSIONSIGNTABLEMGR_DATASENTRY']._serialized_start=376
  _globals['_PROFESSIONSIGNTABLEMGR_DATASENTRY']._serialized_end=453
# @@protoc_insertion_point(module_scope)
