# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: QteTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'QteTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import table_basic_pb2 as table__basic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eQteTable.proto\x12\x06\x62okura\x1a\x11table_basic.proto\"\xdf\x03\n\x0cQteTableBase\x12\x0b\n\x02id\x18\xb7\x0b \x01(\x05\x12\r\n\x04name\x18\xb0\x01 \x01(\t\x12\x11\n\x08qte_type\x18\xe1\x0b \x01(\x05\x12\x10\n\x07ui_type\x18\x92\x07 \x01(\x05\x12\x11\n\x08max_time\x18\x86\x0e \x01(\x02\x12$\n\x0ctime_quantum\x18\x84\x07 \x01(\x0b\x32\r.number_table\x12!\n\rtrigger_count\x18\x02 \x01(\x0b\x32\n.int_array\x12$\n\x0ctrigger_time\x18\xc3\x03 \x01(\x0b\x32\r.number_table\x12\x1f\n\nplay_skill\x18\x8d\x0c \x01(\x0b\x32\n.int_table\x12)\n\x14\x62uff_id_when_success\x18\xeb\t \x01(\x0b\x32\n.int_table\x12)\n\x14\x62uff_id_when_failure\x18\xbf\x07 \x01(\x0b\x32\n.int_array\x12\x1a\n\x11qte_show_skill_id\x18\xfb\n \x01(\x05\x12$\n\x0c\x65vent_params\x18\x95\x0b \x01(\x0b\x32\r.number_table\x12\x14\n\x0b\x66unction_id\x18\xb2\x06 \x01(\x05\x12\'\n\x12impact_function_id\x18\xb2\x0c \x01(\x0b\x32\n.int_array\x12\x14\n\x0bimpact_type\x18\xe5\x02 \x01(\x05\"\x80\x01\n\x0bQteTableMgr\x12-\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32\x1e.bokura.QteTableMgr.DatasEntry\x1a\x42\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.bokura.QteTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'QteTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QTETABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_QTETABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_QTETABLEBASE']._serialized_start=46
  _globals['_QTETABLEBASE']._serialized_end=525
  _globals['_QTETABLEMGR']._serialized_start=528
  _globals['_QTETABLEMGR']._serialized_end=656
  _globals['_QTETABLEMGR_DATASENTRY']._serialized_start=590
  _globals['_QTETABLEMGR_DATASENTRY']._serialized_end=656
# @@protoc_insertion_point(module_scope)
