# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ResolveTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ResolveTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import table_basic_pb2 as table__basic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12ResolveTable.proto\x12\x06\x62okura\x1a\x11table_basic.proto\"\x8a\x01\n\x10ResolveTableBase\x12\x0b\n\x02id\x18\xb7\x0b \x01(\x05\x12\x10\n\x07item_id\x18\xe1\x04 \x01(\x05\x12\x12\n\titem_name\x18\xc5\x0b \x01(\t\x12\x1d\n\x08get_item\x18\xdb\x06 \x01(\x0b\x32\n.int_array\x12\x14\n\x0b\x66unction_id\x18\x95\x01 \x01(\x05\x12\x0e\n\x05limit\x18\x80\x05 \x01(\x05\"\x8c\x01\n\x0fResolveTableMgr\x12\x31\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32\".bokura.ResolveTableMgr.DatasEntry\x1a\x46\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\'\n\x05value\x18\x02 \x01(\x0b\x32\x18.bokura.ResolveTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ResolveTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESOLVETABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_RESOLVETABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_RESOLVETABLEBASE']._serialized_start=50
  _globals['_RESOLVETABLEBASE']._serialized_end=188
  _globals['_RESOLVETABLEMGR']._serialized_start=191
  _globals['_RESOLVETABLEMGR']._serialized_end=331
  _globals['_RESOLVETABLEMGR_DATASENTRY']._serialized_start=261
  _globals['_RESOLVETABLEMGR_DATASENTRY']._serialized_end=331
# @@protoc_insertion_point(module_scope)
