# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ReviveTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ReviveTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import table_basic_pb2 as table__basic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11ReviveTable.proto\x12\x06\x62okura\x1a\x11table_basic.proto\"\xcf\x01\n\x0fReviveTableBase\x12\x0b\n\x02id\x18\xb7\x0b \x01(\x05\x12\x18\n\x04name\x18\xb7\x03 \x01(\x0b\x32\t.mlstring\x12\r\n\x04type\x18\xa1\x05 \x01(\x05\x12\x1c\n\x07\x63onsume\x18\xae\x0e \x01(\x0b\x32\n.int_array\x12\x13\n\ncount_down\x18\xae\x1e \x01(\x05\x12#\n\x0e\x62\x65\x66ore_buff_id\x18\xd9\r \x01(\x0b\x32\n.int_array\x12\x11\n\twait_time\x18j \x01(\x05\x12\x1b\n\x12is_boss_can_revive\x18\xac\x06 \x01(\x05\"\x89\x01\n\x0eReviveTableMgr\x12\x30\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32!.bokura.ReviveTableMgr.DatasEntry\x1a\x45\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.bokura.ReviveTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ReviveTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REVIVETABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_REVIVETABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_REVIVETABLEBASE']._serialized_start=49
  _globals['_REVIVETABLEBASE']._serialized_end=256
  _globals['_REVIVETABLEMGR']._serialized_start=259
  _globals['_REVIVETABLEMGR']._serialized_end=396
  _globals['_REVIVETABLEMGR_DATASENTRY']._serialized_start=327
  _globals['_REVIVETABLEMGR_DATASENTRY']._serialized_end=396
# @@protoc_insertion_point(module_scope)
