# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SceneObjectEntityGlobalTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'SceneObjectEntityGlobalTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import table_basic_pb2 as table__basic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"SceneObjectEntityGlobalTable.proto\x12\x06\x62okura\x1a\x11table_basic.proto\"\x8c\x01\n SceneObjectEntityGlobalTableBase\x12\r\n\x04u_id\x18\xec\x0f \x01(\x05\x12\x0b\n\x02id\x18\xb7\x0b \x01(\x05\x12 \n\x08position\x18\xae\x05 \x01(\x0b\x32\r.number_array\x12\x14\n\x0bsource_type\x18\xfc\x02 \x01(\x05\x12\x14\n\x0boption_data\x18\xd5\x06 \x01(\t\"\xbc\x01\n\x1fSceneObjectEntityGlobalTableMgr\x12\x41\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32\x32.bokura.SceneObjectEntityGlobalTableMgr.DatasEntry\x1aV\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x37\n\x05value\x18\x02 \x01(\x0b\x32(.bokura.SceneObjectEntityGlobalTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SceneObjectEntityGlobalTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCENEOBJECTENTITYGLOBALTABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_SCENEOBJECTENTITYGLOBALTABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_SCENEOBJECTENTITYGLOBALTABLEBASE']._serialized_start=66
  _globals['_SCENEOBJECTENTITYGLOBALTABLEBASE']._serialized_end=206
  _globals['_SCENEOBJECTENTITYGLOBALTABLEMGR']._serialized_start=209
  _globals['_SCENEOBJECTENTITYGLOBALTABLEMGR']._serialized_end=397
  _globals['_SCENEOBJECTENTITYGLOBALTABLEMGR_DATASENTRY']._serialized_start=311
  _globals['_SCENEOBJECTENTITYGLOBALTABLEMGR_DATASENTRY']._serialized_end=397
# @@protoc_insertion_point(module_scope)
