# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: serv_grpc_warehouse_ntf.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'serv_grpc_warehouse_ntf.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_notify_warehouse_grid_change_request_pb2 as stru__notify__warehouse__grid__change__request__pb2
import stru_notify_warehouse_invite_request_pb2 as stru__notify__warehouse__invite__request__pb2
import stru_notify_warehouse_new_joiner_request_pb2 as stru__notify__warehouse__new__joiner__request__pb2
import stru_notify_warehouse_passive_exist_request_pb2 as stru__notify__warehouse__passive__exist__request__pb2
import stru_notify_warehouse_refuse_to_join_request_pb2 as stru__notify__warehouse__refuse__to__join__request__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dserv_grpc_warehouse_ntf.proto\x12\x06zproto\x1a/stru_notify_warehouse_grid_change_request.proto\x1a*stru_notify_warehouse_invite_request.proto\x1a.stru_notify_warehouse_new_joiner_request.proto\x1a\x31stru_notify_warehouse_passive_exist_request.proto\x1a\x32stru_notify_warehouse_refuse_to_join_request.proto\"\xc8\x03\n\x10GrpcWarehouseNtf\x1aN\n\x15NotifyWarehouseInvite\x12\x35\n\x07request\x18\x01 \x01(\x0b\x32$.zproto.NotifyWarehouseInviteRequest\x1aV\n\x19NotifyWarehouseGridChange\x12\x39\n\x07request\x18\x01 \x01(\x0b\x32(.zproto.NotifyWarehouseGridChangeRequest\x1aZ\n\x1bNotifyWarehousePassiveExist\x12;\n\x07request\x18\x01 \x01(\x0b\x32*.zproto.NotifyWarehousePassiveExistRequest\x1aT\n\x18NotifyWarehouseNewJoiner\x12\x38\n\x07request\x18\x01 \x01(\x0b\x32\'.zproto.NotifyWarehouseNewJoinerRequest\x1aZ\n\x1bNotifyWarehouseRefuseToJoin\x12;\n\x07request\x18\x01 \x01(\x0b\x32*.zproto.NotifyWarehouseRefuseToJoinRequestb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'serv_grpc_warehouse_ntf_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GRPCWAREHOUSENTF']._serialized_start=286
  _globals['_GRPCWAREHOUSENTF']._serialized_end=742
  _globals['_GRPCWAREHOUSENTF_NOTIFYWAREHOUSEINVITE']._serialized_start=306
  _globals['_GRPCWAREHOUSENTF_NOTIFYWAREHOUSEINVITE']._serialized_end=384
  _globals['_GRPCWAREHOUSENTF_NOTIFYWAREHOUSEGRIDCHANGE']._serialized_start=386
  _globals['_GRPCWAREHOUSENTF_NOTIFYWAREHOUSEGRIDCHANGE']._serialized_end=472
  _globals['_GRPCWAREHOUSENTF_NOTIFYWAREHOUSEPASSIVEEXIST']._serialized_start=474
  _globals['_GRPCWAREHOUSENTF_NOTIFYWAREHOUSEPASSIVEEXIST']._serialized_end=564
  _globals['_GRPCWAREHOUSENTF_NOTIFYWAREHOUSENEWJOINER']._serialized_start=566
  _globals['_GRPCWAREHOUSENTF_NOTIFYWAREHOUSENEWJOINER']._serialized_end=650
  _globals['_GRPCWAREHOUSENTF_NOTIFYWAREHOUSEREFUSETOJOIN']._serialized_start=652
  _globals['_GRPCWAREHOUSENTF_NOTIFYWAREHOUSEREFUSETOJOIN']._serialized_end=742
# @@protoc_insertion_point(module_scope)
