# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: serv_match_ntf.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'serv_match_ntf.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_cancel_match_result_ntf_request_pb2 as stru__cancel__match__result__ntf__request__pb2
import stru_enter_match_result_ntf_request_pb2 as stru__enter__match__result__ntf__request__pb2
import stru_match_ready_status_ntf_request_pb2 as stru__match__ready__status__ntf__request__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14serv_match_ntf.proto\x12\x06zproto\x1a*stru_cancel_match_result_ntf_request.proto\x1a)stru_enter_match_result_ntf_request.proto\x1a)stru_match_ready_status_ntf_request.proto\"\xf6\x01\n\x08MatchNtf\x1aL\n\x13\x45nterMatchResultNtf\x12\x35\n\tv_request\x18\x01 \x01(\x0b\x32\".zproto.EnterMatchResultNtfRequest\x1aN\n\x14\x43\x61ncelMatchResultNtf\x12\x36\n\tv_request\x18\x01 \x01(\x0b\x32#.zproto.CancelMatchResultNtfRequest\x1aL\n\x13MatchReadyStatusNtf\x12\x35\n\tv_request\x18\x01 \x01(\x0b\x32\".zproto.MatchReadyStatusNtfRequestb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'serv_match_ntf_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MATCHNTF']._serialized_start=163
  _globals['_MATCHNTF']._serialized_end=409
  _globals['_MATCHNTF_ENTERMATCHRESULTNTF']._serialized_start=175
  _globals['_MATCHNTF_ENTERMATCHRESULTNTF']._serialized_end=251
  _globals['_MATCHNTF_CANCELMATCHRESULTNTF']._serialized_start=253
  _globals['_MATCHNTF_CANCELMATCHRESULTNTF']._serialized_end=331
  _globals['_MATCHNTF_MATCHREADYSTATUSNTF']._serialized_start=333
  _globals['_MATCHNTF_MATCHREADYSTATUSNTF']._serialized_end=409
# @@protoc_insertion_point(module_scope)
