# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SkillFightLevelTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'SkillFightLevelTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import table_basic_pb2 as table__basic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aSkillFightLevelTable.proto\x12\x06\x62okura\x1a\x11table_basic.proto\"\xa0\x02\n\x18SkillFightLevelTableBase\x12\x0b\n\x02id\x18\xb7\x0b \x01(\x05\x12\x11\n\x08skill_id\x18\xbf\x08 \x01(\x05\x12\x0e\n\x05level\x18\xe0\x08 \x01(\x05\x12\x18\n\x0fskill_effect_id\x18\x81\x07 \x01(\x05\x12\r\n\x04name\x18\xb7\x03 \x01(\t\x12\x1f\n\nskill_cost\x18\xeb\x04 \x01(\x0b\x32\n.int_table\x12$\n\x0fskill_res_check\x18\xe7\x03 \x01(\x0b\x32\n.int_table\x12\x16\n\rpve_cool_time\x18\xd1\x0f \x01(\x02\x12\'\n\x0f\x66loat_parameter\x18\xde\t \x01(\x0b\x32\r.string_table\x12#\n\x0eshow_parameter\x18\x95\x05 \x01(\x0b\x32\n.int_array\"\xa4\x01\n\x17SkillFightLevelTableMgr\x12\x39\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32*.bokura.SkillFightLevelTableMgr.DatasEntry\x1aN\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12/\n\x05value\x18\x02 \x01(\x0b\x32 .bokura.SkillFightLevelTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SkillFightLevelTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SKILLFIGHTLEVELTABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_SKILLFIGHTLEVELTABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_SKILLFIGHTLEVELTABLEBASE']._serialized_start=58
  _globals['_SKILLFIGHTLEVELTABLEBASE']._serialized_end=346
  _globals['_SKILLFIGHTLEVELTABLEMGR']._serialized_start=349
  _globals['_SKILLFIGHTLEVELTABLEMGR']._serialized_end=513
  _globals['_SKILLFIGHTLEVELTABLEMGR_DATASENTRY']._serialized_start=435
  _globals['_SKILLFIGHTLEVELTABLEMGR_DATASENTRY']._serialized_end=513
# @@protoc_insertion_point(module_scope)
