# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SkillEffectTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'SkillEffectTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import table_basic_pb2 as table__basic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16SkillEffectTable.proto\x12\x06\x62okura\x1a\x11table_basic.proto\"\xd0\x05\n\x14SkillEffectTableBase\x12\x0b\n\x02id\x18\xb7\x0b \x01(\x05\x12\x0e\n\x05level\x18\xe0\x08 \x01(\x05\x12\r\n\x04name\x18\xb7\x03 \x01(\t\x12\x11\n\x08skill_id\x18\xbf\x08 \x01(\x05\x12\x1e\n\x15skill_damage_distance\x18\x80\n \x01(\x02\x12$\n\x0c\x65\x66\x66\x65\x63t_range\x18\xd0\x0b \x01(\x0b\x32\r.number_array\x12.\n\x16\x61i_release_skill_range\x18\xf4\x0f \x01(\x0b\x32\r.number_array\x12.\n\x19\x63ool_time_on_battle_start\x18\xba\x08 \x01(\x0b\x32\n.int_array\x12\x1d\n\x14use_random_cool_time\x18\xaa\x05 \x01(\x05\x12,\n\x14random_pve_cool_time\x18\xfd\x0e \x01(\x0b\x32\r.number_array\x12\x19\n\x04tags\x18\xe8\x01 \x01(\x0b\x32\n.int_array\x12\x1d\n\tbuff_tags\x18j \x01(\x0b\x32\n.int_table\x12\x1d\n\x08hit_tags\x18\xee\x07 \x01(\x0b\x32\n.int_table\x12 \n\x0b\x65ntity_tags\x18\xab\x03 \x01(\x0b\x32\n.int_table\x12(\n\x0eskill_attr_des\x18\xec\t \x01(\x0b\x32\x0f.mlstring_table\x12\"\n\x19max_horizontal_motion_dis\x18\x8e\x01 \x01(\x02\x12\x11\n\x08st_range\x18\xdc\t \x01(\x02\x12\x10\n\x08st_angle\x18\x1d \x01(\x02\x12\x18\n\x0fst_sphere_range\x18\x99\x08 \x01(\x02\x12\x1b\n\x12is_in_battle_state\x18\x85\x07 \x01(\x08\x12\x1d\n\x14take_weapon_in_skill\x18\x9b\x04 \x01(\x08\x12\x1a\n\x11need_scale_camera\x18\xe1\x01 \x01(\x08\x12&\n\x11skill_learn_buffs\x18\xeb\x02 \x01(\x0b\x32\n.int_array\"\x98\x01\n\x13SkillEffectTableMgr\x12\x35\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32&.bokura.SkillEffectTableMgr.DatasEntry\x1aJ\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12+\n\x05value\x18\x02 \x01(\x0b\x32\x1c.bokura.SkillEffectTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SkillEffectTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SKILLEFFECTTABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_SKILLEFFECTTABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_SKILLEFFECTTABLEBASE']._serialized_start=54
  _globals['_SKILLEFFECTTABLEBASE']._serialized_end=774
  _globals['_SKILLEFFECTTABLEMGR']._serialized_start=777
  _globals['_SKILLEFFECTTABLEMGR']._serialized_end=929
  _globals['_SKILLEFFECTTABLEMGR_DATASENTRY']._serialized_start=855
  _globals['_SKILLEFFECTTABLEMGR_DATASENTRY']._serialized_end=929
# @@protoc_insertion_point(module_scope)
