# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StageBehaveCallEventTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'StageBehaveCallEventTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fStageBehaveCallEventTable.proto\x12\x06\x62okura\"\x84\x01\n\x1dStageBehaveCallEventTableBase\x12\x0b\n\x02id\x18\xb7\x0b \x01(\x05\x12\x13\n\nevent_type\x18\xcb\n \x01(\x05\x12\x17\n\x0elua_event_name\x18\x8d\x0b \x01(\t\x12\x19\n\x10\x63_sharp_event_id\x18\x8e\x0e \x01(\x05\x12\r\n\x04\x64\x65sc\x18\xa1\x0f \x01(\t\"\xb3\x01\n\x1cStageBehaveCallEventTableMgr\x12>\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32/.bokura.StageBehaveCallEventTableMgr.DatasEntry\x1aS\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x34\n\x05value\x18\x02 \x01(\x0b\x32%.bokura.StageBehaveCallEventTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'StageBehaveCallEventTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STAGEBEHAVECALLEVENTTABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_STAGEBEHAVECALLEVENTTABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_STAGEBEHAVECALLEVENTTABLEBASE']._serialized_start=44
  _globals['_STAGEBEHAVECALLEVENTTABLEBASE']._serialized_end=176
  _globals['_STAGEBEHAVECALLEVENTTABLEMGR']._serialized_start=179
  _globals['_STAGEBEHAVECALLEVENTTABLEMGR']._serialized_end=358
  _globals['_STAGEBEHAVECALLEVENTTABLEMGR_DATASENTRY']._serialized_start=275
  _globals['_STAGEBEHAVECALLEVENTTABLEMGR_DATASENTRY']._serialized_end=358
# @@protoc_insertion_point(module_scope)
