# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StiffTemplateTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'StiffTemplateTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18StiffTemplateTable.proto\x12\x06\x62okura\"\x9d\x02\n\x16StiffTemplateTableBase\x12\x0b\n\x02id\x18\xb7\x0b \x01(\x03\x12\x0c\n\x03\x64\x65s\x18\x8a\x02 \x01(\t\x12\x13\n\nbehit_type\x18\xd7\n \x01(\x05\x12\x19\n\x10hor_impact_force\x18\xa6\x06 \x01(\x02\x12\x19\n\x10ver_impact_force\x18\xc4\r \x01(\x02\x12\x16\n\rstiffing_time\x18\x90\x06 \x01(\x02\x12\x18\n\x0fstiff_hang_time\x18\xc0\x0c \x01(\x02\x12\x17\n\x0estiff_end_time\x18\xb9\t \x01(\x02\x12\x1a\n\x11minimum_hor_speed\x18\xdf\x04 \x01(\x02\x12\x1a\n\x11skill_flow_offset\x18\xcc\x01 \x01(\x02\x12\x1a\n\x11skill_flow_radius\x18\xde\x07 \x01(\x02\"\x9e\x01\n\x15StiffTemplateTableMgr\x12\x37\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32(.bokura.StiffTemplateTableMgr.DatasEntry\x1aL\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x03\x12-\n\x05value\x18\x02 \x01(\x0b\x32\x1e.bokura.StiffTemplateTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'StiffTemplateTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STIFFTEMPLATETABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_STIFFTEMPLATETABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_STIFFTEMPLATETABLEBASE']._serialized_start=37
  _globals['_STIFFTEMPLATETABLEBASE']._serialized_end=322
  _globals['_STIFFTEMPLATETABLEMGR']._serialized_start=325
  _globals['_STIFFTEMPLATETABLEMGR']._serialized_end=483
  _globals['_STIFFTEMPLATETABLEMGR_DATASENTRY']._serialized_start=407
  _globals['_STIFFTEMPLATETABLEMGR_DATASENTRY']._serialized_end=483
# @@protoc_insertion_point(module_scope)
