# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_personal_zone_show.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_personal_zone_show.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dstru_personal_zone_show.proto\x12\x06zproto\"w\n\x10PersonalZoneShow\x12\x34\n\x06medals\x18\x01 \x03(\x0b\x32$.zproto.PersonalZoneShow.MedalsEntry\x1a-\n\x0bMedalsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_personal_zone_show_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PERSONALZONESHOW_MEDALSENTRY']._loaded_options = None
  _globals['_PERSONALZONESHOW_MEDALSENTRY']._serialized_options = b'8\001'
  _globals['_PERSONALZONESHOW']._serialized_start=41
  _globals['_PERSONALZONESHOW']._serialized_end=160
  _globals['_PERSONALZONESHOW_MEDALSENTRY']._serialized_start=115
  _globals['_PERSONALZONESHOW_MEDALSENTRY']._serialized_end=160
# @@protoc_insertion_point(module_scope)
