# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_buff_d_b_info.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_buff_d_b_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_buff_d_b_data_pb2 as stru__buff__d__b__data__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18stru_buff_d_b_info.proto\x12\x06zproto\x1a\x18stru_buff_d_b_data.proto\"\xa7\x01\n\nBuffDBInfo\x12\x0e\n\x06max_id\x18\x01 \x01(\r\x12?\n\x10\x61ll_buff_db_data\x18\x02 \x03(\x0b\x32%.zproto.BuffDBInfo.AllBuffDbDataEntry\x1aH\n\x12\x41llBuffDbDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12!\n\x05value\x18\x02 \x01(\x0b\x32\x12.zproto.BuffDBData:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_buff_d_b_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BUFFDBINFO_ALLBUFFDBDATAENTRY']._loaded_options = None
  _globals['_BUFFDBINFO_ALLBUFFDBDATAENTRY']._serialized_options = b'8\001'
  _globals['_BUFFDBINFO']._serialized_start=63
  _globals['_BUFFDBINFO']._serialized_end=230
  _globals['_BUFFDBINFO_ALLBUFFDBDATAENTRY']._serialized_start=158
  _globals['_BUFFDBINFO_ALLBUFFDBDATAENTRY']._serialized_end=230
# @@protoc_insertion_point(module_scope)
