# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_set_personal_zone_photo_request.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_set_personal_zone_photo_request.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*stru_set_personal_zone_photo_request.proto\x12\x06zproto\"\x8d\x01\n\x1bSetPersonalZonePhotoRequest\x12?\n\x06photos\x18\x03 \x03(\x0b\x32/.zproto.SetPersonalZonePhotoRequest.PhotosEntry\x1a-\n\x0bPhotosEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_set_personal_zone_photo_request_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SETPERSONALZONEPHOTOREQUEST_PHOTOSENTRY']._loaded_options = None
  _globals['_SETPERSONALZONEPHOTOREQUEST_PHOTOSENTRY']._serialized_options = b'8\001'
  _globals['_SETPERSONALZONEPHOTOREQUEST']._serialized_start=55
  _globals['_SETPERSONALZONEPHOTOREQUEST']._serialized_end=196
  _globals['_SETPERSONALZONEPHOTOREQUEST_PHOTOSENTRY']._serialized_start=151
  _globals['_SETPERSONALZONEPHOTOREQUEST_PHOTOSENTRY']._serialized_end=196
# @@protoc_insertion_point(module_scope)
