# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_newbie_backflow_elective.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_newbie_backflow_elective.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_newbie_backflow_target_data_pb2 as stru__newbie__backflow__target__data__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#stru_newbie_backflow_elective.proto\x12\x06zproto\x1a&stru_newbie_backflow_target_data.proto\"\xcd\x01\n\x16NewbieBackflowElective\x12\x41\n\ntarget_map\x18\x01 \x03(\x0b\x32-.zproto.NewbieBackflowElective.TargetMapEntry\x12\x1c\n\x14progress_award_state\x18\x02 \x03(\x05\x1aR\n\x0eTargetMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12/\n\x05value\x18\x02 \x01(\x0b\x32 .zproto.NewbieBackflowTargetData:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_newbie_backflow_elective_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NEWBIEBACKFLOWELECTIVE_TARGETMAPENTRY']._loaded_options = None
  _globals['_NEWBIEBACKFLOWELECTIVE_TARGETMAPENTRY']._serialized_options = b'8\001'
  _globals['_NEWBIEBACKFLOWELECTIVE']._serialized_start=88
  _globals['_NEWBIEBACKFLOWELECTIVE']._serialized_end=293
  _globals['_NEWBIEBACKFLOWELECTIVE_TARGETMAPENTRY']._serialized_start=211
  _globals['_NEWBIEBACKFLOWELECTIVE_TARGETMAPENTRY']._serialized_end=293
# @@protoc_insertion_point(module_scope)
