# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_get_homeland_bulletin_boards_reply.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_get_homeland_bulletin_boards_reply.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_community_bulletin_board_pb2 as stru__community__bulletin__board__pb2
import enum_e_error_code_pb2 as enum__e__error__code__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-stru_get_homeland_bulletin_boards_reply.proto\x12\x06zproto\x1a#stru_community_bulletin_board.proto\x1a\x17\x65num_e_error_code.proto\"\x7f\n\x1eGetHomelandBulletinBoardsReply\x12\x37\n\x0f\x62ulletin_boards\x18\x01 \x03(\x0b\x32\x1e.zproto.CommunityBulletinBoard\x12$\n\x08\x65rr_code\x18\x02 \x01(\x0e\x32\x12.zproto.EErrorCodeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_get_homeland_bulletin_boards_reply_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETHOMELANDBULLETINBOARDSREPLY']._serialized_start=119
  _globals['_GETHOMELANDBULLETINBOARDSREPLY']._serialized_end=246
# @@protoc_insertion_point(module_scope)
