# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_equip_slot_refine_request.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_equip_slot_refine_request.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_equip_slot_refine_item_cost_pb2 as stru__equip__slot__refine__item__cost__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$stru_equip_slot_refine_request.proto\x12\x06zproto\x1a&stru_equip_slot_refine_item_cost.proto\"b\n\x16\x45quipSlotRefineRequest\x12\x0f\n\x07slot_id\x18\x01 \x01(\r\x12\x37\n\x0eitem_cost_list\x18\x02 \x03(\x0b\x32\x1f.zproto.EquipSlotRefineItemCostb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_equip_slot_refine_request_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EQUIPSLOTREFINEREQUEST']._serialized_start=88
  _globals['_EQUIPSLOTREFINEREQUEST']._serialized_end=186
# @@protoc_insertion_point(module_scope)
