# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_dungeon_target.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_dungeon_target.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_dungeon_target_data_pb2 as stru__dungeon__target__data__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19stru_dungeon_target.proto\x12\x06zproto\x1a\x1estru_dungeon_target_data.proto\"\x99\x01\n\rDungeonTarget\x12:\n\x0btarget_data\x18\x01 \x03(\x0b\x32%.zproto.DungeonTarget.TargetDataEntry\x1aL\n\x0fTargetDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12(\n\x05value\x18\x02 \x01(\x0b\x32\x19.zproto.DungeonTargetData:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_dungeon_target_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DUNGEONTARGET_TARGETDATAENTRY']._loaded_options = None
  _globals['_DUNGEONTARGET_TARGETDATAENTRY']._serialized_options = b'8\001'
  _globals['_DUNGEONTARGET']._serialized_start=70
  _globals['_DUNGEONTARGET']._serialized_end=223
  _globals['_DUNGEONTARGET_TARGETDATAENTRY']._serialized_start=147
  _globals['_DUNGEONTARGET_TARGETDATAENTRY']._serialized_end=223
# @@protoc_insertion_point(module_scope)
