# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_union_member.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_union_member.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17stru_union_member.proto\x12\x06zproto\"\x80\x01\n\x0bUnionMember\x12\x13\n\x0bofficial_id\x18\x01 \x01(\x05\x12\x0e\n\x06mem_id\x18\x02 \x01(\x03\x12\x11\n\tjoin_time\x18\x03 \x01(\x03\x12\x1a\n\x12week_active_points\x18\x04 \x01(\x03\x12\x1d\n\x15history_active_points\x18\x05 \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_union_member_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UNIONMEMBER']._serialized_start=36
  _globals['_UNIONMEMBER']._serialized_end=164
# @@protoc_insertion_point(module_scope)
