# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_play_action_param.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_play_action_param.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cstru_play_action_param.proto\x12\x06zproto\"w\n\x0fPlayActionParam\x12\x11\n\taction_id\x18\x01 \x01(\x05\x12\x10\n\x08is_upper\x18\x02 \x01(\x08\x12\x19\n\x11is_dance_together\x18\x03 \x01(\x08\x12\x10\n\x08mount_id\x18\x04 \x01(\x05\x12\x12\n\nmount_size\x18\x05 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_play_action_param_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PLAYACTIONPARAM']._serialized_start=40
  _globals['_PLAYACTIONPARAM']._serialized_end=159
# @@protoc_insertion_point(module_scope)
