# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_role_level.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_role_level.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_level_proficiency_pb2 as stru__level__proficiency__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15stru_role_level.proto\x12\x06zproto\x1a\x1cstru_level_proficiency.proto\"\xf4\x03\n\tRoleLevel\x12\r\n\x05level\x18\x01 \x01(\x05\x12\x15\n\rcur_level_exp\x18\x02 \x01(\x03\x12\x45\n\x13received_level_list\x18\x03 \x03(\x0b\x32(.zproto.RoleLevel.ReceivedLevelListEntry\x12\x32\n\x10proficiency_info\x18\x04 \x01(\x0b\x32\x18.zproto.LevelProficiency\x12;\n\x0e\x61\x63tive_exp_map\x18\x05 \x03(\x0b\x32#.zproto.RoleLevel.ActiveExpMapEntry\x12\x17\n\x0flast_season_day\x18\x06 \x01(\x05\x12\x16\n\x0e\x62less_exp_pool\x18\x07 \x01(\x03\x12\x17\n\x0fgrant_bless_exp\x18\x08 \x01(\x03\x12\x1c\n\x14\x61\x63\x63umulate_bless_exp\x18\t \x01(\x03\x12\x16\n\x0e\x61\x63\x63umulate_exp\x18\n \x01(\x03\x12\x1a\n\x12prev_season_max_lv\x18\x0b \x01(\x05\x1a\x38\n\x16ReceivedLevelListEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x08:\x02\x38\x01\x1a\x33\n\x11\x41\x63tiveExpMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x03:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_role_level_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROLELEVEL_RECEIVEDLEVELLISTENTRY']._loaded_options = None
  _globals['_ROLELEVEL_RECEIVEDLEVELLISTENTRY']._serialized_options = b'8\001'
  _globals['_ROLELEVEL_ACTIVEEXPMAPENTRY']._loaded_options = None
  _globals['_ROLELEVEL_ACTIVEEXPMAPENTRY']._serialized_options = b'8\001'
  _globals['_ROLELEVEL']._serialized_start=64
  _globals['_ROLELEVEL']._serialized_end=564
  _globals['_ROLELEVEL_RECEIVEDLEVELLISTENTRY']._serialized_start=455
  _globals['_ROLELEVEL_RECEIVEDLEVELLISTENTRY']._serialized_end=511
  _globals['_ROLELEVEL_ACTIVEEXPMAPENTRY']._serialized_start=513
  _globals['_ROLELEVEL_ACTIVEEXPMAPENTRY']._serialized_end=564
# @@protoc_insertion_point(module_scope)
