# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_exchange_sell_item_reply.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_exchange_sell_item_reply.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import enum_e_error_code_pb2 as enum__e__error__code__pb2
import stru_exchange_sell_item_data_pb2 as stru__exchange__sell__item__data__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#stru_exchange_sell_item_reply.proto\x12\x06zproto\x1a\x17\x65num_e_error_code.proto\x1a\"stru_exchange_sell_item_data.proto\"\x85\x02\n\x15\x45xchangeSellItemReply\x12+\n\x05items\x18\x02 \x03(\x0b\x32\x1c.zproto.ExchangeSellItemData\x12G\n\x0ewith_draw_item\x18\x03 \x03(\x0b\x32/.zproto.ExchangeSellItemReply.WithDrawItemEntry\x12\r\n\x05limit\x18\x04 \x01(\x05\x12\x0c\n\x04rate\x18\x05 \x01(\x05\x12$\n\x08\x65rr_code\x18\x06 \x01(\x0e\x32\x12.zproto.EErrorCode\x1a\x33\n\x11WithDrawItemEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_exchange_sell_item_reply_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXCHANGESELLITEMREPLY_WITHDRAWITEMENTRY']._loaded_options = None
  _globals['_EXCHANGESELLITEMREPLY_WITHDRAWITEMENTRY']._serialized_options = b'8\001'
  _globals['_EXCHANGESELLITEMREPLY']._serialized_start=109
  _globals['_EXCHANGESELLITEMREPLY']._serialized_end=370
  _globals['_EXCHANGESELLITEMREPLY_WITHDRAWITEMENTRY']._serialized_start=319
  _globals['_EXCHANGESELLITEMREPLY_WITHDRAWITEMENTRY']._serialized_end=370
# @@protoc_insertion_point(module_scope)
