# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_player_record_info.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_player_record_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_player_record_single_pb2 as stru__player__record__single__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dstru_player_record_info.proto\x12\x06zproto\x1a\x1fstru_player_record_single.proto\"\xa9\x01\n\x10PlayerRecordInfo\x12\x43\n\x0eplayer_records\x18\x01 \x03(\x0b\x32+.zproto.PlayerRecordInfo.PlayerRecordsEntry\x1aP\n\x12PlayerRecordsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12)\n\x05value\x18\x02 \x01(\x0b\x32\x1a.zproto.PlayerRecordSingle:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_player_record_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PLAYERRECORDINFO_PLAYERRECORDSENTRY']._loaded_options = None
  _globals['_PLAYERRECORDINFO_PLAYERRECORDSENTRY']._serialized_options = b'8\001'
  _globals['_PLAYERRECORDINFO']._serialized_start=75
  _globals['_PLAYERRECORDINFO']._serialized_end=244
  _globals['_PLAYERRECORDINFO_PLAYERRECORDSENTRY']._serialized_start=164
  _globals['_PLAYERRECORDINFO_PLAYERRECORDSENTRY']._serialized_end=244
# @@protoc_insertion_point(module_scope)
