# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_account_data.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_account_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import enum_system_type_pb2 as enum__system__type__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17stru_account_data.proto\x12\x06zproto\x1a\x16\x65num_system_type.proto\"z\n\x0b\x41\x63\x63ountData\x12\x0f\n\x07open_id\x18\x01 \x01(\t\x12\x10\n\x08sdk_type\x18\x02 \x01(\x05\x12\x12\n\naccount_id\x18\x03 \x01(\t\x12\x14\n\x0c\x61\x63\x63ount_uuid\x18\x04 \x01(\t\x12\x1e\n\x02os\x18\x05 \x01(\x0e\x32\x12.zproto.SystemTypeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_account_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACCOUNTDATA']._serialized_start=59
  _globals['_ACCOUNTDATA']._serialized_end=181
# @@protoc_insertion_point(module_scope)
