# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_grow_fund_mem_info.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_grow_fund_mem_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_user_summary_data_pb2 as stru__user__summary__data__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dstru_grow_fund_mem_info.proto\x12\x06zproto\x1a\x1cstru_user_summary_data.proto\"W\n\x0fGrowFundMemInfo\x12\x10\n\x08\x66und_pos\x18\x01 \x01(\x05\x12\x32\n\x11\x62\x61sic_avatar_data\x18\x02 \x01(\x0b\x32\x17.zproto.UserSummaryDatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_grow_fund_mem_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GROWFUNDMEMINFO']._serialized_start=71
  _globals['_GROWFUNDMEMINFO']._serialized_end=158
# @@protoc_insertion_point(module_scope)
