# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_leader_get_apply_list_reply.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_leader_get_apply_list_reply.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_apply_info_pb2 as stru__apply__info__pb2
import enum_e_error_code_pb2 as enum__e__error__code__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&stru_leader_get_apply_list_reply.proto\x12\x06zproto\x1a\x15stru_apply_info.proto\x1a\x17\x65num_e_error_code.proto\"a\n\x17LeaderGetApplyListReply\x12 \n\x05\x61pply\x18\x01 \x03(\x0b\x32\x11.zproto.ApplyInfo\x12$\n\x08\x65rr_code\x18\x02 \x01(\x0e\x32\x12.zproto.EErrorCodeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_leader_get_apply_list_reply_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LEADERGETAPPLYLISTREPLY']._serialized_start=98
  _globals['_LEADERGETAPPLYLISTREPLY']._serialized_end=195
# @@protoc_insertion_point(module_scope)
