# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_dungeon_pioneer.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_dungeon_pioneer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_completed_target_info_pb2 as stru__completed__target__info__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1astru_dungeon_pioneer.proto\x12\x06zproto\x1a stru_completed_target_info.proto\"\xc6\x01\n\x0e\x44ungeonPioneer\x12W\n\x1a\x63ompleted_target_this_time\x18\x01 \x03(\x0b\x32\x33.zproto.DungeonPioneer.CompletedTargetThisTimeEntry\x1a[\n\x1c\x43ompletedTargetThisTimeEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12*\n\x05value\x18\x02 \x01(\x0b\x32\x1b.zproto.CompletedTargetInfo:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_dungeon_pioneer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DUNGEONPIONEER_COMPLETEDTARGETTHISTIMEENTRY']._loaded_options = None
  _globals['_DUNGEONPIONEER_COMPLETEDTARGETTHISTIMEENTRY']._serialized_options = b'8\001'
  _globals['_DUNGEONPIONEER']._serialized_start=73
  _globals['_DUNGEONPIONEER']._serialized_end=271
  _globals['_DUNGEONPIONEER_COMPLETEDTARGETTHISTIMEENTRY']._serialized_start=180
  _globals['_DUNGEONPIONEER_COMPLETEDTARGETTHISTIMEENTRY']._serialized_end=271
# @@protoc_insertion_point(module_scope)
