# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_community_home_data.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_community_home_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_community_homeland_recipe_pb2 as stru__community__homeland__recipe__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1estru_community_home_data.proto\x12\x06zproto\x1a$stru_community_homeland_recipe.proto\"\x83\x02\n\x11\x43ommunityHomeData\x12\x14\n\x0c\x63ommunity_id\x18\x01 \x01(\x03\x12\x13\n\x0bhomeland_id\x18\x02 \x01(\x03\x12\x11\n\tbuy_count\x18\x03 \x01(\x05\x12H\n\x10unlocked_recipes\x18\x04 \x03(\x0b\x32..zproto.CommunityHomeData.UnlockedRecipesEntry\x12\r\n\x05level\x18\x05 \x01(\x05\x1aW\n\x14UnlockedRecipesEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12.\n\x05value\x18\x02 \x01(\x0b\x32\x1f.zproto.CommunityHomelandRecipe:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_community_home_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMUNITYHOMEDATA_UNLOCKEDRECIPESENTRY']._loaded_options = None
  _globals['_COMMUNITYHOMEDATA_UNLOCKEDRECIPESENTRY']._serialized_options = b'8\001'
  _globals['_COMMUNITYHOMEDATA']._serialized_start=81
  _globals['_COMMUNITYHOMEDATA']._serialized_end=340
  _globals['_COMMUNITYHOMEDATA_UNLOCKEDRECIPESENTRY']._serialized_start=253
  _globals['_COMMUNITYHOMEDATA_UNLOCKEDRECIPESENTRY']._serialized_end=340
# @@protoc_insertion_point(module_scope)
