# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_shop_data.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_shop_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_player_buy_record_pb2 as stru__player__buy__record__pb2
import stru_shop_compensation_data_pb2 as stru__shop__compensation__data__pb2
import stru_shop_refresh_record_pb2 as stru__shop__refresh__record__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14stru_shop_data.proto\x12\x06zproto\x1a\x1cstru_player_buy_record.proto\x1a!stru_shop_compensation_data.proto\x1a\x1estru_shop_refresh_record.proto\"\x82\x04\n\x08ShopData\x12\x37\n\x0crefresh_list\x18\x01 \x03(\x0b\x32!.zproto.ShopData.RefreshListEntry\x12\x44\n\x13normal_shop_records\x18\x02 \x03(\x0b\x32\'.zproto.ShopData.NormalShopRecordsEntry\x12\x44\n\x13season_shop_records\x18\x03 \x03(\x0b\x32\'.zproto.ShopData.SeasonShopRecordsEntry\x12<\n\x16\x63ompensation_item_data\x18\x04 \x01(\x0b\x32\x1c.zproto.ShopCompensationData\x1aM\n\x10RefreshListEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12(\n\x05value\x18\x02 \x01(\x0b\x32\x19.zproto.ShopRefreshRecord:\x02\x38\x01\x1aQ\n\x16NormalShopRecordsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.zproto.PlayerBuyRecord:\x02\x38\x01\x1aQ\n\x16SeasonShopRecordsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.zproto.PlayerBuyRecord:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_shop_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SHOPDATA_REFRESHLISTENTRY']._loaded_options = None
  _globals['_SHOPDATA_REFRESHLISTENTRY']._serialized_options = b'8\001'
  _globals['_SHOPDATA_NORMALSHOPRECORDSENTRY']._loaded_options = None
  _globals['_SHOPDATA_NORMALSHOPRECORDSENTRY']._serialized_options = b'8\001'
  _globals['_SHOPDATA_SEASONSHOPRECORDSENTRY']._loaded_options = None
  _globals['_SHOPDATA_SEASONSHOPRECORDSENTRY']._serialized_options = b'8\001'
  _globals['_SHOPDATA']._serialized_start=130
  _globals['_SHOPDATA']._serialized_end=644
  _globals['_SHOPDATA_REFRESHLISTENTRY']._serialized_start=401
  _globals['_SHOPDATA_REFRESHLISTENTRY']._serialized_end=478
  _globals['_SHOPDATA_NORMALSHOPRECORDSENTRY']._serialized_start=480
  _globals['_SHOPDATA_NORMALSHOPRECORDSENTRY']._serialized_end=561
  _globals['_SHOPDATA_SEASONSHOPRECORDSENTRY']._serialized_start=563
  _globals['_SHOPDATA_SEASONSHOPRECORDSENTRY']._serialized_end=644
# @@protoc_insertion_point(module_scope)
