# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_mod_info.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_mod_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_mod_part_upgrade_record_pb2 as stru__mod__part__upgrade__record__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13stru_mod_info.proto\x12\x06zproto\x1a\"stru_mod_part_upgrade_record.proto\"\x80\x01\n\x07ModInfo\x12\x10\n\x08part_ids\x18\x01 \x03(\x05\x12\x35\n\x0fupgrade_records\x18\x02 \x03(\x0b\x32\x1c.zproto.ModPartUpgradeRecord\x12\x14\n\x0csuccess_rate\x18\x03 \x01(\x05\x12\x16\n\x0einit_link_nums\x18\x04 \x03(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_mod_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MODINFO']._serialized_start=68
  _globals['_MODINFO']._serialized_end=196
# @@protoc_insertion_point(module_scope)
