# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_notify_homeland_build_furniture_op_request.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_notify_homeland_build_furniture_op_request.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_notify_build_furniture_op_pb2 as stru__notify__build__furniture__op__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5stru_notify_homeland_build_furniture_op_request.proto\x12\x06zproto\x1a$stru_notify_build_furniture_op.proto\"\xb7\x01\n%NotifyHomelandBuildFurnitureOpRequest\x12\x14\n\x0c\x63ommunity_id\x18\x01 \x01(\x03\x12\x13\n\x0bhomeland_id\x18\x02 \x01(\x03\x12\x10\n\x08is_outer\x18\x03 \x01(\x08\x12\x12\n\nscene_guid\x18\x04 \x01(\t\x12=\n\x15\x62uild_furniture_infos\x18\x05 \x03(\x0b\x32\x1e.zproto.NotifyBuildFurnitureOpb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_notify_homeland_build_furniture_op_request_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NOTIFYHOMELANDBUILDFURNITUREOPREQUEST']._serialized_start=104
  _globals['_NOTIFYHOMELANDBUILDFURNITUREOPREQUEST']._serialized_end=287
# @@protoc_insertion_point(module_scope)
