# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_profession_project_list.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_profession_project_list.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_profession_project_common_sync_data_pb2 as stru__profession__project__common__sync__data__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"stru_profession_project_list.proto\x12\x06zproto\x1a.stru_profession_project_common_sync_data.proto\"\xf5\x01\n\x15ProfessionProjectList\x12Y\n\x17profession_project_list\x18\x01 \x03(\x0b\x32\x38.zproto.ProfessionProjectList.ProfessionProjectListEntry\x12\x1a\n\x12\x63urrent_project_id\x18\x02 \x01(\x05\x1a\x65\n\x1aProfessionProjectListEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x36\n\x05value\x18\x02 \x01(\x0b\x32\'.zproto.ProfessionProjectCommonSyncData:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_profession_project_list_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROFESSIONPROJECTLIST_PROFESSIONPROJECTLISTENTRY']._loaded_options = None
  _globals['_PROFESSIONPROJECTLIST_PROFESSIONPROJECTLISTENTRY']._serialized_options = b'8\001'
  _globals['_PROFESSIONPROJECTLIST']._serialized_start=95
  _globals['_PROFESSIONPROJECTLIST']._serialized_end=340
  _globals['_PROFESSIONPROJECTLIST_PROFESSIONPROJECTLISTENTRY']._serialized_start=239
  _globals['_PROFESSIONPROJECTLIST_PROFESSIONPROJECTLISTENTRY']._serialized_end=340
# @@protoc_insertion_point(module_scope)
