# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_package.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_package.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_item_pb2 as stru__item__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12stru_package.proto\x12\x06zproto\x1a\x0fstru_item.proto\"\x9c\x02\n\x07Package\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x14\n\x0cmax_capacity\x18\x02 \x01(\x05\x12,\n\x07item_cd\x18\x03 \x03(\x0b\x32\x1b.zproto.Package.ItemCdEntry\x12)\n\x05items\x18\x04 \x03(\x0b\x32\x1a.zproto.Package.ItemsEntry\x12\x11\n\tpublic_cd\x18\x05 \x01(\x03\x12\x16\n\x0e\x63hange_version\x18\x06 \x01(\x05\x1a-\n\x0bItemCdEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x03:\x02\x38\x01\x1a:\n\nItemsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x03\x12\x1b\n\x05value\x18\x02 \x01(\x0b\x32\x0c.zproto.Item:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_package_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PACKAGE_ITEMCDENTRY']._loaded_options = None
  _globals['_PACKAGE_ITEMCDENTRY']._serialized_options = b'8\001'
  _globals['_PACKAGE_ITEMSENTRY']._loaded_options = None
  _globals['_PACKAGE_ITEMSENTRY']._serialized_options = b'8\001'
  _globals['_PACKAGE']._serialized_start=48
  _globals['_PACKAGE']._serialized_end=332
  _globals['_PACKAGE_ITEMCDENTRY']._serialized_start=227
  _globals['_PACKAGE_ITEMCDENTRY']._serialized_end=272
  _globals['_PACKAGE_ITEMSENTRY']._serialized_start=274
  _globals['_PACKAGE_ITEMSENTRY']._serialized_end=332
# @@protoc_insertion_point(module_scope)
