# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_union_activity_rank_info.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_union_activity_rank_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_avatar_info_pb2 as stru__avatar__info__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#stru_union_activity_rank_info.proto\x12\x06zproto\x1a\x16stru_avatar_info.proto\"\x85\x01\n\x15UnionActivityRankInfo\x12\x0f\n\x07\x63har_id\x18\x01 \x01(\x03\x12\x11\n\tchar_name\x18\x02 \x01(\t\x12\'\n\x0b\x61vatar_info\x18\x03 \x01(\x0b\x32\x12.zproto.AvatarInfo\x12\x10\n\x08rank_idx\x18\x04 \x01(\x05\x12\r\n\x05value\x18\x05 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_union_activity_rank_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UNIONACTIVITYRANKINFO']._serialized_start=72
  _globals['_UNIONACTIVITYRANKINFO']._serialized_end=205
# @@protoc_insertion_point(module_scope)
