# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_monster_hunt_info.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_monster_hunt_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_monster_hunt_target_pb2 as stru__monster__hunt__target__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cstru_monster_hunt_info.proto\x12\x06zproto\x1a\x1estru_monster_hunt_target.proto\"\xe3\x03\n\x0fMonsterHuntInfo\x12G\n\x11monster_hunt_list\x18\x01 \x03(\x0b\x32,.zproto.MonsterHuntInfo.MonsterHuntListEntry\x12\x11\n\tcur_level\x18\x02 \x01(\x05\x12\x0f\n\x07\x63ur_exp\x18\x03 \x01(\x05\x12\x45\n\x10level_award_flag\x18\x04 \x03(\x0b\x32+.zproto.MonsterHuntInfo.LevelAwardFlagEntry\x12T\n\x18monster_hunt_refrsh_time\x18\x06 \x03(\x0b\x32\x32.zproto.MonsterHuntInfo.MonsterHuntRefrshTimeEntry\x1aQ\n\x14MonsterHuntListEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12(\n\x05value\x18\x02 \x01(\x0b\x32\x19.zproto.MonsterHuntTarget:\x02\x38\x01\x1a\x35\n\x13LevelAwardFlagEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x1a<\n\x1aMonsterHuntRefrshTimeEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x03:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_monster_hunt_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MONSTERHUNTINFO_MONSTERHUNTLISTENTRY']._loaded_options = None
  _globals['_MONSTERHUNTINFO_MONSTERHUNTLISTENTRY']._serialized_options = b'8\001'
  _globals['_MONSTERHUNTINFO_LEVELAWARDFLAGENTRY']._loaded_options = None
  _globals['_MONSTERHUNTINFO_LEVELAWARDFLAGENTRY']._serialized_options = b'8\001'
  _globals['_MONSTERHUNTINFO_MONSTERHUNTREFRSHTIMEENTRY']._loaded_options = None
  _globals['_MONSTERHUNTINFO_MONSTERHUNTREFRSHTIMEENTRY']._serialized_options = b'8\001'
  _globals['_MONSTERHUNTINFO']._serialized_start=73
  _globals['_MONSTERHUNTINFO']._serialized_end=556
  _globals['_MONSTERHUNTINFO_MONSTERHUNTLISTENTRY']._serialized_start=358
  _globals['_MONSTERHUNTINFO_MONSTERHUNTLISTENTRY']._serialized_end=439
  _globals['_MONSTERHUNTINFO_LEVELAWARDFLAGENTRY']._serialized_start=441
  _globals['_MONSTERHUNTINFO_LEVELAWARDFLAGENTRY']._serialized_end=494
  _globals['_MONSTERHUNTINFO_MONSTERHUNTREFRSHTIMEENTRY']._serialized_start=496
  _globals['_MONSTERHUNTINFO_MONSTERHUNTREFRSHTIMEENTRY']._serialized_end=556
# @@protoc_insertion_point(module_scope)
