# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_action_group_save_data.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_action_group_save_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_action_group_save_info_pb2 as stru__action__group__save__info__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!stru_action_group_save_data.proto\x12\x06zproto\x1a!stru_action_group_save_info.proto\"\xd8\x01\n\x13\x41\x63tionGroupSaveData\x12V\n\x17\x61\x63tion_group_save_infos\x18\x01 \x03(\x0b\x32\x35.zproto.ActionGroupSaveData.ActionGroupSaveInfosEntry\x12\x0f\n\x07is_init\x18\x02 \x01(\x08\x1aX\n\x19\x41\x63tionGroupSaveInfosEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12*\n\x05value\x18\x02 \x01(\x0b\x32\x1b.zproto.ActionGroupSaveInfo:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_action_group_save_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACTIONGROUPSAVEDATA_ACTIONGROUPSAVEINFOSENTRY']._loaded_options = None
  _globals['_ACTIONGROUPSAVEDATA_ACTIONGROUPSAVEINFOSENTRY']._serialized_options = b'8\001'
  _globals['_ACTIONGROUPSAVEDATA']._serialized_start=81
  _globals['_ACTIONGROUPSAVEDATA']._serialized_end=297
  _globals['_ACTIONGROUPSAVEDATA_ACTIONGROUPSAVEINFOSENTRY']._serialized_start=209
  _globals['_ACTIONGROUPSAVEDATA_ACTIONGROUPSAVEINFOSENTRY']._serialized_end=297
# @@protoc_insertion_point(module_scope)
