# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_get_face_upload_data_reply.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_get_face_upload_data_reply.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import enum_e_error_code_pb2 as enum__e__error__code__pb2
import stru_face_upload_data_pb2 as stru__face__upload__data__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%stru_get_face_upload_data_reply.proto\x12\x06zproto\x1a\x17\x65num_e_error_code.proto\x1a\x1bstru_face_upload_data.proto\"r\n\x16GetFaceUploadDataReply\x12\x32\n\x12\x66\x61\x63\x65_cos_data_list\x18\x01 \x03(\x0b\x32\x16.zproto.FaceUploadData\x12$\n\x08\x65rr_code\x18\x02 \x01(\x0e\x32\x12.zproto.EErrorCodeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_get_face_upload_data_reply_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETFACEUPLOADDATAREPLY']._serialized_start=103
  _globals['_GETFACEUPLOADDATAREPLY']._serialized_end=217
# @@protoc_insertion_point(module_scope)
