# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_scene_lua_data.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_scene_lua_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19stru_scene_lua_data.proto\x12\x06zproto\"\x83\x01\n\x0cSceneLuaData\x12>\n\x0escene_lua_info\x18\x01 \x03(\x0b\x32&.zproto.SceneLuaData.SceneLuaInfoEntry\x1a\x33\n\x11SceneLuaInfoEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_scene_lua_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCENELUADATA_SCENELUAINFOENTRY']._loaded_options = None
  _globals['_SCENELUADATA_SCENELUAINFOENTRY']._serialized_options = b'8\001'
  _globals['_SCENELUADATA']._serialized_start=38
  _globals['_SCENELUADATA']._serialized_end=169
  _globals['_SCENELUADATA_SCENELUAINFOENTRY']._serialized_start=118
  _globals['_SCENELUADATA_SCENELUAINFOENTRY']._serialized_end=169
# @@protoc_insertion_point(module_scope)
