# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_social_info.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_social_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_user_summary_data_pb2 as stru__user__summary__data__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16stru_social_info.proto\x12\x06zproto\x1a\x1cstru_user_summary_data.proto\"\x94\x01\n\nSocialInfo\x12\x0e\n\x06remark\x18\x01 \x01(\t\x12\x0e\n\x06remind\x18\x02 \x01(\x08\x12\x0b\n\x03top\x18\x03 \x01(\x08\x12\x10\n\x08group_id\x18\x04 \x01(\x05\x12,\n\x0bsocial_data\x18\x05 \x01(\x0b\x32\x17.zproto.UserSummaryData\x12\x19\n\x11last_refresh_time\x18\x06 \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_social_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SOCIALINFO']._serialized_start=65
  _globals['_SOCIALINFO']._serialized_end=213
# @@protoc_insertion_point(module_scope)
