# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_community_bulletin_board.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_community_bulletin_board.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_community_bulletin_board_operator_char_pb2 as stru__community__bulletin__board__operator__char__pb2
import stru_community_bulletin_board_target_char_pb2 as stru__community__bulletin__board__target__char__pb2
import enum_e_community_bulletin_board_type_pb2 as enum__e__community__bulletin__board__type__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#stru_community_bulletin_board.proto\x12\x06zproto\x1a\x31stru_community_bulletin_board_operator_char.proto\x1a/stru_community_bulletin_board_target_char.proto\x1a*enum_e_community_bulletin_board_type.proto\"\xec\x01\n\x16\x43ommunityBulletinBoard\x12\x31\n\x04type\x18\x01 \x01(\x0e\x32#.zproto.ECommunityBulletinBoardType\x12\x41\n\roperator_char\x18\x02 \x01(\x0b\x32*.zproto.CommunityBulletinBoardOperatorChar\x12=\n\x0btarget_char\x18\x03 \x01(\x0b\x32(.zproto.CommunityBulletinBoardTargetChar\x12\x0c\n\x04time\x18\x04 \x01(\x03\x12\x0f\n\x07\x63ontent\x18\x05 \x03(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_community_bulletin_board_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMUNITYBULLETINBOARD']._serialized_start=192
  _globals['_COMMUNITYBULLETINBOARD']._serialized_end=428
# @@protoc_insertion_point(module_scope)
