# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_play_helper.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_play_helper.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16stru_play_helper.proto\x12\x06zproto\"\x8c\x02\n\nPlayHelper\x12J\n\x15\x64isplayed_helper_list\x18\x01 \x03(\x0b\x32+.zproto.PlayHelper.DisplayedHelperListEntry\x12?\n\x0f\x63ompleted_guide\x18\x02 \x03(\x0b\x32&.zproto.PlayHelper.CompletedGuideEntry\x1a:\n\x18\x44isplayedHelperListEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x08:\x02\x38\x01\x1a\x35\n\x13\x43ompletedGuideEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x08:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_play_helper_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PLAYHELPER_DISPLAYEDHELPERLISTENTRY']._loaded_options = None
  _globals['_PLAYHELPER_DISPLAYEDHELPERLISTENTRY']._serialized_options = b'8\001'
  _globals['_PLAYHELPER_COMPLETEDGUIDEENTRY']._loaded_options = None
  _globals['_PLAYHELPER_COMPLETEDGUIDEENTRY']._serialized_options = b'8\001'
  _globals['_PLAYHELPER']._serialized_start=35
  _globals['_PLAYHELPER']._serialized_end=303
  _globals['_PLAYHELPER_DISPLAYEDHELPERLISTENTRY']._serialized_start=190
  _globals['_PLAYHELPER_DISPLAYEDHELPERLISTENTRY']._serialized_end=248
  _globals['_PLAYHELPER_COMPLETEDGUIDEENTRY']._serialized_start=250
  _globals['_PLAYHELPER_COMPLETEDGUIDEENTRY']._serialized_end=303
# @@protoc_insertion_point(module_scope)
