# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_notify_union_activity_progress_request.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_notify_union_activity_progress_request.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_union_activity_progress_info_pb2 as stru__union__activity__progress__info__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1stru_notify_union_activity_progress_request.proto\x12\x06zproto\x1a\'stru_union_activity_progress_info.proto\"^\n\"NotifyUnionActivityProgressRequest\x12\x38\n\rprogress_info\x18\x02 \x01(\x0b\x32!.zproto.UnionActivityProgressInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_notify_union_activity_progress_request_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NOTIFYUNIONACTIVITYPROGRESSREQUEST']._serialized_start=102
  _globals['_NOTIFYUNIONACTIVITYPROGRESSREQUEST']._serialized_end=196
# @@protoc_insertion_point(module_scope)
