# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_treasure.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_treasure.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_treasure_item_row_pb2 as stru__treasure__item__row__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13stru_treasure.proto\x12\x06zproto\x1a\x1cstru_treasure_item_row.proto\"\x83\x03\n\x08Treasure\x12(\n\x04rows\x18\x01 \x03(\x0b\x32\x1a.zproto.Treasure.RowsEntry\x12\x37\n\x0chistory_rows\x18\x02 \x03(\x0b\x32!.zproto.Treasure.HistoryRowsEntry\x12\x0c\n\x04\x66lag\x18\x03 \x01(\x08\x12\x14\n\x0crefresh_time\x18\x04 \x01(\x03\x12\x17\n\x0fselected_reward\x18\x05 \x03(\x05\x12\x11\n\tseason_id\x18\x06 \x01(\x05\x12\x16\n\x0elast_season_id\x18\x07 \x01(\x05\x12\x19\n\x11last_refresh_time\x18\x08 \x01(\x03\x1a\x44\n\tRowsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.zproto.TreasureItemRow:\x02\x38\x01\x1aK\n\x10HistoryRowsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.zproto.TreasureItemRow:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_treasure_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TREASURE_ROWSENTRY']._loaded_options = None
  _globals['_TREASURE_ROWSENTRY']._serialized_options = b'8\001'
  _globals['_TREASURE_HISTORYROWSENTRY']._loaded_options = None
  _globals['_TREASURE_HISTORYROWSENTRY']._serialized_options = b'8\001'
  _globals['_TREASURE']._serialized_start=62
  _globals['_TREASURE']._serialized_end=449
  _globals['_TREASURE_ROWSENTRY']._serialized_start=304
  _globals['_TREASURE_ROWSENTRY']._serialized_end=372
  _globals['_TREASURE_HISTORYROWSENTRY']._serialized_start=374
  _globals['_TREASURE_HISTORYROWSENTRY']._serialized_end=449
# @@protoc_insertion_point(module_scope)
