# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_album_show.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_album_show.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import enum_e_album_right_pb2 as enum__e__album__right__pb2
import stru_image_info_pb2 as stru__image__info__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15stru_album_show.proto\x12\x06zproto\x1a\x18\x65num_e_album_right.proto\x1a\x15stru_image_info.proto\"\xc0\x01\n\tAlbumShow\x12\x10\n\x08\x61lbum_id\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x12\n\ncan_access\x18\x03 \x01(\x08\x12#\n\x06\x61\x63\x63\x65ss\x18\x04 \x01(\x0e\x32\x13.zproto.EAlbumRight\x12\x16\n\x0e\x63over_photo_id\x18\x05 \x01(\r\x12/\n\x14\x63over_thumbnail_info\x18\x06 \x01(\x0b\x32\x11.zproto.ImageInfo\x12\x11\n\tphoto_ids\x18\x07 \x03(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_album_show_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ALBUMSHOW']._serialized_start=83
  _globals['_ALBUMSHOW']._serialized_end=275
# @@protoc_insertion_point(module_scope)
