# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_monster_target_info.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_monster_target_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import enum_monster_target_award_pb2 as enum__monster__target__award__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1estru_monster_target_info.proto\x12\x06zproto\x1a\x1f\x65num_monster_target_award.proto\"\x8d\x01\n\x11MonsterTargetInfo\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x13\n\x0btarget_uuid\x18\x02 \x01(\x05\x12\x13\n\x0btarget_type\x18\x03 \x01(\x05\x12\x12\n\ntarget_num\x18\x04 \x01(\x05\x12.\n\naward_flag\x18\x05 \x01(\x0e\x32\x1a.zproto.MonsterTargetAwardb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_monster_target_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MONSTERTARGETINFO']._serialized_start=76
  _globals['_MONSTERTARGETINFO']._serialized_end=217
# @@protoc_insertion_point(module_scope)
