# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_login_request.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_login_request.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_device_info_pb2 as stru__device__info__pb2
import stru_launch_param_pb2 as stru__launch__param__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18stru_login_request.proto\x12\x06zproto\x1a\x16stru_device_info.proto\x1a\x17stru_launch_param.proto\"\xf9\x03\n\x0cLoginRequest\x12\x0f\n\x07open_id\x18\x02 \x01(\t\x12\r\n\x05token\x18\x03 \x01(\t\x12\x10\n\x08sdk_type\x18\x04 \x01(\x05\x12\x12\n\nchannel_id\x18\x05 \x01(\x05\x12\n\n\x02os\x18\x06 \x01(\x05\x12\x15\n\rplatform_type\x18\x07 \x01(\x05\x12\'\n\x0b\x64\x65vice_info\x18\x08 \x01(\x0b\x32\x12.zproto.DeviceInfo\x12\x16\n\x0e\x63lient_version\x18\t \x01(\t\x12\x18\n\x10protocol_version\x18\n \x01(\t\x12\x16\n\x0e\x63onfig_version\x18\x0b \x01(\t\x12\x0f\n\x07\x61rea_id\x18\x0c \x01(\x05\x12\x1d\n\x15i_os_ad_service_token\x18\r \x01(\t\x12\x14\n\x0cpay_ext_data\x18\x0e \x01(\t\x12\x1f\n\x17\x63lient_resource_version\x18\x0f \x01(\t\x12)\n\x0claunch_param\x18\x12 \x01(\x0b\x32\x13.zproto.LaunchParam\x12\x15\n\rarea_id_token\x18\x13 \x01(\t\x12\x15\n\ris_cloud_game\x18\x14 \x01(\x08\x12\x13\n\x0b\x64istinct_id\x18\x15 \x01(\t\x12\x17\n\x0f\x62ound_providers\x18\x16 \x03(\t\x12\x10\n\x08language\x18\x17 \x01(\x05\x12\r\n\x05gclid\x18\x18 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_login_request_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGINREQUEST']._serialized_start=86
  _globals['_LOGINREQUEST']._serialized_end=591
# @@protoc_insertion_point(module_scope)
