# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_mahjong_final_message.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_mahjong_final_message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_mahjong_final_settle_info_pb2 as stru__mahjong__final__settle__info__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n stru_mahjong_final_message.proto\x12\x06zproto\x1a$stru_mahjong_final_settle_info.proto\"D\n\x13MahjongFinalMessage\x12-\n\x05infos\x18\x01 \x03(\x0b\x32\x1e.zproto.MahjongFinalSettleInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_mahjong_final_message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MAHJONGFINALMESSAGE']._serialized_start=82
  _globals['_MAHJONGFINALMESSAGE']._serialized_end=150
# @@protoc_insertion_point(module_scope)
