# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_energy_info.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_energy_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_energy_item_info_pb2 as stru__energy__item__info__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16stru_energy_info.proto\x12\x06zproto\x1a\x1bstru_energy_item_info.proto\"\xc7\x01\n\nEnergyInfo\x12\x14\n\x0c\x65nergy_value\x18\x01 \x01(\r\x12\x12\n\nunlock_num\x18\x02 \x01(\r\x12@\n\x10\x65nergy_item_info\x18\x03 \x03(\x0b\x32&.zproto.EnergyInfo.EnergyItemInfoEntry\x1aM\n\x13\x45nergyItemInfoEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.zproto.EnergyItemInfo:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_energy_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENERGYINFO_ENERGYITEMINFOENTRY']._loaded_options = None
  _globals['_ENERGYINFO_ENERGYITEMINFOENTRY']._serialized_options = b'8\001'
  _globals['_ENERGYINFO']._serialized_start=64
  _globals['_ENERGYINFO']._serialized_end=263
  _globals['_ENERGYINFO_ENERGYITEMINFOENTRY']._serialized_start=186
  _globals['_ENERGYINFO_ENERGYITEMINFOENTRY']._serialized_end=263
# @@protoc_insertion_point(module_scope)
