# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_show_piece_data.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_show_piece_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_show_piece_id_list_pb2 as stru__show__piece__id__list__pb2
import stru_show_piece_pair_pb2 as stru__show__piece__pair__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1astru_show_piece_data.proto\x12\x06zproto\x1a\x1dstru_show_piece_id_list.proto\x1a\x1astru_show_piece_pair.proto\"\xe6\x03\n\rShowPieceData\x12H\n\x13often_use_type_list\x18\x01 \x03(\x0b\x32+.zproto.ShowPieceData.OftenUseTypeListEntry\x12\x43\n\x10unlock_type_list\x18\x02 \x03(\x0b\x32).zproto.ShowPieceData.UnlockTypeListEntry\x12P\n\x17roulette_pos_piece_info\x18\x03 \x03(\x0b\x32/.zproto.ShowPieceData.RoulettePosPieceInfoEntry\x1aP\n\x15OftenUseTypeListEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.zproto.ShowPieceIdList:\x02\x38\x01\x1aN\n\x13UnlockTypeListEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.zproto.ShowPieceIdList:\x02\x38\x01\x1aR\n\x19RoulettePosPieceInfoEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12$\n\x05value\x18\x02 \x01(\x0b\x32\x15.zproto.ShowPiecePair:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_show_piece_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SHOWPIECEDATA_OFTENUSETYPELISTENTRY']._loaded_options = None
  _globals['_SHOWPIECEDATA_OFTENUSETYPELISTENTRY']._serialized_options = b'8\001'
  _globals['_SHOWPIECEDATA_UNLOCKTYPELISTENTRY']._loaded_options = None
  _globals['_SHOWPIECEDATA_UNLOCKTYPELISTENTRY']._serialized_options = b'8\001'
  _globals['_SHOWPIECEDATA_ROULETTEPOSPIECEINFOENTRY']._loaded_options = None
  _globals['_SHOWPIECEDATA_ROULETTEPOSPIECEINFOENTRY']._serialized_options = b'8\001'
  _globals['_SHOWPIECEDATA']._serialized_start=98
  _globals['_SHOWPIECEDATA']._serialized_end=584
  _globals['_SHOWPIECEDATA_OFTENUSETYPELISTENTRY']._serialized_start=340
  _globals['_SHOWPIECEDATA_OFTENUSETYPELISTENTRY']._serialized_end=420
  _globals['_SHOWPIECEDATA_UNLOCKTYPELISTENTRY']._serialized_start=422
  _globals['_SHOWPIECEDATA_UNLOCKTYPELISTENTRY']._serialized_end=500
  _globals['_SHOWPIECEDATA_ROULETTEPOSPIECEINFOENTRY']._serialized_start=502
  _globals['_SHOWPIECEDATA_ROULETTEPOSPIECEINFOENTRY']._serialized_end=584
# @@protoc_insertion_point(module_scope)
