# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_sign_status_list.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_sign_status_list.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_sign_status_pb2 as stru__sign__status__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bstru_sign_status_list.proto\x12\x06zproto\x1a\x16stru_sign_status.proto\"\xa1\x01\n\x0eSignStatusList\x12\x44\n\x10sign_status_data\x18\x01 \x03(\x0b\x32*.zproto.SignStatusList.SignStatusDataEntry\x1aI\n\x13SignStatusDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12!\n\x05value\x18\x02 \x01(\x0b\x32\x12.zproto.SignStatus:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_sign_status_list_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SIGNSTATUSLIST_SIGNSTATUSDATAENTRY']._loaded_options = None
  _globals['_SIGNSTATUSLIST_SIGNSTATUSDATAENTRY']._serialized_options = b'8\001'
  _globals['_SIGNSTATUSLIST']._serialized_start=64
  _globals['_SIGNSTATUSLIST']._serialized_end=225
  _globals['_SIGNSTATUSLIST_SIGNSTATUSDATAENTRY']._serialized_start=152
  _globals['_SIGNSTATUSLIST_SIGNSTATUSDATAENTRY']._serialized_end=225
# @@protoc_insertion_point(module_scope)
