# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_mahjong_player_self.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_mahjong_player_self.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_mahjong_player_show_pb2 as stru__mahjong__player__show__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1estru_mahjong_player_self.proto\x12\x06zproto\x1a\x1estru_mahjong_player_show.proto\"\x87\x01\n\x11MahjongPlayerSelf\x12.\n\x0bplayer_show\x18\x01 \x01(\x0b\x32\x19.zproto.MahjongPlayerShow\x12\x0e\n\x06\x63\x61n_do\x18\x02 \x01(\x05\x12\x16\n\x0eoperation_time\x18\x03 \x01(\x03\x12\x1a\n\x12left_thinking_time\x18\x04 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_mahjong_player_self_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MAHJONGPLAYERSELF']._serialized_start=75
  _globals['_MAHJONGPLAYERSELF']._serialized_end=210
# @@protoc_insertion_point(module_scope)
