# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_fish_rank_list.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_fish_rank_list.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_fish_rank_info_pb2 as stru__fish__rank__info__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19stru_fish_rank_list.proto\x12\x06zproto\x1a\x19stru_fish_rank_info.proto\"`\n\x0c\x46ishRankList\x12\'\n\tself_info\x18\x01 \x01(\x0b\x32\x14.zproto.FishRankInfo\x12\'\n\trank_list\x18\x02 \x03(\x0b\x32\x14.zproto.FishRankInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_fish_rank_list_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FISHRANKLIST']._serialized_start=64
  _globals['_FISHRANKLIST']._serialized_end=160
# @@protoc_insertion_point(module_scope)
