# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_equip_attr_set.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_equip_attr_set.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19stru_equip_attr_set.proto\x12\x06zproto\"\xd6\x03\n\x0c\x45quipAttrSet\x12\x37\n\nbasic_attr\x18\x01 \x03(\x0b\x32#.zproto.EquipAttrSet.BasicAttrEntry\x12;\n\x0c\x61\x64vance_attr\x18\x02 \x03(\x0b\x32%.zproto.EquipAttrSet.AdvanceAttrEntry\x12\x39\n\x0brecast_attr\x18\x03 \x03(\x0b\x32$.zproto.EquipAttrSet.RecastAttrEntry\x12\x44\n\x11rare_quality_attr\x18\x04 \x03(\x0b\x32).zproto.EquipAttrSet.RareQualityAttrEntry\x1a\x30\n\x0e\x42\x61sicAttrEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x1a\x32\n\x10\x41\x64vanceAttrEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x1a\x31\n\x0fRecastAttrEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x1a\x36\n\x14RareQualityAttrEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_equip_attr_set_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EQUIPATTRSET_BASICATTRENTRY']._loaded_options = None
  _globals['_EQUIPATTRSET_BASICATTRENTRY']._serialized_options = b'8\001'
  _globals['_EQUIPATTRSET_ADVANCEATTRENTRY']._loaded_options = None
  _globals['_EQUIPATTRSET_ADVANCEATTRENTRY']._serialized_options = b'8\001'
  _globals['_EQUIPATTRSET_RECASTATTRENTRY']._loaded_options = None
  _globals['_EQUIPATTRSET_RECASTATTRENTRY']._serialized_options = b'8\001'
  _globals['_EQUIPATTRSET_RAREQUALITYATTRENTRY']._loaded_options = None
  _globals['_EQUIPATTRSET_RAREQUALITYATTRENTRY']._serialized_options = b'8\001'
  _globals['_EQUIPATTRSET']._serialized_start=38
  _globals['_EQUIPATTRSET']._serialized_end=508
  _globals['_EQUIPATTRSET_BASICATTRENTRY']._serialized_start=301
  _globals['_EQUIPATTRSET_BASICATTRENTRY']._serialized_end=349
  _globals['_EQUIPATTRSET_ADVANCEATTRENTRY']._serialized_start=351
  _globals['_EQUIPATTRSET_ADVANCEATTRENTRY']._serialized_end=401
  _globals['_EQUIPATTRSET_RECASTATTRENTRY']._serialized_start=403
  _globals['_EQUIPATTRSET_RECASTATTRENTRY']._serialized_end=452
  _globals['_EQUIPATTRSET_RAREQUALITYATTRENTRY']._serialized_start=454
  _globals['_EQUIPATTRSET_RAREQUALITYATTRENTRY']._serialized_end=508
# @@protoc_insertion_point(module_scope)
