# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_life_profession_basic.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_life_profession_basic.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_lift_profession_specialization_pb2 as stru__lift__profession__specialization__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n stru_life_profession_basic.proto\x12\x06zproto\x1a)stru_lift_profession_specialization.proto\"\x89\x02\n\x13LifeProfessionBasic\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05level\x18\x02 \x01(\x05\x12\x0b\n\x03\x65xp\x18\x03 \x01(\x05\x12G\n\x0especialization\x18\x05 \x03(\x0b\x32/.zproto.LifeProfessionBasic.SpecializationEntry\x12$\n\x1c\x63urrent_specialization_point\x18\x06 \x01(\x05\x1a[\n\x13SpecializationEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x33\n\x05value\x18\x02 \x01(\x0b\x32$.zproto.LiftProfessionSpecialization:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_life_profession_basic_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LIFEPROFESSIONBASIC_SPECIALIZATIONENTRY']._loaded_options = None
  _globals['_LIFEPROFESSIONBASIC_SPECIALIZATIONENTRY']._serialized_options = b'8\001'
  _globals['_LIFEPROFESSIONBASIC']._serialized_start=88
  _globals['_LIFEPROFESSIONBASIC']._serialized_end=353
  _globals['_LIFEPROFESSIONBASIC_SPECIALIZATIONENTRY']._serialized_start=262
  _globals['_LIFEPROFESSIONBASIC_SPECIALIZATIONENTRY']._serialized_end=353
# @@protoc_insertion_point(module_scope)
