# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_exchange_sale_record.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_exchange_sale_record.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_item_pb2 as stru__item__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fstru_exchange_sale_record.proto\x12\x06zproto\x1a\x0fstru_item.proto\"m\n\x12\x45xchangeSaleRecord\x12\x0b\n\x03num\x18\x01 \x01(\r\x12\x0c\n\x04rate\x18\x02 \x01(\r\x12\r\n\x05money\x18\x03 \x01(\r\x12\x0c\n\x04time\x18\x04 \x01(\x03\x12\x1f\n\titem_info\x18\x05 \x01(\x0b\x32\x0c.zproto.Itemb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_exchange_sale_record_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXCHANGESALERECORD']._serialized_start=60
  _globals['_EXCHANGESALERECORD']._serialized_end=169
# @@protoc_insertion_point(module_scope)
