# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_report_upload_request.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_report_upload_request.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import enum_e_report_category_type_pb2 as enum__e__report__category__type__pb2
import enum_e_report_reason_type_pb2 as enum__e__report__reason__type__pb2
import enum_e_report_scene_type_pb2 as enum__e__report__scene__type__pb2
import stru_report_base_info_pb2 as stru__report__base__info__pb2
import stru_report_chat_pb2 as stru__report__chat__pb2
import stru_report_home_pb2 as stru__report__home__pb2
import stru_report_picture_pb2 as stru__report__picture__pb2
import stru_report_union_pb2 as stru__report__union__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n stru_report_upload_request.proto\x12\x06zproto\x1a!enum_e_report_category_type.proto\x1a\x1f\x65num_e_report_reason_type.proto\x1a\x1e\x65num_e_report_scene_type.proto\x1a\x1bstru_report_base_info.proto\x1a\x16stru_report_chat.proto\x1a\x16stru_report_home.proto\x1a\x19stru_report_picture.proto\x1a\x17stru_report_union.proto\"\x9a\x03\n\x13ReportUploadRequest\x12,\n\nscene_type\x18\x01 \x01(\x0e\x32\x18.zproto.EReportSceneType\x12\x32\n\rcategory_type\x18\x02 \x01(\x0e\x32\x1b.zproto.EReportCategoryType\x12.\n\x0breason_type\x18\x03 \x03(\x0e\x32\x19.zproto.EReportReasonType\x12\x13\n\x0breport_desc\x18\x04 \x01(\t\x12\x30\n\x10report_base_info\x18\x05 \x01(\x0b\x32\x16.zproto.ReportBaseInfo\x12\'\n\x0breport_chat\x18\x06 \x01(\x0b\x32\x12.zproto.ReportChat\x12-\n\x0ereport_picture\x18\x07 \x01(\x0b\x32\x15.zproto.ReportPicture\x12)\n\x0creport_union\x18\x08 \x01(\x0b\x32\x13.zproto.ReportUnion\x12\'\n\x0breport_home\x18\t \x01(\x0b\x32\x12.zproto.ReportHomeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_report_upload_request_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REPORTUPLOADREQUEST']._serialized_start=274
  _globals['_REPORTUPLOADREQUEST']._serialized_end=684
# @@protoc_insertion_point(module_scope)
