# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_action_group_action_clip.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_action_group_action_clip.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_action_group_mount_info_pb2 as stru__action__group__mount__info__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#stru_action_group_action_clip.proto\x12\x06zproto\x1a\"stru_action_group_mount_info.proto\"\xc9\x01\n\x15\x41\x63tionGroupActionClip\x12\x12\n\nbegin_time\x18\x01 \x01(\x02\x12\x10\n\x08\x65nd_time\x18\x02 \x01(\x02\x12\x11\n\tfade_time\x18\x03 \x01(\x02\x12\x11\n\taction_id\x18\x04 \x01(\x05\x12\x19\n\x11\x61\x63tion_begin_time\x18\x05 \x01(\x02\x12\x17\n\x0f\x61\x63tion_end_time\x18\x06 \x01(\x02\x12\x30\n\nmount_info\x18\x07 \x01(\x0b\x32\x1c.zproto.ActionGroupMountInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_action_group_action_clip_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACTIONGROUPACTIONCLIP']._serialized_start=84
  _globals['_ACTIONGROUPACTIONCLIP']._serialized_end=285
# @@protoc_insertion_point(module_scope)
