# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_parkour_record_list.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_parkour_record_list.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_parkour_record_pb2 as stru__parkour__record__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1estru_parkour_record_list.proto\x12\x06zproto\x1a\x19stru_parkour_record.proto\"\x9d\x01\n\x11ParkourRecordList\x12>\n\x0brecord_list\x18\x01 \x03(\x0b\x32).zproto.ParkourRecordList.RecordListEntry\x1aH\n\x0fRecordListEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12$\n\x05value\x18\x02 \x01(\x0b\x32\x15.zproto.ParkourRecord:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_parkour_record_list_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PARKOURRECORDLIST_RECORDLISTENTRY']._loaded_options = None
  _globals['_PARKOURRECORDLIST_RECORDLISTENTRY']._serialized_options = b'8\001'
  _globals['_PARKOURRECORDLIST']._serialized_start=70
  _globals['_PARKOURRECORDLIST']._serialized_end=227
  _globals['_PARKOURRECORDLIST_RECORDLISTENTRY']._serialized_start=155
  _globals['_PARKOURRECORDLIST_RECORDLISTENTRY']._serialized_end=227
# @@protoc_insertion_point(module_scope)
