# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_total_friendliness.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_total_friendliness.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dstru_total_friendliness.proto\x12\x06zproto\"\x86\x01\n\x11TotalFriendliness\x12\r\n\x05level\x18\x01 \x01(\x05\x12\x0f\n\x07\x63ur_exp\x18\x02 \x01(\x05\x12\x19\n\x11update_time_stamp\x18\x03 \x01(\x03\x12\x1c\n\x14today_total_add_exps\x18\x04 \x01(\x05\x12\x18\n\x10got_level_awards\x18\x05 \x03(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_total_friendliness_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TOTALFRIENDLINESS']._serialized_start=42
  _globals['_TOTALFRIENDLINESS']._serialized_end=176
# @@protoc_insertion_point(module_scope)
