# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_community_build_furniture_info.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_community_build_furniture_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_item_pb2 as stru__item__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)stru_community_build_furniture_info.proto\x12\x06zproto\x1a\x0fstru_item.proto\"\xe2\x02\n\x1b\x43ommunityBuildFurnitureInfo\x12\x12\n\nbuild_uuid\x18\x01 \x01(\x03\x12\x14\n\x0c\x66urniture_id\x18\x02 \x01(\x05\x12\x17\n\x0f\x66urniture_count\x18\x03 \x01(\x05\x12\x0f\n\x07\x63har_id\x18\x04 \x01(\x03\x12\x12\n\nstart_time\x18\x05 \x01(\x03\x12\x10\n\x08\x65nd_time\x18\x06 \x01(\x03\x12\x18\n\x10\x61\x63\x63\x65lerate_count\x18\x07 \x01(\x05\x12R\n\x10\x61\x63\x63\x65lerate_items\x18\x08 \x03(\x0b\x32\x38.zproto.CommunityBuildFurnitureInfo.AccelerateItemsEntry\x12#\n\rconsume_items\x18\t \x03(\x0b\x32\x0c.zproto.Item\x1a\x36\n\x14\x41\x63\x63\x65lerateItemsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_community_build_furniture_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMUNITYBUILDFURNITUREINFO_ACCELERATEITEMSENTRY']._loaded_options = None
  _globals['_COMMUNITYBUILDFURNITUREINFO_ACCELERATEITEMSENTRY']._serialized_options = b'8\001'
  _globals['_COMMUNITYBUILDFURNITUREINFO']._serialized_start=71
  _globals['_COMMUNITYBUILDFURNITUREINFO']._serialized_end=425
  _globals['_COMMUNITYBUILDFURNITUREINFO_ACCELERATEITEMSENTRY']._serialized_start=371
  _globals['_COMMUNITYBUILDFURNITUREINFO_ACCELERATEITEMSENTRY']._serialized_end=425
# @@protoc_insertion_point(module_scope)
