# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_match_player_show_info.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_match_player_show_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_avatar_info_pb2 as stru__avatar__info__pb2
import enum_e_body_size_pb2 as enum__e__body__size__pb2
import stru_personal_zone_show_pb2 as stru__personal__zone__show__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!stru_match_player_show_info.proto\x12\x06zproto\x1a\x16stru_avatar_info.proto\x1a\x16\x65num_e_body_size.proto\x1a\x1dstru_personal_zone_show.proto\"\xc2\x01\n\x13MatchPlayerShowInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06gender\x18\x02 \x01(\x05\x12$\n\tbody_size\x18\x03 \x01(\x0e\x32\x11.zproto.EBodySize\x12\r\n\x05level\x18\x04 \x01(\x05\x12\'\n\x0b\x61vatar_info\x18\x05 \x01(\x0b\x32\x12.zproto.AvatarInfo\x12/\n\rpersonal_zone\x18\x06 \x01(\x0b\x32\x18.zproto.PersonalZoneShowb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_match_player_show_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MATCHPLAYERSHOWINFO']._serialized_start=125
  _globals['_MATCHPLAYERSHOWINFO']._serialized_end=319
# @@protoc_insertion_point(module_scope)
