# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_notify_flower_time_update_request.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_notify_flower_time_update_request.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import enum_structure_op_type_pb2 as enum__structure__op__type__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,stru_notify_flower_time_update_request.proto\x12\x06zproto\x1a\x1c\x65num_structure_op_type.proto\"I\n\x1dNotifyFlowerTimeUpdateRequest\x12(\n\x07op_type\x18\x01 \x01(\x0e\x32\x17.zproto.StructureOpTypeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_notify_flower_time_update_request_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NOTIFYFLOWERTIMEUPDATEREQUEST']._serialized_start=86
  _globals['_NOTIFYFLOWERTIMEUPDATEREQUEST']._serialized_end=159
# @@protoc_insertion_point(module_scope)
