# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_temp_photo_cache.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_temp_photo_cache.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_temp_photo_cache_info_pb2 as stru__temp__photo__cache__info__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bstru_temp_photo_cache.proto\x12\x06zproto\x1a stru_temp_photo_cache_info.proto\"\xb6\x01\n\x0etempPhotoCache\x12M\n\x15temp_photo_cache_dict\x18\x01 \x03(\x0b\x32..zproto.tempPhotoCache.TempPhotoCacheDictEntry\x1aU\n\x17TempPhotoCacheDictEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12)\n\x05value\x18\x02 \x01(\x0b\x32\x1a.zproto.tempPhotoCacheInfo:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_temp_photo_cache_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEMPPHOTOCACHE_TEMPPHOTOCACHEDICTENTRY']._loaded_options = None
  _globals['_TEMPPHOTOCACHE_TEMPPHOTOCACHEDICTENTRY']._serialized_options = b'8\001'
  _globals['_TEMPPHOTOCACHE']._serialized_start=74
  _globals['_TEMPPHOTOCACHE']._serialized_end=256
  _globals['_TEMPPHOTOCACHE_TEMPPHOTOCACHEDICTENTRY']._serialized_start=171
  _globals['_TEMPPHOTOCACHE_TEMPPHOTOCACHEDICTENTRY']._serialized_end=256
# @@protoc_insertion_point(module_scope)
