# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_get_friend_base_info_reply.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_get_friend_base_info_reply.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import enum_e_error_code_pb2 as enum__e__error__code__pb2
import stru_friend_base_info_pb2 as stru__friend__base__info__pb2
import stru_friendliness_pb2 as stru__friendliness__pb2
import stru_total_friendliness_pb2 as stru__total__friendliness__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%stru_get_friend_base_info_reply.proto\x12\x06zproto\x1a\x17\x65num_e_error_code.proto\x1a\x1bstru_friend_base_info.proto\x1a\x17stru_friendliness.proto\x1a\x1dstru_total_friendliness.proto\"\xc0\x02\n\x16GetFriendBaseInfoReply\x12)\n\tbase_info\x18\x03 \x01(\x0b\x32\x16.zproto.FriendBaseInfo\x12O\n\x11\x66riendliness_list\x18\x05 \x03(\x0b\x32\x34.zproto.GetFriendBaseInfoReply.FriendlinessListEntry\x12\x35\n\x12total_friendliness\x18\x06 \x01(\x0b\x32\x19.zproto.TotalFriendliness\x12$\n\x08\x65rr_code\x18\x07 \x01(\x0e\x32\x12.zproto.EErrorCode\x1aM\n\x15\x46riendlinessListEntry\x12\x0b\n\x03key\x18\x01 \x01(\x03\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.zproto.Friendliness:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_get_friend_base_info_reply_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETFRIENDBASEINFOREPLY_FRIENDLINESSLISTENTRY']._loaded_options = None
  _globals['_GETFRIENDBASEINFOREPLY_FRIENDLINESSLISTENTRY']._serialized_options = b'8\001'
  _globals['_GETFRIENDBASEINFOREPLY']._serialized_start=160
  _globals['_GETFRIENDBASEINFOREPLY']._serialized_end=480
  _globals['_GETFRIENDBASEINFOREPLY_FRIENDLINESSLISTENTRY']._serialized_start=403
  _globals['_GETFRIENDBASEINFOREPLY_FRIENDLINESSLISTENTRY']._serialized_end=480
# @@protoc_insertion_point(module_scope)
