# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_newbie_act_data.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_newbie_act_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_newbie_backflow_elective_pb2 as stru__newbie__backflow__elective__pb2
import stru_newbie_backflow_target_data_pb2 as stru__newbie__backflow__target__data__pb2
import stru_newbie_backflow_target_id_list_pb2 as stru__newbie__backflow__target__id__list__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1astru_newbie_act_data.proto\x12\x06zproto\x1a#stru_newbie_backflow_elective.proto\x1a&stru_newbie_backflow_target_data.proto\x1a)stru_newbie_backflow_target_id_list.proto\"\xd2\x04\n\rNewbieActData\x12\x12\n\nlogin_days\x18\x01 \x01(\x05\x12\x1a\n\x12refresh_time_stamp\x18\x02 \x01(\x03\x12\x19\n\x11refresh_season_id\x18\x03 \x01(\x05\x12\x16\n\x0e\x61ward_received\x18\x04 \x01(\x08\x12\x19\n\x11graduate_received\x18\x05 \x01(\x08\x12\x38\n\ntarget_map\x18\x06 \x03(\x0b\x32$.zproto.NewbieActData.TargetMapEntry\x12>\n\relective_data\x18\x07 \x03(\x0b\x32\'.zproto.NewbieActData.ElectiveDataEntry\x12\x44\n\x10required_targets\x18\x08 \x03(\x0b\x32*.zproto.NewbieActData.RequiredTargetsEntry\x1aR\n\x0eTargetMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12/\n\x05value\x18\x02 \x01(\x0b\x32 .zproto.NewbieBackflowTargetData:\x02\x38\x01\x1aS\n\x11\x45lectiveDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12-\n\x05value\x18\x02 \x01(\x0b\x32\x1e.zproto.NewbieBackflowElective:\x02\x38\x01\x1aZ\n\x14RequiredTargetsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x31\n\x05value\x18\x02 \x01(\x0b\x32\".zproto.NewbieBackflowTargetIdList:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_newbie_act_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NEWBIEACTDATA_TARGETMAPENTRY']._loaded_options = None
  _globals['_NEWBIEACTDATA_TARGETMAPENTRY']._serialized_options = b'8\001'
  _globals['_NEWBIEACTDATA_ELECTIVEDATAENTRY']._loaded_options = None
  _globals['_NEWBIEACTDATA_ELECTIVEDATAENTRY']._serialized_options = b'8\001'
  _globals['_NEWBIEACTDATA_REQUIREDTARGETSENTRY']._loaded_options = None
  _globals['_NEWBIEACTDATA_REQUIREDTARGETSENTRY']._serialized_options = b'8\001'
  _globals['_NEWBIEACTDATA']._serialized_start=159
  _globals['_NEWBIEACTDATA']._serialized_end=753
  _globals['_NEWBIEACTDATA_TARGETMAPENTRY']._serialized_start=494
  _globals['_NEWBIEACTDATA_TARGETMAPENTRY']._serialized_end=576
  _globals['_NEWBIEACTDATA_ELECTIVEDATAENTRY']._serialized_start=578
  _globals['_NEWBIEACTDATA_ELECTIVEDATAENTRY']._serialized_end=661
  _globals['_NEWBIEACTDATA_REQUIREDTARGETSENTRY']._serialized_start=663
  _globals['_NEWBIEACTDATA_REQUIREDTARGETSENTRY']._serialized_end=753
# @@protoc_insertion_point(module_scope)
