# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_passenger_change_param.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_passenger_change_param.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!stru_passenger_change_param.proto\x12\x06zproto\"x\n\x14PassengerChangeParam\x12\x1b\n\x0eIsAddPassenger\x18\x01 \x01(\x08H\x00\x88\x01\x01\x12\x1c\n\x0f\x41\x64\x64OrRemoveUuid\x18\x02 \x01(\x03H\x01\x88\x01\x01\x42\x11\n\x0f_IsAddPassengerB\x12\n\x10_AddOrRemoveUuidb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_passenger_change_param_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PASSENGERCHANGEPARAM']._serialized_start=45
  _globals['_PASSENGERCHANGEPARAM']._serialized_end=165
# @@protoc_insertion_point(module_scope)
