# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_map_book_info_list.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_map_book_info_list.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_map_book_info_pb2 as stru__map__book__info__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dstru_map_book_info_list.proto\x12\x06zproto\x1a\x18stru_map_book_info.proto\"\x98\x01\n\x0fMapBookInfoList\x12=\n\x0cmap_book_map\x18\x01 \x03(\x0b\x32\'.zproto.MapBookInfoList.MapBookMapEntry\x1a\x46\n\x0fMapBookMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\"\n\x05value\x18\x02 \x01(\x0b\x32\x13.zproto.MapBookInfo:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_map_book_info_list_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MAPBOOKINFOLIST_MAPBOOKMAPENTRY']._loaded_options = None
  _globals['_MAPBOOKINFOLIST_MAPBOOKMAPENTRY']._serialized_options = b'8\001'
  _globals['_MAPBOOKINFOLIST']._serialized_start=68
  _globals['_MAPBOOKINFOLIST']._serialized_end=220
  _globals['_MAPBOOKINFOLIST_MAPBOOKMAPENTRY']._serialized_start=150
  _globals['_MAPBOOKINFOLIST_MAPBOOKMAPENTRY']._serialized_end=220
# @@protoc_insertion_point(module_scope)
