# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_receive_union_activity_award_reply.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_receive_union_activity_award_reply.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import enum_e_error_code_pb2 as enum__e__error__code__pb2
import stru_item_pb2 as stru__item__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-stru_receive_union_activity_award_reply.proto\x12\x06zproto\x1a\x17\x65num_e_error_code.proto\x1a\x0fstru_item.proto\"\xf5\x01\n\x1eReceiveUnionActivityAwardReply\x12 \n\x18received_point_award_ids\x18\x01 \x03(\x05\x12\x1b\n\x05items\x18\x02 \x03(\x0b\x32\x0c.zproto.Item\x12\x1f\n\x17union_last_refresh_time\x18\x03 \x01(\x03\x12\"\n\x1aunion_current_refresh_time\x18\x04 \x01(\x03\x12\x12\n\nlast_point\x18\x05 \x01(\x03\x12\x15\n\rcurrent_point\x18\x06 \x01(\x03\x12$\n\x08\x65rr_code\x18\x07 \x01(\x0e\x32\x12.zproto.EErrorCodeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_receive_union_activity_award_reply_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RECEIVEUNIONACTIVITYAWARDREPLY']._serialized_start=100
  _globals['_RECEIVEUNIONACTIVITYAWARDREPLY']._serialized_end=345
# @@protoc_insertion_point(module_scope)
