# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_backflow_act_data.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_backflow_act_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_newbie_backflow_elective_pb2 as stru__newbie__backflow__elective__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cstru_backflow_act_data.proto\x12\x06zproto\x1a#stru_newbie_backflow_elective.proto\"\x9f\x02\n\x0f\x42\x61\x63kflowActData\x12\x12\n\nlogin_days\x18\x01 \x01(\x05\x12\x1a\n\x12refresh_time_stamp\x18\x02 \x01(\x03\x12\x19\n\x11refresh_season_id\x18\x03 \x01(\x05\x12\x12\n\nsign_state\x18\x04 \x03(\x05\x12\x16\n\x0e\x61ward_received\x18\x05 \x01(\x08\x12@\n\relective_data\x18\x06 \x03(\x0b\x32).zproto.BackflowActData.ElectiveDataEntry\x1aS\n\x11\x45lectiveDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12-\n\x05value\x18\x02 \x01(\x0b\x32\x1e.zproto.NewbieBackflowElective:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_backflow_act_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BACKFLOWACTDATA_ELECTIVEDATAENTRY']._loaded_options = None
  _globals['_BACKFLOWACTDATA_ELECTIVEDATAENTRY']._serialized_options = b'8\001'
  _globals['_BACKFLOWACTDATA']._serialized_start=78
  _globals['_BACKFLOWACTDATA']._serialized_end=365
  _globals['_BACKFLOWACTDATA_ELECTIVEDATAENTRY']._serialized_start=282
  _globals['_BACKFLOWACTDATA_ELECTIVEDATAENTRY']._serialized_end=365
# @@protoc_insertion_point(module_scope)
