# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_notice_update_team_member_info_request.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_notice_update_team_member_info_request.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_team_member_fast_sync_data_pb2 as stru__team__member__fast__sync__data__pb2
import stru_team_mem_data_pb2 as stru__team__mem__data__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1stru_notice_update_team_member_info_request.proto\x12\x06zproto\x1a%stru_team_member_fast_sync_data.proto\x1a\x18stru_team_mem_data.proto\"\x9a\x01\n!NoticeUpdateTeamMemberInfoRequest\x12>\n\x16team_member_sync_datas\x18\x05 \x03(\x0b\x32\x1e.zproto.TeamMemberFastSyncData\x12\x35\n\x18team_member_social_datas\x18\x06 \x03(\x0b\x32\x13.zproto.TeamMemDatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_notice_update_team_member_info_request_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NOTICEUPDATETEAMMEMBERINFOREQUEST']._serialized_start=127
  _globals['_NOTICEUPDATETEAMMEMBERINFOREQUEST']._serialized_end=281
# @@protoc_insertion_point(module_scope)
