# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_homeland_warehouse_store_request.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_homeland_warehouse_store_request.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+stru_homeland_warehouse_store_request.proto\x12\x06zproto\"\x8e\x01\n\x1dHomelandWarehouseStoreRequest\x12?\n\x05items\x18\x01 \x03(\x0b\x32\x30.zproto.HomelandWarehouseStoreRequest.ItemsEntry\x1a,\n\nItemsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x03\x12\r\n\x05value\x18\x02 \x01(\x03:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_homeland_warehouse_store_request_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HOMELANDWAREHOUSESTOREREQUEST_ITEMSENTRY']._loaded_options = None
  _globals['_HOMELANDWAREHOUSESTOREREQUEST_ITEMSENTRY']._serialized_options = b'8\001'
  _globals['_HOMELANDWAREHOUSESTOREREQUEST']._serialized_start=56
  _globals['_HOMELANDWAREHOUSESTOREREQUEST']._serialized_end=198
  _globals['_HOMELANDWAREHOUSESTOREREQUEST_ITEMSENTRY']._serialized_start=154
  _globals['_HOMELANDWAREHOUSESTOREREQUEST_ITEMSENTRY']._serialized_end=198
# @@protoc_insertion_point(module_scope)
