# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_duty_list.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_duty_list.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_duty_info_pb2 as stru__duty__info__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14stru_duty_list.proto\x12\x06zproto\x1a\x14stru_duty_info.proto\"\xaa\x01\n\x08\x44utyList\x12\x1e\n\x16\x63ur_profession_duty_id\x18\x01 \x01(\x05\x12\x38\n\rduty_info_map\x18\x02 \x03(\x0b\x32!.zproto.DutyList.DutyInfoMapEntry\x1a\x44\n\x10\x44utyInfoMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x1f\n\x05value\x18\x02 \x01(\x0b\x32\x10.zproto.DutyInfo:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_duty_list_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DUTYLIST_DUTYINFOMAPENTRY']._loaded_options = None
  _globals['_DUTYLIST_DUTYINFOMAPENTRY']._serialized_options = b'8\001'
  _globals['_DUTYLIST']._serialized_start=55
  _globals['_DUTYLIST']._serialized_end=225
  _globals['_DUTYLIST_DUTYINFOMAPENTRY']._serialized_start=157
  _globals['_DUTYLIST_DUTYINFOMAPENTRY']._serialized_end=225
# @@protoc_insertion_point(module_scope)
