# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_session_info.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_session_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17stru_session_info.proto\x12\x06zproto\"\x8e\x01\n\x0bSessionInfo\x12\x0f\n\x07peer_id\x18\x01 \x01(\r\x12\x0f\n\x07\x63har_id\x18\x02 \x01(\x03\x12\x12\n\naccount_id\x18\x03 \x01(\t\x12\x10\n\x08trace_id\x18\x04 \x01(\x04\x12\x11\n\tremote_ip\x18\x05 \x01(\t\x12\x12\n\nagent_guid\x18\x06 \x01(\t\x12\x10\n\x08is_robot\x18\x07 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_session_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SESSIONINFO']._serialized_start=36
  _globals['_SESSIONINFO']._serialized_end=178
# @@protoc_insertion_point(module_scope)
