# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_shop_item_info.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_shop_item_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_shop_item_buy_limit_pb2 as stru__shop__item__buy__limit__pb2
import enum_shop_limit_buy_type_pb2 as enum__shop__limit__buy__type__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19stru_shop_item_info.proto\x12\x06zproto\x1a\x1estru_shop_item_buy_limit.proto\x1a\x1e\x65num_shop_limit_buy_type.proto\"\xf9\x01\n\x0cShopItemInfo\x12\x0f\n\x07item_id\x18\x01 \x01(\x05\x12\x12\n\nstart_time\x18\x02 \x01(\x03\x12\x10\n\x08\x65nd_time\x18\x03 \x01(\x03\x12\x30\n\x0elimit_buy_type\x18\x04 \x01(\x0e\x32\x18.zproto.ShopLimitBuyType\x12\x35\n\tbuy_count\x18\x05 \x03(\x0b\x32\".zproto.ShopItemInfo.BuyCountEntry\x1aI\n\rBuyCountEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\'\n\x05value\x18\x02 \x01(\x0b\x32\x18.zproto.ShopItemBuyLimit:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_shop_item_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SHOPITEMINFO_BUYCOUNTENTRY']._loaded_options = None
  _globals['_SHOPITEMINFO_BUYCOUNTENTRY']._serialized_options = b'8\001'
  _globals['_SHOPITEMINFO']._serialized_start=102
  _globals['_SHOPITEMINFO']._serialized_end=351
  _globals['_SHOPITEMINFO_BUYCOUNTENTRY']._serialized_start=278
  _globals['_SHOPITEMINFO_BUYCOUNTENTRY']._serialized_end=351
# @@protoc_insertion_point(module_scope)
