# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_community_kick_player_request.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_community_kick_player_request.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(stru_community_kick_player_request.proto\x12\x06zproto\"k\n\x1a\x43ommunityKickPlayerRequest\x12\x14\n\x0c\x63ommunity_id\x18\x01 \x01(\x03\x12\x13\n\x0bhomeland_id\x18\x02 \x01(\x03\x12\x10\n\x08\x63har_ids\x18\x03 \x03(\x03\x12\x10\n\x08is_outer\x18\x04 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_community_kick_player_request_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMUNITYKICKPLAYERREQUEST']._serialized_start=52
  _globals['_COMMUNITYKICKPLAYERREQUEST']._serialized_end=159
# @@protoc_insertion_point(module_scope)
