# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_notify_homeland_warehouse_grid_change_request.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_notify_homeland_warehouse_grid_change_request.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_community_warehouse_grid_pb2 as stru__community__warehouse__grid__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n8stru_notify_homeland_warehouse_grid_change_request.proto\x12\x06zproto\x1a#stru_community_warehouse_grid.proto\"^\n(NotifyHomelandWarehouseGridChangeRequest\x12\x32\n\nitem_infos\x18\x01 \x03(\x0b\x32\x1e.zproto.CommunityWarehouseGridb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_notify_homeland_warehouse_grid_change_request_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NOTIFYHOMELANDWAREHOUSEGRIDCHANGEREQUEST']._serialized_start=105
  _globals['_NOTIFYHOMELANDWAREHOUSEGRIDCHANGEREQUEST']._serialized_end=199
# @@protoc_insertion_point(module_scope)
