# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_community_remove_structure_request.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_community_remove_structure_request.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_structure_land_op_pb2 as stru__structure__land__op__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-stru_community_remove_structure_request.proto\x12\x06zproto\x1a\x1cstru_structure_land_op.proto\"W\n\x1f\x43ommunityRemoveStructureRequest\x12\x0f\n\x07home_id\x18\x01 \x01(\x03\x12#\n\x02op\x18\x02 \x01(\x0b\x32\x17.zproto.StructureLandOpb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_community_remove_structure_request_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMUNITYREMOVESTRUCTUREREQUEST']._serialized_start=87
  _globals['_COMMUNITYREMOVESTRUCTUREREQUEST']._serialized_end=174
# @@protoc_insertion_point(module_scope)
