# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_fish_setting.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_fish_setting.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_fish_record_pb2 as stru__fish__record__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17stru_fish_setting.proto\x12\x06zproto\x1a\x16stru_fish_record.proto\"\xcd\x04\n\x0b\x46ishSetting\x12\x0f\n\x07\x62\x61it_id\x18\x02 \x01(\x05\x12\x13\n\x0b\x65xperiences\x18\x03 \x01(\x05\x12\x18\n\x10research_fish_id\x18\x04 \x01(\x05\x12:\n\x0c\x66ish_records\x18\x05 \x03(\x0b\x32$.zproto.FishSetting.FishRecordsEntry\x12G\n\x13\x66ish_rod_durability\x18\x06 \x03(\x0b\x32*.zproto.FishSetting.FishRodDurabilityEntry\x12\x10\n\x08rod_uuid\x18\x07 \x01(\x04\x12:\n\x0clevel_reward\x18\x08 \x03(\x0b\x32$.zproto.FishSetting.LevelRewardEntry\x12?\n\x0fzero_fish_times\x18\t \x03(\x0b\x32&.zproto.FishSetting.ZeroFishTimesEntry\x1a\x46\n\x10\x46ishRecordsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12!\n\x05value\x18\x02 \x01(\x0b\x32\x12.zproto.FishRecord:\x02\x38\x01\x1a\x38\n\x16\x46ishRodDurabilityEntry\x12\x0b\n\x03key\x18\x01 \x01(\x04\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x1a\x32\n\x10LevelRewardEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x08:\x02\x38\x01\x1a\x34\n\x12ZeroFishTimesEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x03:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_fish_setting_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FISHSETTING_FISHRECORDSENTRY']._loaded_options = None
  _globals['_FISHSETTING_FISHRECORDSENTRY']._serialized_options = b'8\001'
  _globals['_FISHSETTING_FISHRODDURABILITYENTRY']._loaded_options = None
  _globals['_FISHSETTING_FISHRODDURABILITYENTRY']._serialized_options = b'8\001'
  _globals['_FISHSETTING_LEVELREWARDENTRY']._loaded_options = None
  _globals['_FISHSETTING_LEVELREWARDENTRY']._serialized_options = b'8\001'
  _globals['_FISHSETTING_ZEROFISHTIMESENTRY']._loaded_options = None
  _globals['_FISHSETTING_ZEROFISHTIMESENTRY']._serialized_options = b'8\001'
  _globals['_FISHSETTING']._serialized_start=60
  _globals['_FISHSETTING']._serialized_end=649
  _globals['_FISHSETTING_FISHRECORDSENTRY']._serialized_start=415
  _globals['_FISHSETTING_FISHRECORDSENTRY']._serialized_end=485
  _globals['_FISHSETTING_FISHRODDURABILITYENTRY']._serialized_start=487
  _globals['_FISHSETTING_FISHRODDURABILITYENTRY']._serialized_end=543
  _globals['_FISHSETTING_LEVELREWARDENTRY']._serialized_start=545
  _globals['_FISHSETTING_LEVELREWARDENTRY']._serialized_end=595
  _globals['_FISHSETTING_ZEROFISHTIMESENTRY']._serialized_start=597
  _globals['_FISHSETTING_ZEROFISHTIMESENTRY']._serialized_end=649
# @@protoc_insertion_point(module_scope)
