# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_dungeon_ready_info.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_dungeon_ready_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_dungeon_ready_buffer_info_pb2 as stru__dungeon__ready__buffer__info__pb2
import stru_dungeon_ready_item_info_pb2 as stru__dungeon__ready__item__info__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dstru_dungeon_ready_info.proto\x12\x06zproto\x1a$stru_dungeon_ready_buffer_info.proto\x1a\"stru_dungeon_ready_item_info.proto\"\xb3\x01\n\x10\x44ungeonReadyInfo\x12\x10\n\x08is_ready\x18\x01 \x01(\x08\x12-\n\x05\x62uffs\x18\x02 \x03(\x0b\x32\x1e.zproto.DungeonReadyBufferInfo\x12\x31\n\x0bmedicaments\x18\x03 \x03(\x0b\x32\x1c.zproto.DungeonReadyItemInfo\x12+\n\x05items\x18\x04 \x03(\x0b\x32\x1c.zproto.DungeonReadyItemInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_dungeon_ready_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DUNGEONREADYINFO']._serialized_start=116
  _globals['_DUNGEONREADYINFO']._serialized_end=295
# @@protoc_insertion_point(module_scope)
