# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_mahjong_sync_op_message.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_mahjong_sync_op_message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_mahjong_operation_pb2 as stru__mahjong__operation__pb2
import stru_mahjong_player_self_pb2 as stru__mahjong__player__self__pb2
import stru_mahjong_player_show_pb2 as stru__mahjong__player__show__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"stru_mahjong_sync_op_message.proto\x12\x06zproto\x1a\x1cstru_mahjong_operation.proto\x1a\x1estru_mahjong_player_self.proto\x1a\x1estru_mahjong_player_show.proto\"\x85\x02\n\x14MahjongSyncOpMessage\x12+\n\toperation\x18\x01 \x01(\x0b\x32\x18.zproto.MahjongOperation\x12\r\n\x05\x64oras\x18\x02 \x03(\x05\x12\x15\n\rcurrent_index\x18\x03 \x01(\x05\x12\x13\n\x0blizhi_count\x18\x04 \x01(\x05\x12\x15\n\rhonba_counter\x18\x05 \x01(\x05\x12\x12\n\ncard_index\x18\x06 \x01(\x05\x12*\n\x07players\x18\x07 \x03(\x0b\x32\x19.zproto.MahjongPlayerShow\x12.\n\x0bplayer_self\x18\x08 \x01(\x0b\x32\x19.zproto.MahjongPlayerSelfb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_mahjong_sync_op_message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MAHJONGSYNCOPMESSAGE']._serialized_start=141
  _globals['_MAHJONGSYNCOPMESSAGE']._serialized_end=402
# @@protoc_insertion_point(module_scope)
