# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_scene_init_params.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_scene_init_params.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_dungeon_hot_key_context_pb2 as stru__dungeon__hot__key__context__pb2
import stru_dungeon_single_ai_mode_context_pb2 as stru__dungeon__single__ai__mode__context__pb2
import stru_dungeon_union_info_pb2 as stru__dungeon__union__info__pb2
import stru_homeland_info_pb2 as stru__homeland__info__pb2
import stru_match_key_info_pb2 as stru__match__key__info__pb2
import stru_planet_memory_context_pb2 as stru__planet__memory__context__pb2
import stru_ride_seat_info_pb2 as stru__ride__seat__info__pb2
import stru_weekly_tower_info_pb2 as stru__weekly__tower__info__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cstru_scene_init_params.proto\x12\x06zproto\x1a\"stru_dungeon_hot_key_context.proto\x1a)stru_dungeon_single_ai_mode_context.proto\x1a\x1dstru_dungeon_union_info.proto\x1a\x18stru_homeland_info.proto\x1a\x19stru_match_key_info.proto\x1a stru_planet_memory_context.proto\x1a\x19stru_ride_seat_info.proto\x1a\x1cstru_weekly_tower_info.proto\x1a\x19google/protobuf/any.proto\"\x98\x05\n\x0fSceneInitParams\x12\x0e\n\x06owners\x18\x01 \x03(\x03\x12\x13\n\x0b\x63hange_flag\x18\x04 \x01(\x03\x12,\n\x07\x63ontext\x18\x05 \x01(\x0b\x32\x1b.zproto.PlanetMemoryContext\x12\x0f\n\x07\x61\x66\x66ixes\x18\x06 \x03(\x05\x12\x0f\n\x07team_id\x18\x07 \x01(\x05\x12\x14\n\x0c\x63ommunity_id\x18\x08 \x01(\x03\x12\x13\n\x0bhomeland_id\x18\t \x01(\x03\x12\x18\n\x10\x63ommunity_map_id\x18\n \x01(\x05\x12+\n\rhomeland_info\x18\x0c \x01(\x0b\x32\x14.zproto.HomelandInfo\x12,\n\nunion_info\x18\x0f \x01(\x0b\x32\x18.zproto.DungeonUnionInfo\x12\x42\n\x16single_ai_mode_context\x18\x10 \x01(\x0b\x32\".zproto.DungeonSingleAiModeContext\x12=\n\x17\x64ungeon_hot_key_context\x18\x11 \x01(\x0b\x32\x1c.zproto.DungeonHotKeyContext\x12\x18\n\x10scene_guid_index\x18\x13 \x01(\t\x12\x32\n\x11weekly_tower_info\x18\x14 \x01(\x0b\x32\x17.zproto.WeeklyTowerInfo\x12,\n\x0eride_seat_info\x18\x15 \x01(\x0b\x32\x14.zproto.RideSeatInfo\x12)\n\x0binit_params\x18\x16 \x03(\x0b\x32\x14.google.protobuf.Any\x12\x18\n\x10master_mode_diff\x18\x17 \x01(\x05\x12,\n\x0ematch_key_info\x18\x18 \x01(\x0b\x32\x14.zproto.MatchKeyInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_scene_init_params_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCENEINITPARAMS']._serialized_start=322
  _globals['_SCENEINITPARAMS']._serialized_end=986
# @@protoc_insertion_point(module_scope)
