# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_dungeon_revive_info.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_dungeon_revive_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1estru_dungeon_revive_info.proto\x12\x06zproto\"\x97\x01\n\x11\x44ungeonReviveInfo\x12\x12\n\nrevive_ids\x18\x01 \x03(\x05\x12<\n\nrevive_map\x18\x02 \x03(\x0b\x32(.zproto.DungeonReviveInfo.ReviveMapEntry\x1a\x30\n\x0eReviveMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_dungeon_revive_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DUNGEONREVIVEINFO_REVIVEMAPENTRY']._loaded_options = None
  _globals['_DUNGEONREVIVEINFO_REVIVEMAPENTRY']._serialized_options = b'8\001'
  _globals['_DUNGEONREVIVEINFO']._serialized_start=43
  _globals['_DUNGEONREVIVEINFO']._serialized_end=194
  _globals['_DUNGEONREVIVEINFO_REVIVEMAPENTRY']._serialized_start=146
  _globals['_DUNGEONREVIVEINFO_REVIVEMAPENTRY']._serialized_end=194
# @@protoc_insertion_point(module_scope)
