# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_level_proficiency.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_level_proficiency.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_unlock_proficiency_pb2 as stru__unlock__proficiency__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cstru_level_proficiency.proto\x12\x06zproto\x1a\x1dstru_unlock_proficiency.proto\"\xcc\x02\n\x10LevelProficiency\x12P\n\x15using_proficiency_map\x18\x01 \x03(\x0b\x32\x31.zproto.LevelProficiency.UsingProficiencyMapEntry\x12R\n\x16unlock_proficiency_map\x18\x02 \x03(\x0b\x32\x32.zproto.LevelProficiency.UnlockProficiencyMapEntry\x1a:\n\x18UsingProficiencyMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x1aV\n\x19UnlockProficiencyMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12(\n\x05value\x18\x02 \x01(\x0b\x32\x19.zproto.UnlockProficiency:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_level_proficiency_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LEVELPROFICIENCY_USINGPROFICIENCYMAPENTRY']._loaded_options = None
  _globals['_LEVELPROFICIENCY_USINGPROFICIENCYMAPENTRY']._serialized_options = b'8\001'
  _globals['_LEVELPROFICIENCY_UNLOCKPROFICIENCYMAPENTRY']._loaded_options = None
  _globals['_LEVELPROFICIENCY_UNLOCKPROFICIENCYMAPENTRY']._serialized_options = b'8\001'
  _globals['_LEVELPROFICIENCY']._serialized_start=72
  _globals['_LEVELPROFICIENCY']._serialized_end=404
  _globals['_LEVELPROFICIENCY_USINGPROFICIENCYMAPENTRY']._serialized_start=258
  _globals['_LEVELPROFICIENCY_USINGPROFICIENCYMAPENTRY']._serialized_end=316
  _globals['_LEVELPROFICIENCY_UNLOCKPROFICIENCYMAPENTRY']._serialized_start=318
  _globals['_LEVELPROFICIENCY_UNLOCKPROFICIENCYMAPENTRY']._serialized_end=404
# @@protoc_insertion_point(module_scope)
