# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_season_master_mode_dungeon_info.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_season_master_mode_dungeon_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_master_mode_diff_dungeon_info_pb2 as stru__master__mode__diff__dungeon__info__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*stru_season_master_mode_dungeon_info.proto\x12\x06zproto\x1a(stru_master_mode_diff_dungeon_info.proto\"\xfc\x02\n\x1bSeasonMasterModeDungeonInfo\x12Z\n\x15master_mode_diff_info\x18\x01 \x03(\x0b\x32;.zproto.SeasonMasterModeDungeonInfo.MasterModeDiffInfoEntry\x12 \n\x18\x64ungeon_info_update_time\x18\x02 \x01(\x03\x12L\n\rseason_awards\x18\x03 \x03(\x0b\x32\x35.zproto.SeasonMasterModeDungeonInfo.SeasonAwardsEntry\x1a\\\n\x17MasterModeDiffInfoEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x30\n\x05value\x18\x02 \x01(\x0b\x32!.zproto.MasterModeDiffDungeonInfo:\x02\x38\x01\x1a\x33\n\x11SeasonAwardsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_season_master_mode_dungeon_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SEASONMASTERMODEDUNGEONINFO_MASTERMODEDIFFINFOENTRY']._loaded_options = None
  _globals['_SEASONMASTERMODEDUNGEONINFO_MASTERMODEDIFFINFOENTRY']._serialized_options = b'8\001'
  _globals['_SEASONMASTERMODEDUNGEONINFO_SEASONAWARDSENTRY']._loaded_options = None
  _globals['_SEASONMASTERMODEDUNGEONINFO_SEASONAWARDSENTRY']._serialized_options = b'8\001'
  _globals['_SEASONMASTERMODEDUNGEONINFO']._serialized_start=97
  _globals['_SEASONMASTERMODEDUNGEONINFO']._serialized_end=477
  _globals['_SEASONMASTERMODEDUNGEONINFO_MASTERMODEDIFFINFOENTRY']._serialized_start=332
  _globals['_SEASONMASTERMODEDUNGEONINFO_MASTERMODEDIFFINFOENTRY']._serialized_end=424
  _globals['_SEASONMASTERMODEDUNGEONINFO_SEASONAWARDSENTRY']._serialized_start=426
  _globals['_SEASONMASTERMODEDUNGEONINFO_SEASONAWARDSENTRY']._serialized_end=477
# @@protoc_insertion_point(module_scope)
