# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stru_enter_act_request.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stru_enter_act_request.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stru_match_param_context_pb2 as stru__match__param__context__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cstru_enter_act_request.proto\x12\x06zproto\x1a\x1estru_match_param_context.proto\"Y\n\x0f\x45nterActRequest\x12\x0e\n\x06\x61\x63t_id\x18\x01 \x01(\x05\x12\x36\n\x13match_param_context\x18\x02 \x01(\x0b\x32\x19.zproto.MatchParamContextb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stru_enter_act_request_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENTERACTREQUEST']._serialized_start=72
  _globals['_ENTERACTREQUEST']._serialized_end=161
# @@protoc_insertion_point(module_scope)
