# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: TargetTrackTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'TargetTrackTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16TargetTrackTable.proto\x12\x06\x62okura\"\xaa\x01\n\x14TargetTrackTableBase\x12\x0b\n\x02id\x18\xb7\x0b \x01(\x05\x12\r\n\x04type\x18\xa1\x05 \x01(\t\x12\r\n\x04team\x18\xd4\x06 \x01(\x05\x12\x14\n\x0bscene_track\x18\xea\x04 \x01(\x05\x12\x12\n\tmap_track\x18\xb3\x08 \x01(\x05\x12\x17\n\x0estart_distance\x18\xe4\x0e \x01(\x05\x12\x15\n\x0c\x65nd_distance\x18\x8f\r \x01(\x05\x12\r\n\x04icon\x18\x81\t \x01(\t\"\x98\x01\n\x13TargetTrackTableMgr\x12\x35\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32&.bokura.TargetTrackTableMgr.DatasEntry\x1aJ\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12+\n\x05value\x18\x02 \x01(\x0b\x32\x1c.bokura.TargetTrackTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'TargetTrackTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TARGETTRACKTABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_TARGETTRACKTABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_TARGETTRACKTABLEBASE']._serialized_start=35
  _globals['_TARGETTRACKTABLEBASE']._serialized_end=205
  _globals['_TARGETTRACKTABLEMGR']._serialized_start=208
  _globals['_TARGETTRACKTABLEMGR']._serialized_end=360
  _globals['_TARGETTRACKTABLEMGR_DATASENTRY']._serialized_start=286
  _globals['_TARGETTRACKTABLEMGR_DATASENTRY']._serialized_end=360
# @@protoc_insertion_point(module_scope)
