# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: WorldEventAwardTable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'WorldEventAwardTable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aWorldEventAwardTable.proto\x12\x06\x62okura\":\n\x18WorldEventAwardTableBase\x12\x0e\n\x05score\x18\xa3\r \x01(\x05\x12\x0e\n\x05\x61ward\x18\xbb\x01 \x01(\x05\"\xa4\x01\n\x17WorldEventAwardTableMgr\x12\x39\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32*.bokura.WorldEventAwardTableMgr.DatasEntry\x1aN\n\nDatasEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12/\n\x05value\x18\x02 \x01(\x0b\x32 .bokura.WorldEventAwardTableBase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WorldEventAwardTable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WORLDEVENTAWARDTABLEMGR_DATASENTRY']._loaded_options = None
  _globals['_WORLDEVENTAWARDTABLEMGR_DATASENTRY']._serialized_options = b'8\001'
  _globals['_WORLDEVENTAWARDTABLEBASE']._serialized_start=38
  _globals['_WORLDEVENTAWARDTABLEBASE']._serialized_end=96
  _globals['_WORLDEVENTAWARDTABLEMGR']._serialized_start=99
  _globals['_WORLDEVENTAWARDTABLEMGR']._serialized_end=263
  _globals['_WORLDEVENTAWARDTABLEMGR_DATASENTRY']._serialized_start=185
  _globals['_WORLDEVENTAWARDTABLEMGR_DATASENTRY']._serialized_end=263
# @@protoc_insertion_point(module_scope)
